### ISSUE TITLE
[Feature Request] Option to treat as a normal window.

### ISSUE THREAD

**Issue by Athanasius** [msarilar/EDEngineer#10]
For those of us with multiple monitors can you make an option to have the window just be a normal one?  Even if I unlock the window and right click the title bar to access 'minimise' I still end up with a small window bottom-left of my primary monitor.

Edit: I can at least drag the minimised window to somewhere more convenient, but my request still stands.

**Comment by msarilar** [comment]
Why not use the shortcut to hide/show it, rather than minimize?

**Comment by Athanasius** [comment]
Well, that's another issue, since taking the update this morning I can't get that to work, neither the default Ctrl-F10, nor the Shift-F12 I'd changed it to.  When I finally remembered that the only way to get at the options is the systray icon I do indeed still have it set to Shift+F12.

Setting that back to Ctrl-F10 works.  Re-setting Shift=F12 doesn't.

But anyway, I'd simply like to have the window on my second monitor AND not 'always on top', I just want it to act 100% like a normal window.

So, my usage pattern goes like this:

1) Run EDEngineer
2) Have it pop up over the ED window
3) Want to check it has the right things, or refer to it otherwise whilst also looking at things in-game, so
4) Unlock window and drag to other monitor.
5) Now it's blocking looking at other windows, and I'd really like to just alt-tab/change focus and raise other windows, not use an application-specific shortcut to hide/show it.

Indeed if I do use the shortcut, OR if not, the application doesn't appear on alt-tab or windows-tab at all.

I can appreciate you're trying to make this app easy to use for those with only one monitor, but it's blocking normal use of it.

**Comment by msarilar** [comment]
Will be next version

**Comment by msarilar** [comment]
Fix deployed, please restart the application

**Comment by Athanasius** [comment]
Ah, that's better :)  Now I can just manage windows as normal with it unlocked.  Thanks!
