### ISSUE TITLE
Access via browser

### ISSUE THREAD

**Issue by Strayer** [msarilar/EDEngineer#11]
[As suggested on Reddit](https://www.reddit.com/r/EliteDangerous/comments/5b3dpt/edengineer_an_overlay_to_track_your_blueprint/d9m6sea/), it would be awesome if the data would also be accessible via browser, possibly even from remote systems, if configured.

The Reddit user mentions the use of a VR utility that allows to display browser windows inside VR. My use case would be a little bit different, I'd want to access this data from a separate machine (my MacBook) that I always have next to my gaming computer while playing Elite.

**Comment by msarilar** [comment]
Thanks for the suggestion, but that would require a different technology stack than WPF/XAML ! Maybe someone will do that in another project :)
