### ISSUE TITLE
Feature Request: Shopping list

### ISSUE THREAD

**Issue by xermalk** [msarilar/EDEngineer#114]
Hi
Any chance we could get a Engineering Shopping list

- select a few schematics
- set how many of each you want to build
- and get a "shopping" list with all the materials you are missing.

**Comment by msarilar** [comment]
published in 1.0.4.0

**Comment by Jibsman** [comment]
Upvote! I would like to be able to print out the list of materials needed after selecting the engineering. Perhaps add the Material Trader items opened so we can see everything we need to trade for.
