### ISSUE TITLE
Win 10 crash

### ISSUE THREAD

**Issue by rizal72** [msarilar/EDEngineer#12]
Hello CMDR,
as I've already reported on your reddit post, I am not ablew to let the app run on WIN 10 (latest update).
After launching start.exe, the app downloads correctly, but then it crashes on start.
I'm attaching my ED logs as well.

I'm pasting here the event logs:

Application: EDEngineer.exe Framework Version: v4.0.30319 Description: The process was terminated due to an unhandled exception. Exception Info: System.NullReferenceException at EDEngineer.Utils.JournalEntryConverter.ReadJson(Newtonsoft.Json.JsonReader, System.Type, System.Object, Newtonsoft.Json.JsonSerializer) at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.DeserializeConvertable(Newtonsoft.Json.JsonConverter, Newtonsoft.Json.JsonReader, System.Type, System.Object) at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(Newtonsoft.Json.JsonReader, System.Type, Boolean) at Newtonsoft.Json.JsonSerializer.DeserializeInternal(Newtonsoft.Json.JsonReader, System.Type) at Newtonsoft.Json.JsonConvert.DeserializeObject(System.String, System.Type, Newtonsoft.Json.JsonSerializerSettings) at Newtonsoft.Json.JsonConvert.DeserializeObject(System.String, System.Type, Newtonsoft.Json.JsonConverter[]) at Newtonsoft.Json.JsonConvert.DeserializeObject[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]](System.String, Newtonsoft.Json.JsonConverter[]) at EDEngineer.MainWindowViewModel.<ApplyEventsToSate>b__30_0(System.String) at System.Linq.Enumerable+WhereSelectEnumerableIterator`2[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089],[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].MoveNext() at System.Linq.Enumerable+WhereEnumerableIterator`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].MoveNext() at System.Linq.Buffer`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]]..ctor(System.Collections.Generic.IEnumerable`1<System.__Canon>) at System.Linq.OrderedEnumerable`1+<GetEnumerator>d__1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].MoveNext() at System.Collections.Generic.List`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]]..ctor(System.Collections.Generic.IEnumerable`1<System.__Canon>) at System.Linq.Enumerable.ToList[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]](System.Collections.Generic.IEnumerable`1<System.__Canon>) at EDEngineer.MainWindowViewModel.ApplyEventsToSate(System.Collections.Generic.IEnumerable`1<System.String>) at EDEngineer.MainWindowViewModel.LoadState(Boolean) at EDEngineer.MainWindowViewModel..ctor() at EDEngineer.MainWindow..ctor() Exception Info: System.Reflection.TargetInvocationException at System.RuntimeTypeHandle.CreateInstance(System.RuntimeType, Boolean, Boolean, Boolean ByRef, System.RuntimeMethodHandleInternal ByRef, Boolean ByRef) at System.RuntimeType.CreateInstanceSlow(Boolean, Boolean, Boolean, System.Threading.StackCrawlMark ByRef) at System.RuntimeType.CreateInstanceDefaultCtor(Boolean, Boolean, Boolean, System.Threading.StackCrawlMark ByRef) at System.Activator.CreateInstance(System.Type, Boolean) at System.RuntimeType.CreateInstanceImpl(System.Reflection.BindingFlags, System.Reflection.Binder, System.Object[], System.Globalization.CultureInfo, System.Object[], System.Threading.StackCrawlMark ByRef) at System.Activator.CreateInstance(System.Type, System.Reflection.BindingFlags, System.Reflection.Binder, System.Object[], System.Globalization.CultureInfo, System.Object[]) at System.Activator.CreateInstance(System.Type, System.Object[]) at System.Xaml.Schema.SafeReflectionInvoker.CreateInstanceCritical(System.Type, System.Object[]) at System.Xaml.Schema.SafeReflectionInvoker.CreateInstance(System.Type, System.Object[]) at System.Xaml.Schema.XamlTypeInvoker.CreateInstance(System.Object[]) at MS.Internal.Xaml.Runtime.ClrObjectRuntime.CreateInstanceWithCtor(System.Xaml.XamlType, System.Object[]) at MS.Internal.Xaml.Runtime.ClrObjectRuntime.CreateInstance(System.Xaml.XamlType, System.Object[]) at System.Xaml.XamlObjectWriter.Logic_CreateAndAssignToParentStart(MS.Internal.Xaml.Context.ObjectWriterContext) at System.Xaml.XamlObjectWriter.WriteStartMember(System.Xaml.XamlMember) at System.Xaml.XamlWriter.WriteNode(System.Xaml.XamlReader) at System.Windows.Markup.WpfXamlLoader.TransformNodes(System.Xaml.XamlReader, System.Xaml.XamlObjectWriter, Boolean, Boolean, Boolean, System.Xaml.IXamlLineInfo, System.Xaml.IXamlLineInfoConsumer, MS.Internal.Xaml.Context.XamlContextStack`1<System.Windows.Markup.WpfXamlFrame>, System.Windows.Markup.IStyleConnector) at System.Windows.Markup.WpfXamlLoader.Load(System.Xaml.XamlReader, System.Xaml.IXamlObjectWriterFactory, Boolean, System.Object, System.Xaml.XamlObjectWriterSettings, System.Uri) at System.Windows.Markup.WpfXamlLoader.LoadBaml(System.Xaml.XamlReader, Boolean, System.Object, System.Xaml.Permissions.XamlAccessLevel, System.Uri) at System.Windows.Markup.XamlReader.LoadBaml(System.IO.Stream, System.Windows.Markup.ParserContext, System.Object, Boolean) at System.Windows.Application.LoadBamlStreamWithSyncInfo(System.IO.Stream, System.Windows.Markup.ParserContext) at System.Windows.Application.LoadComponent(System.Uri, Boolean) at System.Windows.Application.DoStartup() at System.Windows.Application.<.ctor>b__1_0(System.Object) at System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32) at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate) at System.Windows.Threading.DispatcherOperation.InvokeImpl() at System.Windows.Threading.DispatcherOperation.InvokeInSecurityContext(System.Object) at MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(System.Object) at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean) at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean) at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object) at MS.Internal.CulturePreservingExecutionContext.Run(MS.Internal.CulturePreservingExecutionContext, System.Threading.ContextCallback, System.Object) at System.Windows.Threading.DispatcherOperation.Invoke() at System.Windows.Threading.Dispatcher.ProcessQueue() at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef) at MS.Win32.HwndWrapper.WndProc(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef) at MS.Win32.HwndSubclass.DispatcherCallbackOperation(System.Object) at System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32) at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate) at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(System.Windows.Threading.DispatcherPriority, System.TimeSpan, System.Delegate, System.Object, Int32) at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr, Int32, IntPtr, IntPtr) at MS.Win32.UnsafeNativeMethods.DispatchMessage(System.Windows.Interop.MSG ByRef) at System.Windows.Threading.Dispatcher.PushFrameImpl(System.Windows.Threading.DispatcherFrame) at System.Windows.Threading.Dispatcher.PushFrame(System.Windows.Threading.DispatcherFrame) at System.Windows.Application.RunDispatcher(System.Object) at System.Windows.Application.RunInternal(System.Windows.Window) at System.Windows.Application.Run(System.Windows.Window) at System.Windows.Application.Run() at EDEngineer.App.Main() 

**THEN THIS ONE:**
EDEngineer.exe 
   1.0.0.0 
   581d30f0 
   KERNELBASE.dll 
   10.0.14393.321 
   57f4c291 
   e0434352 
   000da6f2 
   302c 
   01d237573e7e478b 
   C:\Users\Riccardo\AppData\Local\Apps\2.0\COCDD75Q.VYY\3RJMR55A.9PL\eden..tion_c7c2cd04d2cdd815_0001.0000_f06a00ee6656da7b\EDEngineer.exe 
   C:\WINDOWS\System32\KERNELBASE.dll 
   cf7c7c26-902d-4637-ac13-100e52f04f9e 

**AND THIS:**

Log Name:      Application
Source:        Windows Error Reporting
Date:          05/11/2016 12:25:02
Event ID:      1001
Task Category: None
Level:         Information
Keywords:      Classic
User:          N/A
Computer:      Gaming-PC
Description:
Fault bucket 129261103479, type 5
Event Name: CLR20r3
Response: Not available
Cab Id: 0

Problem signature:
P1: EDEngineer.exe
P2: 1.0.0.0
P3: 581d30f0
P4: EDEngineer
P5: 1.0.0.0
P6: 581d30f0
P7: 95
P8: 456
P9: N3CTRYE2KN3C34SGL4ZQYRBFTE4M13NB
P10: 

Attached files:
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER37B4.tmp.WERInternalMetadata.xml
\\?\C:\Users\Riccardo\AppData\Local\Temp\WER3D53.tmp.appcompat.txt
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER3D63.tmp.dmp
\\?\C:\Users\Riccardo\AppData\Local\Temp\WER3EBC.tmp.WERDataCollectionFailure.txt

These files may be available here:
C:\ProgramData\Microsoft\Windows\WER\ReportArchive\AppCrash_EDEngineer.exe_c020f0197d8abb3f57596bbae62b66e13d366f4_be0c3adc_2ccb3eb9

Analysis symbol: 
Rechecking for solution: 0
Report ID: cf7c7c26-902d-4637-ac13-100e52f04f9e
Report Status: 4104
Hashed bucket: b120f188819c8f581f5e0c44f05eac47
Event Xml:
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name="Windows Error Reporting" />
    <EventID Qualifiers="0">1001</EventID>
    <Level>4</Level>
    <Task>0</Task>
    <Keywords>0x80000000000000</Keywords>
    <TimeCreated SystemTime="2016-11-05T11:25:02.065483600Z" />
    <EventRecordID>4325</EventRecordID>
    <Channel>Application</Channel>
    <Computer>Gaming-PC</Computer>
    <Security />
  </System>
  <EventData>
    <Data>129261103479</Data>
    <Data>5</Data>
    <Data>CLR20r3</Data>
    <Data>Not available</Data>
    <Data>0</Data>
    <Data>EDEngineer.exe</Data>
    <Data>1.0.0.0</Data>
    <Data>581d30f0</Data>
    <Data>EDEngineer</Data>
    <Data>1.0.0.0</Data>
    <Data>581d30f0</Data>
    <Data>95</Data>
    <Data>456</Data>
    <Data>N3CTRYE2KN3C34SGL4ZQYRBFTE4M13NB</Data>
    <Data>
    </Data>
    <Data>
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER37B4.tmp.WERInternalMetadata.xml
\\?\C:\Users\Riccardo\AppData\Local\Temp\WER3D53.tmp.appcompat.txt
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER3D63.tmp.dmp
\\?\C:\Users\Riccardo\AppData\Local\Temp\WER3EBC.tmp.WERDataCollectionFailure.txt</Data>
    <Data>C:\ProgramData\Microsoft\Windows\WER\ReportArchive\AppCrash_EDEngineer.exe_c020f0197d8abb3f57596bbae62b66e13d366f4_be0c3adc_2ccb3eb9</Data>
    <Data>
    </Data>
    <Data>0</Data>
    <Data>cf7c7c26-902d-4637-ac13-100e52f04f9e</Data>
    <Data>4104</Data>
    <Data>b120f188819c8f581f5e0c44f05eac47</Data>
  </EventData>
</Event>

[Elite Dangerous_logs.zip](https://github.com/msarilar/EDEngineer/files/573157/Elite.Dangerous_logs.zip)

**Comment by msarilar** [comment]
Thank you !
Will be fixed next update.

**Comment by msarilar** [comment]
Fix deployed, please restart the application
