### ISSUE TITLE
Launching via Command Line

### ISSUE THREAD

**Issue by rosscarlson** [msarilar/EDEngineer#120]
Not really a bug so my apologies, wasn't sure where to ask.  I'd like to launch EDEngineer via VoiceAttack (so via command line).  I know it's not a standard .exe but can't figure out how I'd launch it from the command line.

Thoughts?

Great app BTW, I've never bothered with Engineering as it's such a pain in the ass but have been thanks to this.

**Comment by msarilar** [comment]
It's actually a standard exe, it's just that it doesn't install in places where it would need administrator privileges (e.g. Program Files).

The place where it gets installed is a bit obfuscated (ClickOnce does that for security reason afaik), mine is `C:\Users\Max\AppData\Local\Apps\2.0\4GRCJBPK.N20\4JBM3Q58.BEO\eden..tion_c7c2cd04d2cdd815_0001.0000_d2d9c83992af26fb` for example.

If you launch EDEngineer and you go to your task manager, you can right click the process and in the context menu you'll find something like "Go to file emplacement" or something similar. That will show you the place of the executable.

That place is not supposed to change (unless you uninstall in which case the entire folder gets cleared).

PS: this is the right place to ask questions! there's even a label for these :)

**Comment by rosscarlson** [comment]
Ah, great, thanks for sharing.  Exactly what I needed.

Fantastic app BTW, I had ZERO interest in Engineering until this.
