### ISSUE TITLE
Unexpected Emission Data does not update

### ISSUE THREAD

**Issue by wysiwyg67** [msarilar/EDEngineer#122]
Great App. Thankyou! (Not sure if my report is supposed to go here as I'm newish to github etc.)
Unexpected Emmission Data does not update when I eject it in-game.
EDDiscovery log shows "Encoded material, emissiondata, 6 items"
Hope this helps.

**Comment by msarilar** [comment]
well spotted ! thanks for the report

**Comment by msarilar** [comment]
just published a little hotfix for that, you can restart the app and it will update

**Comment by wysiwyg67** [comment]
Cool - thanks for the fast response. This is seriously the best app yet that takes advantage of the new log in 2.2! Keep up the good work :)
