### ISSUE TITLE
Feature Request: Highlight of material/data

### ISSUE THREAD

**Issue by Gimi1967** [msarilar/EDEngineer#129]
Low priority:
Ability to click on a material (rarity icon maybe) and have that material/data highlighted. Maybe the icon could turn blue.
Would allow for marking materials as (do not discard or what is currently being searched for or anything you like). Just a quick on/off highlight feature.

**Comment by msarilar** [comment]
why not just use the favorite blueprint feature? I'm curious to know the use case of favorite ingredients

**Comment by Gimi1967** [comment]
I use that as well. The reason this came up is that I'm collecting data for unlocking engineers, you know 50 of this and that. So my storage is full and I wish to mark those as "do not discard".
Further, sometimes I'm hunting for specific materials. As I have several blueprints marked as favourites, the ability to mark one or a few as important right now would increase the readability. 
Likewise, if you have a community goal where you are handing in data or materials, you can mark those particular items as important.  Low priority, but something I would appreciate if it's not too much effort.

**Comment by msarilar** [comment]
ah yes, makes sense

I'll see what I can do, shouldn't be that complicated

**Comment by msarilar** [comment]
published in 1.0.3.4
