### ISSUE TITLE
crash on start

### ISSUE THREAD

**Issue by mordredp** [msarilar/EDEngineer#13]
Attached is Windows Events Log.

[log.txt](https://github.com/msarilar/EDEngineer/files/573184/log.txt)

**Comment by msarilar** [comment]
I'm going to need your Elite Dangerous log folder in a zip file:

C:\Users\%USERNAME%\Saved Games\Frontier Developments\Elite Dangerous

**Comment by mordredp** [comment]
GitHub does not like zips containing .log files.. Where can I upload it?

**Comment by msarilar** [comment]
Sure it does, somebody already did it and I fixed the issue for him : https://github.com/msarilar/EDEngineer/issues/12

**Comment by msarilar** [comment]
I published an update fixing #8, it might have solved your issue
