### ISSUE TITLE
Crash on download

### ISSUE THREAD

**Issue by Oscuron** [msarilar/EDEngineer#130]
Hey man, found this tool got super excited when i saw that its exactly what i need, now this.. 

i clicked on the setup.exe link in the readme, executed it and get this error message.
- restarted pc, same thing 
- run as admin, same thing
- its not being blocked by windows firewall or anti virus programm.. 

do you have a clue what it could be?

[279SAEZT_EDmaster_download_crashfile.txt](https://github.com/msarilar/EDEngineer/files/637450/279SAEZT_EDmaster_download_crashfile.txt)
[984JREM4_EDmaster_download_crashfile.txt](https://github.com/msarilar/EDEngineer/files/637451/984JREM4_EDmaster_download_crashfile.txt)

**Comment by msarilar** [comment]
I just tried to reinstall and it worked fine, so it should be alright.

have you tried the steps at the bottom of this page https://github.com/msarilar/EDEngineer/wiki/Troubleshooting-Issues ?

**Comment by Oscuron** [comment]
thanks for the fast reply.. 

yea i did all of those. still crashes sometimes at 28% somtimes at 30%..

**Comment by msarilar** [comment]
could you check the event viewer (windows+R, "`eventvwr`") in the windows logs => Application

maybe there's things in there that could shed light on the issue

apparently, some external process is trying to access EDEngineer while it is being installed

**Comment by Oscuron** [comment]
yea it says that in the crashfile, i couldnt figure out what that was supposed to mean. im guessing the temp folder is created in that instance and just used for the installation so how would something else be trying to access it at the same time?

there are no windows log that have todays date on them, so there is nothing there..

**Comment by Oscuron** [comment]
works now, i have a cleaner tool, called Glary Utilities that i turned off. I also turned of my Antivirus  Programm (Panda Cloud --> free version)
since my antivirus already told me the file is clean im guessing there is some sort of problem with Glary Utilities.. but thanks for your help!

**Comment by msarilar** [comment]
ah! I thought there was no such program running you said :D

glad you made it, I was going to give you a portable version of the application ; but the huge downside is that you would not have gotten autoupdates with it (so it would become useless pretty quickly, since Frontier is fixing bugs in their logs, adding new logs, adding new blueprints, removing commodities from blueprints soon, etc...)
