### ISSUE TITLE
Feature Request: Where to find item

### ISSUE THREAD

**Issue by rosscarlson** [msarilar/EDEngineer#131]
As part of the Shopping List feature how about a feature that would give you notes/ideas on how to find the item in question.  Something like this:

- You open your shopping list
- You click on "Modified Embedded Firmware"
- Below a box opens with details on where to find "the best place to get MEF is by scanning bases, etc."
- That data would be pulled from a cloud based datasource
- If there is no note for a particular item a link would be provided so the user can add the information
- If there is a note there would be an edit or add button for further thoughts on finding the item

That way users are building the database for you/them and you don't have to worry about that.  Alternately you could pull data from something like EDDB, etc. to seed things, etc.

It seems two of the most difficult things around engineering is knowing what you need and then where to get it.  You're off to a great start on what I need, if that can be combined with where to get it and I can get a list such as:

Datamined Wake Exceptions: Found by scanning wakes at distribution centers in anarchy space
Used for: Grade 5 multicannons

Sulphur: Mined from asteroids or on planet surfaces
Used for: Grade 1 power plants

(made those up off the top of my head)

This would greatly enhance the app and make Engineering SO much easier.

**Comment by msarilar** [comment]
That is a very good idea but there's several key points to consider:

* There's no such open API to retrieve information. EDDB has that neat feature to get the nearest market where to buy a commodity but it's not an API : I checked back then, the website outputs html directly. This would imply html parsing, relying on an external source etc...
* The data I currently show via the icons and tooltips (salvage combat ships, markets, etc...) is from inara and not retrieved in real time, and I believe there's no need for more source information
* I'm not really for adding an internet access to the software, I'd prefer to [KISS](https://en.wikipedia.org/wiki/KISS_principle) to avoid malware flagging or user paranoia in general
* Listing every blueprint that uses each ingredient in the left panel would make it very noisy, and I'm not sure it woud add a lot to the software (I mean in the game, you don't care about ingredients, you care about blueprints directly)

I thought back then about checking EDDB alongside the commander's log that indicates the current system to update in realtime the cargo list with the nearest market where to buy each commodity (for those than can be bought), but it's not worth it after considering all these points in my opinion.
