### ISSUE TITLE
EDE doesn't update from game content

### ISSUE THREAD

**Issue by rosscarlson** [msarilar/EDEngineer#132]
Per our conversation on the forum here are a few things you requested.

- (screen1.jpg) Screenshot of the EDE window, bottom showing the path.  I'm not sure why it's cutting off the final directory, "Elite Dangerous" but I've confirmed it's the exact directory in the second shot

- (screen2.jpg) Screenshot of my Journal logs directory.  I've confirmed at these are updating as I play so I'm 99% sure this is the correct directory.

- (Journal.161209212209.01.zip - really a .log file so just change the extension
![screen1](https://cloud.githubusercontent.com/assets/1846909/21076694/4a64af56-beef-11e6-98e9-396e5d456d22.JPG)
![screen2](https://cloud.githubusercontent.com/assets/1846909/21076695/4a64f506-beef-11e6-983f-1d8609292193.JPG)

) The most recent log file from my most recent play session.  In that session I picked up a number of commodities including 4 micro-weave cooling hoses.  I see a line in the file

{ "timestamp":"2016-12-10T05:14:48Z", "event":"MissionCompleted", "Faction":"Mambojas Purple Dragons", "Name":"Mission_Courier_Boom_name", "MissionID":57889784, "DestinationSystem":"Mambojas", "DestinationStation":"Patsayev Enterprise", "Reward":62638, "CommodityReward":[ { "Name": "CoolingHoses", "Count": 4 } ] }

That is from the mission where I acquired the hoses.

[Journal.161209212209.01.zip](https://github.com/msarilar/EDEngineer/files/644106/Journal.161209212209.01.zip)

**Comment by msarilar** [comment]
![image](https://cloud.githubusercontent.com/assets/5569959/21076825/2521b97c-bf36-11e6-981a-a1a1a356077e.png)

**Comment by rosscarlson** [comment]
Sorry, I tried to clarify that with the comment "I'm not sure why it's cutting off the final directory, "Elite Dangerous" but I've confirmed it's the exact directory in the second shot" - so yes, it is 100% pointing at the directory you're referring to in your screenshot, 100%.  I'm not sure why that path is getting cutoff in the display at the bottom of EDE but I assure you it is reading that directory.

Not sure how hard this would be to add but what if you put in a manual "Update Now" button that would spit out some status of what it's processing.  That way I/we could see that it is or isn't reading the files correctly.

**Comment by rosscarlson** [comment]
Adding 2 new screenshots with the correct directory being displayed.  I restarted EDE and made the window wider so you can see.

![screen3](https://cloud.githubusercontent.com/assets/1846909/21076951/c3860a6c-bef7-11e6-9cf0-2ce9446bf192.JPG)
![screen4](https://cloud.githubusercontent.com/assets/1846909/21076952/c38887a6-bef7-11e6-95bb-5080b0adb948.JPG)

**Comment by msarilar** [comment]
that is weird, the "Elite Dangerous" should be slightly visible if it can't fit; like that :
![image](https://cloud.githubusercontent.com/assets/5569959/21077006/524ecbb4-bf3c-11e6-95fc-208dba926254.png)

but anyway, why did "CMDR DEFAULT" appear on top of your screen? What happens when you click on CMDR Exigeous? 

Do you have a file in `C:\Users\Max\AppData\%USERNAME%\EDEngineer` named `manualChanges.Default.json` containing all the changes you did manually before? It is created when the user makes manual changes and hasn't selected a correct log directory (so that users can use the application even when they haven't installed elite dangerous on their computer).

I think you might have fixed the log directory just now, since the application read that folder, and successfully detected "Exigeous" as the commander.

You should close EDEngineer, delete the manualChanges file I referred to above, and start over, that should be good now :)

**Comment by rosscarlson** [comment]
DING! DING! DING! DING! DING! DING! 

God damn it.  Ugh, well, we should have known it was me.  When I clicked on "CMDR EXIGEOUS" at the top guess what happened, it shows the correct inventory from my ship!  I have to admit I obviously hadn't looked up there or had just read it incorrectly, now that I'm playing with it I get it - it's so you could have multiple commanders/accounts and manage them all from the one app.  D'oh!

So now it seems to be working perfectly.  I just setup all my favorites in the EXIGEOUS (correct) profile and it's showing inventory from my ship.  I'll play in a bit and make sure that it is in fact tracking all changes at this point but I'm now 99% sure that it is.  I'll leave this open just in case but will come close it once I've confirmed.

Again thanks for your help, as I'm sure you knew it was my fault all along!!

**Comment by msarilar** [comment]
don't forget to delete the manualChanges.Default.json file :)

glad it's now working!

**Comment by rosscarlson** [comment]
Where is that file to delete?

**Comment by msarilar** [comment]
> Do you have a file in C:\Users\Max\AppData\%USERNAME%\EDEngineer named manualChanges.Default.json containing all the changes you did manually before?

**Comment by rosscarlson** [comment]
Nope, I just checked and it's not there.  I think before when I said "manually" I was just updating the DEFAULT commander profile.  Either way I don't have a file named that on my system (just searched the whole drive).

**Comment by msarilar** [comment]
Sorry, you have to go in Local or Roaming subdirectory of AppData ; please check it and let me know

**Comment by msarilar** [comment]
`C:\Users\%USERNAME%\AppData\Local\EDEngineer`

or

`C:\Users\%USERNAME%\AppData\Roaming\EDEngineer`

**Comment by rosscarlson** [comment]
Got it - it was in Roaming (which wasn't getting indexed, grrrr).  I just renamed it to .OLD just in case, any reason to keep it around?

And again my friend I greatly appreciate all this help.  Long ago I ran an open source app for 3-4 years so I know that support like this is tricky, it's fun to help someone use your baby but frustrating as hell when you/they can't figure out what's wrong.  We'll have to wing up some time for some pew pew!!

-Ross

**Comment by msarilar** [comment]
no reason to keep it, nuke it from orbit and restart EDEngineer so you can get rid of that pesky top bar of commanders :)

**Comment by rosscarlson** [comment]
Nuked and DEFAULT is gone, whew.  Now if the grind to get materials was as easy as this I'd be golden!!

**Comment by rosscarlson** [comment]
And I'm happy to say all seems to be working, thanks for the help in figuring out my stupidity ;-)
