### ISSUE TITLE
data  and materials QTY

### ISSUE THREAD

**Issue by TheRealKurok** [msarilar/EDEngineer#133]
The Overlay does not show the same mounts of Materials and Data as in game, amounts are off. Awesome app thanks for all the hard work.

**Comment by msarilar** [comment]
hey, do you have any more details about the issue?
did you do the initialization properly (i.e. manual setup the first time of launching the application to synchronize it with the game)?

**Comment by TheRealKurok** [comment]
msarilar,

Thank you for the quick reply, I did do the initialization properly and something got wacked for the QTYs did not match even after I tried to manually set again, I went ahead and uninstalled, remove all files I could find and references to EDE and re-installed, re-initialized and it seems to be holding. I will keep an eye on it and let you know. Thank you !
