### ISSUE TITLE
Hiding or Resizing the Shopping List pane

### ISSUE THREAD

**Issue by rosscarlson** [msarilar/EDEngineer#135]
The newly added shopping list is absolutely fantastic.  One of the best features in the app honestly as it lets me know if I have enough for the number of blueprints/roles I want to do.  While know that I need MaterialX is important knowing how many I need as many blueprints use the same MaterialX.  Great addition.

However is there a way to hide or resize that pane in EDE?  My issue is I'm building up enough things to go see 5 different Engineers.  As such that's about 25 favorites I've created so the shopping list is very long, 50+ items on the list.  As it seems the shopping list pane grows each time something is added it quickly covers almost all of the favorite/blueprint list.  Am I missing a way to resize or hide that window?  If not it would be great if that was added.

**Comment by msarilar** [comment]
will be in next update (16e063a)  !
