### ISSUE TITLE
Clicking on inventory item links to blueprints

### ISSUE THREAD

**Issue by rosscarlson** [msarilar/EDEngineer#136]
If this isn't a good place for feature requests my apologies.

While the drop down list on the top right to see what item goes with what blueprints that same functionality from the inventory list at the left would be great.  Seeing I have 4 articulation motors and then being able to see all blueprints that use that item (based on the current filters) would be great.  I constantly use the drop down which is a bit clunky given how long it is.

**Comment by msarilar** [comment]
shouldn't be too hard to implement a filter shortcut that would clear all active filters and select the ingredient filter associated, but it might be a tad confusing for new users or users who are unaware of it. 

I'll think about it and see if I come up with something good enough 👍

**Comment by rosscarlson** [comment]
That's totally fair, certainly not a critical feature - just nice to have.

**Comment by rosscarlson** [comment]
In thinking about this a bit more I'm wondering if it would be any harder or more confusing than the existing dropdown in the upper right?  What I mean is wouldn't you use the same code and display the same results as if I selected the item in the drop down top right?  Obviously I don't know your code base so maybe that's a stupid thought.  It's obviously a less than critical addition so I suppose it should go on the list as such.

**Comment by msarilar** [comment]
after thinking about it I don't think I'll do that as it would conflict with the current existing feature that makes inventory items highlightable

we completely redesign the left panel to make it behave similarly to the blueprint list (expandable blocks, favoritables, etc...) but it's too much trouble for what it's worth in my opinion
