### ISSUE TITLE
Logs to accompany my crash report on Reddit

### ISSUE THREAD

**Issue by zeroKFE** [msarilar/EDEngineer#14]
Here's my logs to accompany my report of having the application crash immediately upon launch.

Thanks for all your hard work!
[EliteDangerousLogs.zip](https://github.com/msarilar/EDEngineer/files/573205/EliteDangerousLogs.zip)

**Comment by msarilar** [comment]
Already fixed in 1.0.0.5 afaik, please update the application (close and reopen)
