### ISSUE TITLE
Materials not updating

### ISSUE THREAD

**Issue by okmerflow** [msarilar/EDEngineer#140]
Hi, I'm using your tool now (looks really great!) but it's not updating my materials (it's always on zero). Commodities on the other hand is working well. Any idea what i can try to solve this?

Thanks in advance!

**Comment by msarilar** [comment]
can't check the issue right now, but feel free to take a look at these

#133 
#132
https://github.com/msarilar/EDEngineer/wiki/Troubleshooting-Issues
