### ISSUE TITLE
Application crash on startup, unable to reinstall.

### ISSUE THREAD

**Issue by RustyGentleman** [msarilar/EDEngineer#141]
I had it working just a couple days ago. Today I tried running it and it'd _stop working_, with the event name 'CLR20r3'.

I tried repairing .NET 4.5, which looking the event name up led me to, but that did nothing. So I ran it again and went on task manager > open file location, which sent me to some folder within AppData\Local. I deleted that folder and 3 others with similar names (certainly related to EDEngineer), then downloaded the setup from here, again, and tried to reinstall it, but that gives me another error: **Application cannot be started. Contact the application vendor.**, with a "Details..." button.
I read through it a bit, and the issue seems to be an _invalid directory name_, on Github's end.

Awaiting a reply.

> PLATFORM VERSION INFO
	Windows 			: 6.1.7601.65536 (Win32NT)
	Common Language Runtime 	: 4.0.30319.42000
	System.Deployment.dll 		: 4.6.1055.0 built by: NETFXREL2
	clr.dll 			: 4.6.1055.0 built by: NETFXREL2
	dfdll.dll 			: 4.6.1055.0 built by: NETFXREL2
	dfshim.dll 			: 4.0.41209.0 (Main.041209-0000)

> SOURCES
	Deployment url			: https://raw.githubusercontent.com/msarilar/EDEngineer/master/EDEngineer/releases/EDEngineer.application

> IDENTITIES
	Deployment Identity		: EDEngineer.application, Version=1.0.4.0, Culture=neutral, PublicKeyToken=c7c2cd04d2cdd815, processorArchitecture=msil

> APPLICATION SUMMARY
	* Installable application.

> **ERROR SUMMARY
	Below is a summary of the errors, details of these errors are listed later in the log.
	* Activation of https://raw.githubusercontent.com/msarilar/EDEngineer/master/EDEngineer/releases/EDEngineer.application resulted in exception. Following failure messages were detected:
		+ The directory name is invalid. (Exception from HRESULT: 0x8007010B)**

> COMPONENT STORE TRANSACTION FAILURE SUMMARY
	No transaction error was detected.

> WARNINGS
	There were no warnings during this operation.

> OPERATION PROGRESS STATUS
	* [29/12/2016 19:39:13] : Activation of https://raw.githubusercontent.com/msarilar/EDEngineer/master/EDEngineer/releases/EDEngineer.application has started.
	* [29/12/2016 19:39:13] : Processing of deployment manifest has successfully completed.

> ERROR DETAILS
	Following errors were detected during this operation.
	* [29/12/2016 19:39:13] System.Runtime.InteropServices.COMException
		- The directory name is invalid. (Exception from HRESULT: 0x8007010B)
		- Source: System.Deployment
		- Stack trace:
			at System.Deployment.Application.NativeMethods.CorLaunchApplication(UInt32 hostType, String applicationFullName, Int32 manifestPathsCount, String[] manifestPaths, Int32 activationDataCount, String[] activationData, PROCESS_INFORMATION processInformation)
			at System.Deployment.Application.ComponentStore.ActivateApplication(DefinitionAppId appId, String activationParameter, Boolean useActivationParameter)
			at System.Deployment.Application.SubscriptionStore.ActivateApplication(DefinitionAppId appId, String activationParameter, Boolean useActivationParameter)
			at System.Deployment.Application.ApplicationActivator.Activate(DefinitionAppId appId, AssemblyManifest appManifest, String activationParameter, Boolean useActivationParameter)
			at System.Deployment.Application.ApplicationActivator.PerformDeploymentActivation(Uri activationUri, Boolean isShortcut, String textualSubId, String deploymentProviderUrlFromExtension, BrowserSettings browserSettings, String& errorPageUrl)
			at System.Deployment.Application.ApplicationActivator.ActivateDeploymentWorker(Object state)

> COMPONENT STORE TRANSACTION DETAILS
	* Transaction at [29/12/2016 19:39:13]
		+ System.Deployment.Internal.Isolation.StoreOperationSetDeploymentMetadata
			- Status: Set
			- HRESULT: 0x0
		+ System.Deployment.Internal.Isolation.StoreTransactionOperationType (27)
			- HRESULT: 0x0

**Comment by msarilar** [comment]
You deleted the folders, but did you try to uninstall via the add/remove programs windows' feature?

I haven't released anything since a while so if it suddenly doesn't work, it probably means an issue on your end, like new proxy, new firewall rules, antivirus etc...

Make sure you're able to access [this url](https://raw.githubusercontent.com/msarilar/EDEngineer/master/EDEngineer/releases/EDEngineer.application), then take a look at what could have changed in your computer's configuration, that will probably do the trick

**Comment by RustyGentleman** [comment]
I did not. I'll try that as soon as I'm able to. 

Nothing's changed on my end for a long time, though. And I am able to access that url.

**Comment by RustyGentleman** [comment]
Ahh, that did it. Thank you! It's insane how much this helps.
