### ISSUE TITLE
Feature Request: "Threshold Warning"

### ISSUE THREAD

**Issue by omega9380** [msarilar/EDEngineer#143]
Loving EDEngineer!  Makes the engineer grind sessions a bit more tolerable.  Now, I like to try to keep my materials and data managed by dumping any mat'l or data that is over 20 units.  A nice option in EDEngineer would be a setting that pops a warning when a mat'l or data goes over X units.  Something similar to the popups that you get when a blueprint is ready.  It would say something like "THRESHOLD WARNING: Mechanical Scrap over 20 units, now at 23 units."  Then of course, highlight the over threshold mat'l in the list.  Thanks!!!

**Comment by ArmEagle** [comment]
This would also help to keep (currently) useless materials at a low amount. This feature could be implemented by  letting you simply set an amount per material, or by adding categories/groups.

Either way I'd use a feature like this.

The opposite is also handy. You have implemented the shopping list. But it could be handy to list some items that one would always want to try to obtain (mission limited materials).

**Comment by rosscarlson** [comment]
Absolutely agree - great idea.  Not only would a popup or audible alert be great but some kind of highlighting in the main app would also be great.  For VR players nearly a must as it's too difficult to see popups like that in VR, even if I didn't mind taking off my Rift (and I do) I'd likely not look in time to see it.

Definitely a great idea.

**Comment by Athanasius** [comment]
+1 for this.

**Comment by msarilar** [comment]
did a bunch of refactoring and ended up doing that feature as well

so it's ready but I'm waiting a bit to see if there's people who wants to contribute to the localization (I've pinged them in the commits here https://github.com/msarilar/EDEngineer/commit/7fa7d27fe7a8dfb7abb60dc6697c046342bdfdc8#commitcomment-20749164)

I'll deploy either when everything's translated or in a couple of days max if no localization is contributed

**Comment by CMDR-Ryoohk** [comment]
I'm for this to.

**Comment by msarilar** [comment]
deployed in 1.0.4.7
