### ISSUE TITLE
Story arc developments: Close encounter has 2 new materials

### ISSUE THREAD

**Issue by Charybdis** [msarilar/EDEngineer#144]
This thread has added a new encounter to the game: https://forums.frontier.co.uk/showthread.php/319545

It adds two new engineer materials and an error for both is reported by ED Engineers.

![unknown material](https://cloud.githubusercontent.com/assets/23155785/21732482/9977dd94-d451-11e6-81da-10b2f8486e3c.png)

The two new materials are captured by ED Discovery from the journal logs as:

Encoded, unknownshipsignature, Discovery Number:34
Encoded, unknownshipsignature, 3 items
Encoded, unknownwakedata, Discovery Number:35
Encoded, unknownwakedata, 3 items

This is from the journals:

{ "timestamp":"2017-01-06T18:48:50Z", "event":"MaterialDiscovered", "Category":"Encoded", "Name":"unknownshipsignature", "DiscoveryNumber":34 }
{ "timestamp":"2017-01-06T18:48:50Z", "event":"MaterialCollected", "Category":"Encoded", "Name":"unknownshipsignature", "Count":3 }
{ "timestamp":"2017-01-06T18:49:21Z", "event":"MaterialDiscovered", "Category":"Encoded", "Name":"unknownwakedata", "DiscoveryNumber":35 }
{ "timestamp":"2017-01-06T18:49:21Z", "event":"MaterialCollected", "Category":"Encoded", "Name":"unknownwakedata", "Count":3 }

This is how they are represented in game

![unknown_data](https://cloud.githubusercontent.com/assets/23155785/21732596/238e20ba-d452-11e6-9254-b6b67334f476.jpg)

Thanks for ED Engineers, it has helped me immensely when engineering a new ship from the ground up!

**Comment by msarilar** [comment]
Thanks for the report, I have the update ready in 420b0f8 , I'll just wait a bit for translators to come back to me (otherwise I'll deploy that in a couple hours and their localization in a later update)

**Comment by msarilar** [comment]
well it's published in 1.0.4.1 (restart EDEngineer to get the update 😃)

**Comment by Charybdis** [comment]
Verified in the latest release 1.0.4.1.

Thanks for the quick turnaround!
