### ISSUE TITLE
A few missing tooltips on key interface elements

### ISSUE THREAD

**Issue by ArmEagle** [msarilar/EDEngineer#147]
You're missing tooltips on a few key interface elements. Though after about 15 minutes of use I've figured it all out, it would be nice to add.

- Left panel, third tab (i): - Shows the icons explaining where the resource can be obtained
- Right panel:
    - topright: double checkmark and the one below: check all filters, and uncheck all filters
    - the star and (x) buttons for every blueprint: mark as favorite, mark as ignored.

**Comment by msarilar** [comment]
fixed in 1.0.4.4
