### ISSUE TITLE
Note if a commoddity, material, or data is needed to unlock an Engineer

### ISSUE THREAD

**Issue by omega9380** [msarilar/EDEngineer#150]
For the tooltips that pop on the mat'ls, commodity, or data, could you add a note that says if it is needed to unlock an engineer?  For example, I just got an invite for Ram Tah.  However, he needs 50 Classified Scan Databanks.  Because EDE stated that CSDs are not used in any blueprints, I had already dumped the 23 that I had to make more room.  Oops :P.

I figure it would be as simple as modifying the resources.json file and adding a small note stating if the item is used to unlock an engineer.  Something as simple as "Engineer unlock item" after the list of where to find it.  For challenge purposes, I don't think you should mention WHICH engineer, just that it is needed.  This would save others some headache when they relize they dumped 59 CSDs before they unlocked Ram Tah :)

I would do the edit myself on my computer, but I cannot seem to locate where resources.json lives.  Thanks!!!!

**Comment by msarilar** [comment]
fixed in 1.0.4.4
