### ISSUE TITLE
Feature request: Voice attack plugin like EDDI 

### ISSUE THREAD

**Issue by NicoFlows** [msarilar/EDEngineer#154]
https://github.com/cmdrmcdonald/EliteDangerousDataProvider

EDDI uses the voice attack plugin to expose/push  a bunch of variables into VA so text to speech responses can be built from them 

If this could have something similar so I could say 

"do I need Focus Crystals?" 
If Qnty_FocusCrys > Need_FocusCrys then
     Say "we are all set on those"
If..... 

and so on

**Comment by msarilar** [comment]
Hi,

Check the API : https://github.com/msarilar/EDEngineer/wiki/API
And its reference : https://github.com/msarilar/EDEngineer/wiki/API-Reference

It's possible for anyone to use it and write their own VA plugin like user @Shemuev did in its project : https://github.com/Shemuev/CIVAQUERY (it's in spanish, but you get the idea)

**Comment by NicoFlows** [comment]
Oops Sorry I overlooked that, my bad.  Thanks!

**Comment by Shemuev** [comment]
I hope to start CIVAQUERY english translation soon, i will keep you informed.
