### ISSUE TITLE
Shopping List Additions

### ISSUE THREAD

**Issue by rosscarlson** [msarilar/EDEngineer#158]
For the shopping list feature it would be great if you could hover, click, etc. on a specific item in the shopping list so it can show you which blueprint that item is used for in the shopping list.  Use case:

- I have 10 items in my shopping list
- Those are from 5 difference blueprints
- 2 of my items don't have enough, the other 8 do
- I can hover the items I don't have enough and the blueprints that material is used for would highlight on the right.
- Or I can hover the blueprint on the right and it would highlight the materials needed on the left

That way I could decide to go ahead and engineer what I can do now rather than wait for everything on my list.  I know you could just remove items and use the favorites panel but I don't want to lose my current shopping list if I've spent time creating it.

Not a high priority, not sure how hard, if easy great - if hard put it low on the list...

**Comment by mikelimtw** [comment]
Or alternatively, you can put the materials required for each blueprint grouped together on the left side with the name of the blueprint on the right.

**Comment by msarilar** [comment]
I think the filtering of blueprint via highlighting ingredients somewhat solves this, what do you think?

**Comment by nemesyssoft** [comment]
I had the same feeling than the original poster. I think that filtering via highlighting of ingredients is somewhat a workaround but if I check my shopping list, that means a trip to the ingredients list, then maybe select material or data, and finally scroll to the ingredient in my shopping list. Doable but not very convenient, if I understand what you mean by "filtering via highlighting of ingredients"...

**Comment by msarilar** [comment]
added in 8c06021

will be available next deployment

![image](https://cloud.githubusercontent.com/assets/5569959/25563349/077ed5fc-2d9b-11e7-80e2-81d78f41b0e2.png)
