### ISSUE TITLE
MaterialDiscovered events suppress the corresponding MaterialCollected event

### ISSUE THREAD

**Issue by srjek** [msarilar/EDEngineer#16]
EDEngineer at times can appear to not update when one picks up a material for the first time. As a example, I discovered yttrium, tin, and arsenic in the log at [http://pastebin.com/raw/iiZD206i](http://pastebin.com/raw/iiZD206i).

The root cause seems to Elite not posting a MaterialCollected event when the material is discovered, but EDEngineer could maybe assume MaterialDiscovered means 3 minerals were added until Elite fixes it on their side. I'm not sure what happens when a material is discovered by a mission, where the reward may not always have a count of 3.

**Comment by msarilar** [comment]
thanks for the report & investigation.
I indeed assumed two events would be raised upon discovering an element (discovery and collection)... we can work something out though.

You warn about missions not necessarily rewarding 3 materials but are you sure looted materials on a planet always come in triple?

**Comment by srjek** [comment]
Yes. In the current version, whenever you scoop a material or scan data, you always get 3 instead of 1. This was changed in 2.1.05, before journal logs were added. ("When collecting physical micro resources or retrieving data loot, add 3 to the inventory instead of 1. If your inventory can't fit 3, just add enough to fill the inventory" at [https://forums.frontier.co.uk/showthread.php/276723-2-1-05-update-incoming](https://forums.frontier.co.uk/showthread.php/276723-2-1-05-update-incoming))

**Comment by srjek** [comment]
So, unfortunately, MaterialDiscovered events suppress MaterialCollected events even when one finishes a mission. Since the rewards of a mission can vary, and as far as I know no other events indicate the count of the material received, there's nothing that can be done about this until FDev does something.

I completed 2 missions in the logs at [http://pastebin.com/raw/cgvMuJ7u](http://pastebin.com/raw/cgvMuJ7u), the first is a undiscovered material, the second was an already discovered material.

In other news, I can confirm the latest version is working correctly with scooped/scanned materials.

**Comment by msarilar** [comment]
thanks a lot for investigating this! you might want to report this directly to Frontier :)

**Comment by srjek** [comment]
Already did at [https://forums.frontier.co.uk/showthread.php/305543-MaterialDiscovered-events-have-no-corresponding-MaterialCollected-event](https://forums.frontier.co.uk/showthread.php/305543-MaterialDiscovered-events-have-no-corresponding-MaterialCollected-event)

**Comment by msarilar** [comment]
great news btw : https://forums.frontier.co.uk/showthread.php/275151-Commanders-log-manual-and-data-sample?p=4777624&viewfull=1#post4777624
