### ISSUE TITLE
Change data storage to not be affected by deletion/compression of Journal files

### ISSUE THREAD

**Issue by Athanasius** [msarilar/EDEngineer#160]
As I understand it, from some changelog notes, *every* time EDEngineer starts it reads **all** journal files, and then applies a separate 'manual changes' file to arrive at what should be the current counts of all materials/data.

If someone wants to archive their journal files for some reason then their counts are going to be off, yes ?

If you're going to the trouble of storing a list of manual changes then why not instead store the timestamp of the most recent journal entry acted upon and on startup skip ahead to the journal file and entry that is just after that ?  Then you just store the current amount of all materials (plus this timestamp), not a list of manual changes.

**Comment by msarilar** [comment]
yes I guess that could work ; I could reduce all the game's logs into a single one (e.g. a fold) that would increase/decrease the associated items count and ignore any game's logs older than this "meta" log

the thing is, there are users who play on multiple computers (like at home, and during lunch break at work). every time they end a session, they copy the content of their log folders into the folder of their other computer such that both are synchronized

with the meta log idea, this wouldn't work for them :(

the best thing though would be to be able to uniquely identify logs with Guid but frontier does *not* associate a guid to each log (which is very weird for event sourced software) such that we could have a list of logs "contained" in the meta log which would have to be ignored when loading logs

**Comment by Athanasius** [comment]
How would it not work with copying log files around as well ?  You should be going on the timestamps *in* the files and their names, not the file system timestamps.

1) Store timestamp of last entry you processed.
2) On next load up read that, and the stored current counts.
3) Now look through the journal folder until you find a Journal file name with date after the timestamp, then step back one (in case extra was written after EDEngineer was quit).
4) Read through until you find a newer (or the same, to be sure), timestamp, opening the next file(s) if needs be.

If you want to simplify this then continue to do what you do now, read them all at startup, but just discard any data older than the last seen timestamp.  It'll still cause startup to take longer and longer as times goes on, but losing old journal files won't affect things.

**Comment by Athanasius** [comment]
And note #3 can have a variant of "read the first line and see if its timestamp is after the stored one, if it is, step back one file and ...".

**Comment by msarilar** [comment]
with the upcoming journal changes for 2.3, there will be a cargo state dump at the end of each log file, so I just need to handle that and users will safely be able to zip/clean their logs.

it also means no more manual changes and no initial setup for new users, yay!
