### ISSUE TITLE
G5-G4 Lightweight Bulkheads Missing

### ISSUE THREAD

**Issue by NamtarOberon** [msarilar/EDEngineer#163]
As the title says, I think those are missing from the list and I know that the blueprint exists because my Corvette has G5 Lightweight http://i.imgur.com/hbWFLJB.png

**Comment by msarilar** [comment]
Interesting! If you have more details, don't hesitate to post about it here or even better yet, update the data of the app : https://github.com/msarilar/EDEngineer/blob/master/EDEngineer/Resources/Data/blueprints.json#L5666

**Comment by NamtarOberon** [comment]
@msarilar G4 LW Armour http://i.imgur.com/X7wVJTy.png
G5 LW Armour http://i.imgur.com/xEkNm21.png

**Comment by NamtarOberon** [comment]
Uhm... I provided the Blueprints but if you intend that I should add them to the app then I am sorry to say that I have no idea how.

**Comment by msarilar** [comment]
Hey,

There should be a button to edit this file https://github.com/msarilar/EDEngineer/blob/master/EDEngineer/Resources/Data/blueprints.json on the top right

adding the new blueprints following the current formatting should be fairly straightforward (it's just a text file, there's no code), only this file requires changes

**Comment by msarilar** [comment]
deployed in 1.0.5.2
thanks again!
