### ISSUE TITLE
Selecting a material or data item shows all blueprints it is used in

### ISSUE THREAD

**Issue by Charybdis** [msarilar/EDEngineer#166]
When a material or data item is selected (has a yellow highlight) then show a list of blueprints it is used in. Display the list in the right hand panel, ignoring any set filters (grey them out).

When the item is deselected then the previous view (by filter settings) is restored. The filters are re-enabled.

**Comment by msarilar** [comment]
duplicates #136 from @rosscarlson

I was thinking about using the tooltip or something similar but it would be problematic for common ingredients like nickel (used in 123 blueprints!)

until I find the time and an idea suitable from a UX perspective, please use the ingredient filter (bottom right of the filters)
