### ISSUE TITLE
Collecting Classified Scan Databanks doubled in EDEngineer 

### ISSUE THREAD

**Issue by dyfron** [msarilar/EDEngineer#169]
Getting 3 and EDEngineer gave me 6 (happened 2 times)
![edengineer](https://cloud.githubusercontent.com/assets/25774620/22938676/c7cc4d52-f2dc-11e6-880d-0893c5642cf9.jpg)

**Comment by msarilar** [comment]
thanks for the report! it's fixed in 1.0.4.9, so please restart the app to get the update
