### ISSUE TITLE
Report Missing Blueprints Information here (Ingredients or Engineers)

### ISSUE THREAD

**Issue by msarilar** [msarilar/EDEngineer#17]
Maybe these blueprints don't even exist in the game, but it's worth checking if you have an idea...

## Missing Ingredients:

* ~~G5 [Fragment Cannon] Double Shot~~

## Missing Engineers:

* G5 [Beam Laser] Short Range Blaster
* G5 [Beam Laser] Sturdy Mount
* G5 [Burst Laser] Efficient Weapon
* G5 [Burst Laser] Focused Weapon
* G5 [Burst Laser] Overcharged Weapon
* G5 [Burst Laser] Short Range Blaster
* G5 [Burst Laser] Sturdy Mount
* G5 [Frame Shift Drive Interdictor] Expanded FSD Interdictor Capture Arc
* G5 [Mine Launcher] High Capacity Magazine
* G5 [Mine Launcher] Sturdy Mount
* G5 [Missile Rack] High Capacity Magazine
* G5 [Missile Rack] Sturdy Mount
* G5 [Rail Gun] High Capacity Magazine
* G5 [Rail Gun] Short Range Blaster
* G5 [Rail Gun] Sturdy Mount
* G5 [Torpedo Pylon] Sturdy Mount

**Comment by msarilar** [comment]
#67

**Comment by msarilar** [comment]
#91

**Comment by msarilar** [comment]
fixed in 1.0.4.5

**Comment by Murderp** [comment]
When exporting a materials list to EDE, the Overcharged Powerplant is not imported even thought the materials are listed in the export pop-up window in coriolis.
