### ISSUE TITLE
Overlay function key shortcut not working

### ISSUE THREAD

**Issue by Spec0pAssassin** [msarilar/EDEngineer#172]
My F1-12 keys are on a function layer on my keyboard. 
Overlay shortcut and Shortcut key changer doesn't register my F keys.
Required keypress Ctrl+Fn+0(F10) 
Desired result: Ctrl+F10 
Current result: Ctrl+0 
Function keys are working in other programs.

**Comment by msarilar** [comment]
don't have a laptop at disposition to try the fn key ; but it's weird that it doesn't affect the shortcut input indeed
