### ISSUE TITLE
No longer displaying anything

### ISSUE THREAD

**Issue by orcnet** [msarilar/EDEngineer#174]
Hi I had your app working perfectly then there was a recent update and it no longer displayed anything (no screens or icon in the task bar).  Like an idiot I uninstalled the whole program thinking that a fresh reinstall would work but it hasn't.  Each time I attempt to run the program it generates a crash report (see attached, converted to a txt file to upload here). hope you can help as I really enjoyed using it before it crashed.

Many thanks Andy
[Report.txt](https://github.com/msarilar/EDEngineer/files/785163/Report.txt)

**Comment by msarilar** [comment]
hi, could you try this one http://stackoverflow.com/a/21427009/1054649 ?

if it doesn't work, could you fire up the event viewer (windows+R, "eventvwr") and check the Application Logs (in Windows Logs) for errors ?

**Comment by orcnet** [comment]
now working thanks would not have found that one.
