### ISSUE TITLE
Non-overlay Window's position shifts right on each run

### ISSUE THREAD

**Issue by Athanasius** [msarilar/EDEngineer#177]
It's excellent that you made EDEngineer remember the window position, but every time I run it my, unlocked/normal, window has shifted 4 or so pixels to the right.  Eventually this leads to losing sight of the 'X' to close the window.

If it's relevant this is on a dual monitor setup, Windows 10 64-bit, with desktop extended to the second monitor, which is to the right of the main one.  I place EDE all the way over on the right of that second monitor.

If needs be I can check the settings file to see just how far it's moving each time.  It might even be simply the border width.

**Comment by Athanasius** [comment]
It's shifting right 8 pixels between quit and reload.  Tested by using Move > Ctrl-Arrows to get the window border just visible on the right hand edge, quitting, restarting, and seeing how many pixels I had to move it back to see the border.

After positioning border on right edge and quitting:

            <setting name="WindowWidth" serializeAs="String">
                <value>1152</value>
            </setting>
            <setting name="WindowHeight" serializeAs="String">
                <value>648</value>
            </setting>
            <setting name="WindowTop" serializeAs="String">
                <value>75</value>
            </setting>
            <setting name="WindowLeft" serializeAs="String">
                <value>2463</value>
            </setting

after restart and it moving right, without me manually correcting:

            <setting name="WindowWidth" serializeAs="String">
                <value>1152</value>
            </setting>
            <setting name="WindowHeight" serializeAs="String">
                <value>648</value>
            </setting>
            <setting name="WindowTop" serializeAs="String">
                <value>77</value>
            </setting>
            <setting name="WindowLeft" serializeAs="String">
                <value>2463</value>
            </setting

My primary monitor, on the left, is 1920x1080, and the secondary, to its right and where I place EDE, is 1680x1050.  They *are* offset vertically in the nvidia options due to being physically different heights (in an attempt to have the mouse cursor not change real-world height when mousing between them).

**Comment by Athanasius** [comment]
Having noticed that only 'WindowTop' changed above, I've now placed the window so its top-right corner is right against the top-right of the secondary monitor.

After a quit the settings are:

            <setting name="WindowWidth" serializeAs="String">
                <value>1152</value>
            </setting>
            <setting name="WindowHeight" serializeAs="String">
                <value>648</value>
            </setting>
            <setting name="WindowTop" serializeAs="String">
                <value>2</value>
            </setting>
            <setting name="WindowLeft" serializeAs="String">
                <value>2462</value>
            </setting

After run/quit:

            <setting name="WindowWidth" serializeAs="String">
                <value>1152</value>
            </setting>
            <setting name="WindowHeight" serializeAs="String">
                <value>648</value>
            </setting>
            <setting name="WindowTop" serializeAs="String">
                <value>4</value>
            </setting>
            <setting name="WindowLeft" serializeAs="String">
                <value>2470</value>
            </setting

And it had moved 2 pixels down vertically, and 8 pixels right horizontally.

**Comment by msarilar** [comment]
thanks for the investigation, the numbers you gave me helped find the correct "magic" numbers I had to use in order to set the position correctly !

fix will be included in next deployment
