### ISSUE TITLE
Notification Spam

### ISSUE THREAD

**Issue by Athanasius** [msarilar/EDEngineer#178]
It would be nice if you could implement some coalescing and rate limiting of the notifications from EDE.

Scenarios where I get spammed (one notification rapidly after another):

1) I picked up data/material that now enables more than one blueprint.  I'll get a notification for each. Coalesce into a list or something like "Blueprint X (and 5 others)".

2) I scanned an NPC, or a surface data point, or a USS data beacon, and got multiple pieces of data.  Even before the last of these is accounted for I'm now over the notification threshold and get one notification per extra data type.  This needs rate limiting (possibly implemented as a queue that waits X seconds before seeing if it needs to coalesce and only then sends a single notification).

3) I recently had EDE get out of sync again.  Correcting the accounts for one thing took me over a notification threshold, so I got notifications for each change after that as well, **and I also got notifications when decreasing another item to bring things correctly back under the threshold**.

There may be other instances.

**Comment by Tkael** [comment]
One notification for each blueprint pattern would be sufficient. For example, lightweight grade 5 or efficient grade 5.

**Comment by msarilar** [comment]
1. is deployed in 1.6.0.0

2. and 3. will come later

**Comment by msarilar** [comment]
major notification overhaul in next deploy bb365e494d6dbf5ab044d6860063e9346c19012e
