### ISSUE TITLE
App window can not activate

### ISSUE THREAD

**Issue by MartindForlon** [msarilar/EDEngineer#179]
With latest release I cannot get this app window as active (Win10). It is showing active icon, when I move mouse it show app window (small), but clicking on it does nothing.

**Comment by MartindForlon** [comment]
It opens app window for quick time on start, but then it minimize and I can't open it in window. I can bring app window up as maximized only.

**Comment by MartindForlon** [comment]
Used Lock/unlock and it solved it for me. Now it works also in window like before.

**Comment by msarilar** [comment]
glad it worked out: remember the "reset window position" command in the tasktray icon, usually solves that kind of issue
