### ISSUE TITLE
Overlay

### ISSUE THREAD

**Issue by Alberonn** [msarilar/EDEngineer#18]
Hey,

First I like t say it's a great job you are doing.
I am having some problems with the ovelay. When I am in E:DH and press CTRL+F10 I don't get the overlay in Elite, but i am back at my desktop. And when I press CTRL+F10 again I go back to Elite.
So I don't see the overlay in Elite, like you show in one of the screenshots.

I used the download link in the your desciption.
I am run Win 10 Pro on my PC.

Am I doing something wrong? Or do I have to change some settings somewhere?

I hope you can help.

Regards,

Marco Kroes aka CMDR Alberonn

**Comment by msarilar** [comment]
Are you running the app in borderless mode?

**Comment by Alberonn** [comment]
Yes i am running the game in full screen mode.

**Comment by msarilar** [comment]
Please run the game in borderless then :)
