### ISSUE TITLE
Impossible to tell if I have the latest version

### ISSUE THREAD

**Issue by nemesyssoft** [msarilar/EDEngineer#180]
Not sure if I'm missing something but after looking around in the app and in the EDEngineer tray widget, I cannot tell if the version I have is the latest or not.

**Comment by msarilar** [comment]
EDEngineer updates automatically at each startup (if there's an update available)
The latest update is 1.0.5.3 (you can see the releases here https://github.com/msarilar/EDEngineer/releases), and it should show the current version in the context menu when you right click the icon of the app in the tasktray.
