### ISSUE TITLE
Install not work

### ISSUE THREAD

**Issue by Dolphin222** [msarilar/EDEngineer#182]
Hello,  when i start the EDEngineer Setup.exe then I got this Information:

An error occurred trying to download 'https://raw.githubusercontent.com/msarilar/EDEngineer/master/EDEngineer/releases/EDEngineer.application'.

This was into the log file:
------
The following properties have been set:
Property: [AdminUser] = true {boolean}
Property: [InstallMode] = HomeSite {string}
Property: [NTProductType] = 1 {int}
Property: [ProcessorArchitecture] = AMD64 {string}
Property: [VersionNT] = 10.0.0 {version}
Running checks for package 'Microsoft .NET Framework 4.6 (x86 and x64)', phase BuildList
Reading value 'Release' of registry key 'HKLM\Software\Microsoft\NET Framework Setup\NDP\v4\Full'
Read integer value 394802
Setting value '394802 {int}' for property 'DotNet46Full_Release'
Reading value 'v4' of registry key 'HKLM\SOFTWARE\Microsoft\NET Framework Setup\OS Integration'
Read integer value 1
Setting value '1 {int}' for property 'DotNet46Full_OSIntegrated'
The following properties have been set for package 'Microsoft .NET Framework 4.6 (x86 and x64)':
Property: [DotNet46Full_OSIntegrated] = 1 {int}
Property: [DotNet46Full_Release] = 394802 {int}
Running checks for command 'DotNetFX46\NDP46-KB3045557-x86-x64-AllOS-ENU.exe'
Result of running operator 'ValueEqualTo' on property 'InstallMode' and value 'HomeSite': true
Result of checks for command 'DotNetFX46\NDP46-KB3045557-x86-x64-AllOS-ENU.exe' is 'Bypass'
Running checks for command 'DotNetFX46\NDP46-KB3045557-x86-x64-AllOS-ENU.exe'
Result of running operator 'ValueEqualTo' on property 'InstallMode' and value 'HomeSite': true
Result of checks for command 'DotNetFX46\NDP46-KB3045557-x86-x64-AllOS-ENU.exe' is 'Bypass'
Running checks for command 'DotNetFX46\NDP46-KB3045560-Web.exe'
Result of running operator 'ValueNotEqualTo' on property 'InstallMode' and value 'HomeSite': false
Result of running operator 'ValueGreaterThanEqualTo' on property 'DotNet46Full_Release' and value '393297': true
Result of checks for command 'DotNetFX46\NDP46-KB3045560-Web.exe' is 'Bypass'
Running checks for command 'DotNetFX46\NDP46-KB3045560-Web.exe'
Result of running operator 'ValueNotEqualTo' on property 'InstallMode' and value 'HomeSite': false
Result of running operator 'ValueGreaterThanEqualTo' on property 'DotNet46Full_Release' and value '393297': true
Result of checks for command 'DotNetFX46\NDP46-KB3045560-Web.exe' is 'Bypass'
'Microsoft .NET Framework 4.6 (x86 and x64)' RunCheck result: No Install Needed
Launching Application.
URLDownloadToCacheFile failed with HRESULT '-2146697208'
Error: An error occurred trying to download 'https://raw.githubusercontent.com/msarilar/EDEngineer/master/EDEngineer/releases/EDEngineer.application'.

------

I used Windows10 and I have stop the Virus scanner for this download ( Kaspersky Internet Security).

What must I do? It is possible to get a kompleted Windows installer file (*.msi) ?

Many thanks .

**Comment by msarilar** [comment]
hi,

1) can your browser open https://raw.githubusercontent.com/msarilar/EDEngineer/master/EDEngineer/releases/EDEngineer.application ?
2) did you check the bottom of this page in the wiki https://github.com/msarilar/EDEngineer/wiki/Troubleshooting-Issues ,

**Comment by Dolphin222** [comment]
Hi, yes i can browse the file.

-----
<?xml version="1.0" encoding="utf-8"?>
<asmv1:assembly xsi:schemaLocation="urn:schemas-microsoft-com:asm.v1 assembly.adaptive.xsd" manifestVersion="1.0" xmlns:asmv1="urn:schemas-microsoft-com:asm.v1" xmlns="urn:schemas-microsoft-com:asm.v2" xmlns:asmv2="urn:schemas-microsoft-com:asm.v2" xmlns:xrml="urn:mpeg:mpeg21:2003:01-REL-R-NS" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:asmv3="urn:schemas-microsoft-com:asm.v3" xmlns:dsig="http://www.w3.org/2000/09/xmldsig#" xmlns:co.v1="urn:schemas-microsoft-com:clickonce.v1" xmlns:co.v2="urn:schemas-microsoft-com:clickonce.v2">
  <assemblyIdentity name="EDEngineer.application" version="1.0.5.5" publicKeyToken="c7c2cd04d2cdd815" language="neutral" processorArchitecture="msil" xmlns="urn:schemas-microsoft-com:asm.v1" />
  <description asmv2:publisher="EDEngineer" asmv2:product="EDEngineer" xmlns="urn:schemas-microsoft-com:asm.v1" />
  <deployment install="true" mapFileExtensions="true">
    <subscription>
      <update>
        <beforeApplicationStartup />
      </update>
    </subscription>
    <deploymentProvider codebase="https://raw.githubusercontent.com/msarilar/EDEngineer/master/EDEngineer/releases/EDEngineer.application" />
  </deployment>
  <compatibleFrameworks xmlns="urn:schemas-microsoft-com:clickonce.v2">
    <framework targetVersion="4.6.1" profile="Full" supportedRuntime="4.0.30319" />
  </compatibleFrameworks>
  <dependency>
    <dependentAssembly dependencyType="install" codebase="Application Files\EDEngineer_1_0_5_5\EDEngineer.exe.manifest" size="16140">
      <assemblyIdentity name="EDEngineer.exe" version="1.0.5.5" publicKeyToken="c7c2cd04d2cdd815" language="neutral" processorArchitecture="msil" type="win32" />
      <hash>
        <dsig:Transforms>
          <dsig:Transform Algorithm="urn:schemas-microsoft-com:HashTransforms.Identity" />
        </dsig:Transforms>
        <dsig:DigestMethod Algorithm="http://www.w3.org/2000/09/xmldsig#sha256" />
        <dsig:DigestValue>wGaHH0f2+Bk9yFGepKUlnTU3Rc6miGkhuMqXtWIIXAY=</dsig:DigestValue>
      </hash>
    </dependentAssembly>
  </dependency>
<publisherIdentity name="CN=GAMBIT6\Max" issuerKeyHash="11f40001e3715b07597e0eddab9728f9e30cc302" /><Signature Id="StrongNameSignature" xmlns="http://www.w3.org/2000/09/xmldsig#"><SignedInfo><CanonicalizationMethod Algorithm="http://www.w3.org/2001/10/xml-exc-c14n#" /><SignatureMethod Algorithm="http://www.w3.org/2000/09/xmldsig#rsa-sha256" /><Reference URI=""><Transforms><Transform Algorithm="http://www.w3.org/2000/09/xmldsig#enveloped-signature" /><Transform Algorithm="http://www.w3.org/2001/10/xml-exc-c14n#" /></Transforms><DigestMethod Algorithm="http://www.w3.org/2000/09/xmldsig#sha256" /><DigestValue>mHi5YqBgSxlNydhOsGB78cMVgyjG1H3PlBH3nGHjJFw=</DigestValue></Reference></SignedInfo><SignatureValue>rfgyIAjyVsUGUq2y5/rZGQAcINT2i0HWSZkLZ7meylycspT9KEYlxlr8YQ3k+2RtpMhFM7gVssLTco9G2+9myjqxOaabCnK1DYoIhXoqFc5nQeNvi5YkBOiCwfPogCxms4+3jdKI+UXeoTtra4I9ahTN36tO9Iu5Aw2Rm2fconA=</SignatureValue><KeyInfo Id="StrongNameKeyInfo"><KeyValue><RSAKeyValue><Modulus>s3Rgw7x2D3+SLtMKutluM5M8B4WEs+Ug20EfdfHXvLbLVmZQc6zcjTSNAVuXx+DFhTw7Xfvs5y0MXW10LdLfiKq6aazW3Jt9gKcxqv/3nADJB/f2RuyVbpmLpwbG5ZTjAKRvo+VM6u+VI5UIM66zasrgjqympr2YoaV4wjeSXk0=</Modulus><Exponent>AQAB</Exponent></RSAKeyValue></KeyValue><msrel:RelData xmlns:msrel="http://schemas.microsoft.com/windows/rel/2005/reldata"><r:license xmlns:r="urn:mpeg:mpeg21:2003:01-REL-R-NS" xmlns:as="http://schemas.microsoft.com/windows/pki/2005/Authenticode"><r:grant><as:ManifestInformation Hash="5c24e3619cf71194cf7dd4c6288315c3f17b60b04ed8c94d194b60a062b97898" Description="" Url=""><as:assemblyIdentity name="EDEngineer.application" version="1.0.5.5" publicKeyToken="c7c2cd04d2cdd815" language="neutral" processorArchitecture="msil" xmlns="urn:schemas-microsoft-com:asm.v1" /></as:ManifestInformation><as:SignedBy /><as:AuthenticodePublisher><as:X509SubjectName>CN=GAMBIT6\Max</as:X509SubjectName></as:AuthenticodePublisher></r:grant><r:issuer><Signature Id="AuthenticodeSignature" xmlns="http://www.w3.org/2000/09/xmldsig#"><SignedInfo><CanonicalizationMethod Algorithm="http://www.w3.org/2001/10/xml-exc-c14n#" /><SignatureMethod Algorithm="http://www.w3.org/2000/09/xmldsig#rsa-sha256" /><Reference URI=""><Transforms><Transform Algorithm="http://www.w3.org/2000/09/xmldsig#enveloped-signature" /><Transform Algorithm="http://www.w3.org/2001/10/xml-exc-c14n#" /></Transforms><DigestMethod Algorithm="http://www.w3.org/2000/09/xmldsig#sha256" /><DigestValue>qqy7k6hlUwtIkjNutaTTCYl7DVWUKJTSQOhpiCfJNlk=</DigestValue></Reference></SignedInfo><SignatureValue>TxqvXmOn5YGr+9z9ACOTPgPrcBpQSQ3TFNcAaN0T22843syTMuF8kkQ1MDJ7IaAhBgGajoi9tCvYuK8iWQNa+2GEs2sJzW35n/zLtOFLafISR6hP24MSuR5WG0xR6oFPAHIUBn1YC1A0pA8/Y26B0hpwu9W6BWpxE1whHuRWACo=</SignatureValue><KeyInfo><KeyValue><RSAKeyValue><Modulus>s3Rgw7x2D3+SLtMKutluM5M8B4WEs+Ug20EfdfHXvLbLVmZQc6zcjTSNAVuXx+DFhTw7Xfvs5y0MXW10LdLfiKq6aazW3Jt9gKcxqv/3nADJB/f2RuyVbpmLpwbG5ZTjAKRvo+VM6u+VI5UIM66zasrgjqympr2YoaV4wjeSXk0=</Modulus><Exponent>AQAB</Exponent></RSAKeyValue></KeyValue><X509Data><X509Certificate>MIIBxTCCAS6gAwIBAgIQfKLD0d6RorlAQCjrdfkDHTANBgkqhkiG9w0BAQsFADAhMR8wHQYDVQQDHhYARwBBAE0AQgBJAFQANgBcAE0AYQB4MB4XDTE2MTEwMTE1MDgxOVoXDTE3MTEwMTIxMDgxOVowITEfMB0GA1UEAx4WAEcAQQBNAEIASQBUADYAXABNAGEAeDCBnzANBgkqhkiG9w0BAQEFAAOBjQAwgYkCgYEAs3Rgw7x2D3+SLtMKutluM5M8B4WEs+Ug20EfdfHXvLbLVmZQc6zcjTSNAVuXx+DFhTw7Xfvs5y0MXW10LdLfiKq6aazW3Jt9gKcxqv/3nADJB/f2RuyVbpmLpwbG5ZTjAKRvo+VM6u+VI5UIM66zasrgjqympr2YoaV4wjeSXk0CAwEAATANBgkqhkiG9w0BAQsFAAOBgQA0l6SGR8ROw2A3Wxp1znVUThSCab6lWc0o/x6VJXn8PmxpvzLDNKqvz4PqP9GDv9DUiPSamsNCRA5yMmsIqD9q8bbtTRN6wYAtBwcP7tHi4OvYggM9UW3cBtJKBV9r+UvywN4847zsC3TPF0FgjEb3xqdCJEqYe3OXzdi0FLScSA==</X509Certificate></X509Data></KeyInfo></Signature></r:issuer></r:license></msrel:RelData></KeyInfo></Signature></asmv1:assembly>
-----
2: Yes I have done this and deleted the Folder "7HLD2DQW.RCK"
But the results is the same.
-------
An error occurred trying to download 'https://raw.githubusercontent.com/msarilar/EDEngineer/master/EDEngineer/releases/EDEngineer.application'.
------------

**Comment by Dolphin222** [comment]
Sorry, the Close was a mistake !

**Comment by Dolphin222** [comment]
Do you have a compled Windows installer File (*.msi) ? Many Thanks

**Comment by Obermokel** [comment]
Might be this is related to IE settings:
http://feedback.veodin.com/knowledgebase/articles/52576-installation-fails-with-error-message-urldownload
A friend of me has resolved the problem by resetting his IE settings: Internet options -> advanced -> reset (my Windows is German, Internetoptionen -> Erweitert -> Zurücksetzen)

**Comment by Dolphin222** [comment]
This was helpful. Many Thanks!!!!
"A friend of me has resolved the problem by resetting his IE settings: Internet options -> advanced -> reset (my Windows is German, Internetoptionen -> Erweitert -> Zurücksetzen)"

**Comment by Dolphin222** [comment]
Problem solved

**Comment by msarilar** [comment]
great! I've updated the wiki with that information in case it happens to someone else
