### ISSUE TITLE
Overlay problem

### ISSUE THREAD

**Issue by Khalarin** [msarilar/EDEngineer#185]
Hi I'm having an issue getting the overlay working in game, works perfectly fine on desktop and with the game open it's tracking my shizzle but in game it just will not show up, at best it switches to the desktop or just does the show/hide action in the background and if i alt+tab back to the desktop I can see it working fine. 

Have tried resetting and changing the hot key and the cmd line option & reinstalling but no change.

Any ideas?
Thanks
-Khal 
p/s - this is a kick ass app, i hope i can get it working.

**Comment by msarilar** [comment]
need to play in windowed mode, not full screen (video option in the game)

**Comment by Khalarin** [comment]
Ahh that'll be the problem then ... and yep that seems to work ok now d'oh! 
If i may ask, will it ever work in fullscreen mode somewhere down the road? 
It's not going to stop me using the app ofc it's really good work =D
Thank you for the lightning fast response too!

**Comment by msarilar** [comment]
nah working full screen won't ever work as the application is standalone and not ran by the game itself

**Comment by Khalarin** [comment]
No worries, thank you again Max =)
