### ISSUE TITLE
[Request] Silent Launch Toggle

### ISSUE THREAD

**Issue by Azaun** [msarilar/EDEngineer#187]
Hello,

I greatly appreciate the program you have written and the time you have invested into it to improve our experience of Elite. Would it be possible to add a silent launch or launch minimized feature so that the material list does not display every time I start my computer? I tried adapting the application shortcut key but something about the executable does not allow the normal settings to force the program to launch as minimized and this setting is not always very successful either. Something within the program itself would be most helpful.

Thank you for your consideration.

**Comment by msarilar** [comment]
just to confirm; you have the window in locked position and you'd like it to start hidden when you boot the application?

**Comment by Azaun** [comment]
Correct. That would be perfect.

**Comment by Tkael** [comment]
+1. The program should have an option to open minimized, and to not give an error message if it is already running. That'd be perfect for launching from VoiceAttack for me.

**Comment by msarilar** [comment]
added in 0a5dde6  

will be available next update 

![image](https://cloud.githubusercontent.com/assets/5569959/25063083/ad288c72-21da-11e7-84fb-2494fc34892f.png)

**Comment by Azaun** [comment]
Thank you!
