### ISSUE TITLE
Show only highlighted

### ISSUE THREAD

**Issue by BeckyYork** [msarilar/EDEngineer#189]
Can we have an option of "only show highlighted" in the Materials/data section.
And when this option is selection it would show all the highlighted data and materials together.

This will be useful when collecting materials so you have a very small list of the things that you're collecting; the shopping list is useful but I find that using highlighted things is simpler to use.

**Comment by msarilar** [comment]
now that highlighted ingredients are used to filter blueprints, I was wondering if it was still interesting to have such filter

what do you think?

**Comment by lemny** [comment]
Are you kidding? This is amazing!
With only 500/1000 space youhave to ditch something on a daily basis.
It's incredible usefull to know quickly for what some stuff is needed to decide.
I love this function.

**Comment by msarilar** [comment]
I don't think we're talking about the same thing @lemny 
From what I understand, @BeckyYork asked for a filter at the ingredient level (like the "show only favorite" or "show entries with no stock") such that it would only show highlighted ingredients.

It used to be a very small QoL thing that didn't have any impact beside the highlight itself, but now it's used as a filter

**Comment by lemny** [comment]
You are right... I was too excited about that new feature ;)
