### ISSUE TITLE
Voice Attack Integration

### ISSUE THREAD

**Issue by mikelimtw** [msarilar/EDEngineer#190]
Would it be possible to expose some variables or controls to allow voice attack interaction? For example allowing you to use voice to manipulate the filters, or perhaps using voice attack to query about blueprints or your list of materials without having to open up the EDEngineer overlay.

Exposing variables to VA by turning EDEngineer into a plugin would allow us to create our own extended functionality without having to ask for it to be implemented by the dev.

**Comment by msarilar** [comment]
You can use the API for this (check out the wiki), somebody did a plugin in spanish : https://github.com/Shemuev/CIVAQUERY
