### ISSUE TITLE
Shopping List/Favourites combined

### ISSUE THREAD

**Issue by Doomy66** [msarilar/EDEngineer#192]
There may be a good reason to have Favorites and Shopping List requirements as separate things, but AFAIAC, if its on my Shopping List, its a Favourite. Trying to keep the 2 in sync is too much admin for my tiny brain. Adding or removing from my Shopping List should be enough to toggle the Favorite status of a Material.

**Comment by msarilar** [comment]
the two aren't really the same:

I meant the favorites to be things that you craft often (like specific synthesis) or things that you want to always track. the idea is to have the little star close to the material name as well as easily find them back on a regular basis

The shopping list was designed for when you prepare a run between multiple engineers in one go; for intance you want to fully engineer your vulture then you want to gather everything times 5 (for rolling stats).

Let's say I want to plan for FSD range times 5 amongst other blueprints ; but I only want that once, I won't care afterwards. It will be set in the shopping list but not as a favorite.
