### ISSUE TITLE
Shopping List Nett Value on main Commodity Form

### ISSUE THREAD

**Issue by Doomy66** [msarilar/EDEngineer#193]
Could we please have the Shopping List Nett Total for each Material on the Main Materials form (-4 if you need 4 more to complete your list, or +20 if you have 20 more than required by your shopping list) ? 

Shopping list list is OK, but it doesn't help a great deal when you are trying to clear your excess, or identify what sort of gathering activity would be best.

**Comment by msarilar** [comment]
duplicates #193
