### ISSUE TITLE
Shopping List Full/No Scroll Bar

### ISSUE THREAD

**Issue by Doomy66** [msarilar/EDEngineer#195]
Seems like a bug, I have run out of Shopping List Slots or the Scroll Bar is missing. 
The far right hand side is full even when Maximized (yes I have an EXTENSIVE shopping list), and when I add the last couple of things to the list (Synthesis items), they do not appear and there is no scroll bar. They MAY be on the list, but I have so many items, its hard to tell if they have added to the requirements or not.

**Comment by msarilar** [comment]
fixed in 6f5e62e
