### ISSUE TITLE
USS / High Grade Emissions Details

### ISSUE THREAD

**Issue by Doomy66** [msarilar/EDEngineer#196]
You could include the details for the various High Grade Emissions locations as detailed:
https://forums.frontier.co.uk/showthread.php/326047-Unidentified-Signal-Sources-(USS)-A-Complete-Guide

**Comment by Tkael** [comment]
+1

**Comment by Psieonic** [comment]
+2

High grade emission, Imperial 
High grade emission, Federation
etc

**Comment by msarilar** [comment]
You guys should checkout [the json data](https://github.com/msarilar/EDEngineer/blob/master/EDEngineer/Resources/Data/entryData.json) I generated and curated, especially the `OriginDetails` which is a [JSON array](https://www.w3schools.com/js/js_json_arrays.asp).

Feel free to submit a pull request updating that file, changing the necessary tokens:

> `"Signal source (High grade emissions)"`
`"Signal source (High grade emissions, Imperial)"`

**Comment by Psieonic** [comment]
I'll take a look at it later tonight then and see what I can do. :)

**Comment by Psieonic** [comment]
I **think** I made a pull request for this last night, but not sure if I put it through correctly.

**Comment by msarilar** [comment]
https://github.com/msarilar/EDEngineer/pull/217

4029a3b
