### ISSUE TITLE
2.3 Plans

### ISSUE THREAD

**Issue by Doomy66** [msarilar/EDEngineer#197]
They are not going to change now, so might be nice to have them ASAP so we can prepare

**Comment by msarilar** [comment]
hum not sure I understand that one ; what would you like to have asap exactly?

**Comment by Doomy66** [comment]
The new 2.3 Engineer Recipes

**Comment by msarilar** [comment]
ah right, have they been published already?
pull requests on the [blueprints json](https://github.com/msarilar/EDEngineer/blob/master/EDEngineer/Resources/Data/blueprints.json) are more than welcome, anybody can edit the file and submit the change to me which I will review and validate (the file should be pretty straightfoward to read and understand, I generated it with that in mind)

**Comment by Thurion** [comment]
I added the recipes for sensors and the detailed surface scanner. I used https://coriolis.edcd.io to get the information about the engineers and required materials. But I encountered a two small problems:

- I needed to add `Abnormal Compact Emissions Data` to [entryData.json](https://github.com/msarilar/EDEngineer/blob/master/EDEngineer/Resources/Data/entryData.json) but it doesn't show up in the program itself.
- I don't have any of that material myself so I can't confirm if the entry in the E:D log is really `abnormalcompactemissionsdata`

Are there more new blueprints than for those 2 modules?

**Comment by msarilar** [comment]
that ingredient already exists https://github.com/msarilar/EDEngineer/blob/master/EDEngineer/Resources/Data/entryData.json#L10

regarding the new blueprints, @AndreyATGB submitted a big pull request with most of the new stuff ; there's just some minor corrections to do and I'll deploy that :)

**Comment by Thurion** [comment]
I missed it because Coriolis spelled it `Abnormal Compact Emissions Data` instead of `Abnormal Compact Emission Data` and I copied their data. And I also was in the materials tab instead of the data tab... That's why it didn't show in the list.

**Comment by msarilar** [comment]
deployed in 1.6.0.0, thanks a lot to @AndreyATGB !
