### ISSUE TITLE
Synthesis not taken into account

### ISSUE THREAD

**Issue by VortiK** [msarilar/EDEngineer#20]
Hello, 

Thanks for this tools it is awesomly great. I started using it tonight and found out it seems to not take into account materials consumed by Synthesis. At least the SRV repair, refuel and rearm.
I had to manually count down the materials used.

The journal event logs should be thoses : 

```
{ "timestamp":"2016-11-06T20:57:56Z", "event":"Synthesis", "Name":"Ammo Basic", "Materials":{ "sulphur":2, "phosphorus":1 } }
{ "timestamp":"2016-11-06T20:58:01Z", "event":"Synthesis", "Name":"Repair Basic", "Materials":{ "iron":2, "nickel":1 } }
{ "timestamp":"2016-11-06T20:58:05Z", "event":"Synthesis", "Name":"Fuel Basic", "Materials":{ "sulphur":1, "phosphorus":1 } }
```

Not a big issue but just tought you might wanna know.

Regards

**Comment by VortiK** [comment]
Just saw it seems to be fixed in a newer version, I ran the setup again and it looks to have updated. I'll try again and tell you if the bug is still there !

**Comment by msarilar** [comment]
yeah it should be taken into account, let me know if it's still not the case
