### ISSUE TITLE
EdEngineer does not load

### ISSUE THREAD

**Issue by ComradeNapoleon** [msarilar/EDEngineer#200]
Since release of 2.3 I have not managed to make EdEngineer run. Not even the new update.
Cheers

**Comment by msarilar** [comment]
could you upload a zip of your log folder ? I'll take a look tonight 

(rename the .zip to .jpg if github doesn't want an archive)

**Comment by ComradeNapoleon** [comment]
Can do that, but which one, and where to find, sorry this is not my force :)
Cheers

**Comment by msarilar** [comment]
copy that verbatim in your explorer address bar `C:\Users\%USERNAME%\Saved Games\Frontier Developments`

**Comment by ComradeNapoleon** [comment]
[Elite Dangerous.zip](https://github.com/msarilar/EDEngineer/files/920844/Elite.Dangerous.zip)
Here you go

**Comment by msarilar** [comment]
I can load them without problem, I think your best bet is to reinstall

not sure what could go wrong here

**Comment by ComradeNapoleon** [comment]
Will do. 
Cheers

**Comment by ComradeNapoleon** [comment]
Sorted out :)
Thank you and cheers.
Did I tell you it is an excellent program.
