### ISSUE TITLE
Display the version number

### ISSUE THREAD

**Issue by CMDR-Cometborne** [msarilar/EDEngineer#204]
At the moment, there looks to be no place in the GUI where the version number is displayed. This makes it harder than necessary to find out which version you are running, especially for bug reports.  Please add the version number somewhere where it is immediately obvious, for example in the window title bar.

**Comment by msarilar** [comment]
yeah there is, it's in the context menu when you right click the icon in the task bar
if you click on it you'll see the release notes of previous versions
