### ISSUE TITLE
Surface scanner: List of engineers is wrong

### ISSUE THREAD

**Issue by Thurion** [msarilar/EDEngineer#208]
The engineer `Tiana Fortune` can modify surface scanners only up to grade 3. [Proof](http://prntscr.com/ewuafw)

According to [Engineering Guide to Exploration](https://forums.frontier.co.uk/showthread.php/340621-Engineering-Guide-to-Exploration) the engineers `Bill Turner` and `Lori Jameson` can do the grade 5 modifications which I can't confirm because I don't have access to them yet. [Coriolis](https://coriolis.edcd.io) also lists `Lei Chung` and `Juri Ishmaak` which I can't confirm either.

**Comment by msarilar** [comment]
thanks for the information ! I see you already made some changes in your fork, could you open a pull request ?

**Comment by msarilar** [comment]
published in 1.0.6.6

**Comment by gbiobob** [comment]
Hi,
here the official answer about the engineers issues in the original 2.3 changelog
https://forums.frontier.co.uk/showthread.php/341916-2-3-The-Commanders-Changelog?p=5433331#post5433331

Not sure you need to reopen the ticket if everything is already ok with previous users feedback

**Comment by Thurion** [comment]
I edited the file and created a pull request: https://github.com/msarilar/EDEngineer/pull/225

Thanks for linking the forum post.
