### ISSUE TITLE
Suggestion for manual material limit

### ISSUE THREAD

**Issue by MoofinSeeker** [msarilar/EDEngineer#209]
Since the update I am unable to use the highlight feature to track important materials, so I would like to request a feature to add an indicator of how many materials I want to keep before discarding extras.

For example, say I only want to keep 5 Open symmetric keys, I would input "5" in my limiter and it would say something like:

Open Symmetric Keys: 20/5

That way I know to get rid of 15 of those without having to manually check what that material is used for or affecting my current shopping list to check things that I'm not actively hunting for.

I hope this makes sense. I'm not very used to using GitHub so apologies if I've messed up.

**Comment by msarilar** [comment]
you can use the Threshold feature for that :

![image](https://cloud.githubusercontent.com/assets/5569959/25069806/6fe488ae-228c-11e7-9038-50f9b5ea5084.png)

**Comment by MoofinSeeker** [comment]
Hi, thanks for the reply. I cannot seem to find that option anywhere on your app. Please could you direct me? Thanks.

**Comment by msarilar** [comment]
Sure, it's in the context menu of the task tray icon
Right click on it to show the options and other advanced stuff

**Comment by msarilar** [comment]
![image](https://cloud.githubusercontent.com/assets/5569959/25070253/ee955252-2299-11e7-9fec-5ced32b3396d.png)

**Comment by MoofinSeeker** [comment]
Thank you! I forgot that options could be found in the task tray too! :)
