### ISSUE TITLE
Unlocking an engineer doesn't subtract materials/data

### ISSUE THREAD

**Issue by Athanasius** [msarilar/EDEngineer#21]
Because, for instance unlocking Ram Tah with 50x Classified Scan Databanks, doesn't emit a journal entry about using them EDEngineer gets out of sync.

There is, however this:

{ "timestamp":"2016-11-06T09:38:56Z", "event":"EngineerProgress", "Engineer":"Ram Tah", "Progress":"Unlocked", "Rank":1 }

But you can do that in bits and pieces, so you can't just assume that this event means 'subtract 50 CSD'.  Basically I'd report it as a bug in the journal code that it's not emitting an event for this.  Perhaps the EngineerProgress event, as above, could include a "cost" if applicable.

**Comment by msarilar** [comment]
interesting, thanks for investigating

we could maybe store the list of all engineers and their Unlock requirements and map that to such events... I'll think about it

**Comment by msarilar** [comment]
I scratched this https://github.com/msarilar/EDEngineer/commit/f69c65395d789892e0df3ce28d087760ff167515

The only issue would be the name of the engineer not being equal to the key I've set in the static dictionary of EngineerProgressOperation. Thankfully, none of the engineers requesting stuff used in blueprints have ambiguous name (like Tod McQuinn | Tod "The Blaster" McQuin | Tod 'The Blaster' McQuin | etc...) so I think we're alright.

**Comment by msarilar** [comment]
published in 1.0.0.15

**Comment by msarilar** [comment]
So actually this is a deeper issue...
The event EngineerProgress triggers only when you actually unlocks the engineer ; meaning if you gives the guy some materials in multiple steps, EDEngineer won't detect it. Only when the final material is given will the application remove the cargo.

Apparently, Elite Dangerous doesn't output anything when you give stuff to engineer. So unfortunately I cannot solve that unless Frontier fixes the issue in their logs :/

**Comment by Athanasius** [comment]
That is what I was trying to tell you above.

I think the best thing to do in EDEngineer right now is watch for the unlock events and warn the user that the count may well now be off.

**Comment by msarilar** [comment]
https://forums.frontier.co.uk/showthread.php/313488-Commander-s-Logs-Giving-Stuff-to-unlock-Engineers-doesn-t-generate-logs?p=4869396#post4869396

**Comment by sqzbox** [comment]
Here's the log file you asked for. But I suspect that the issue is FD's to solve.
[Elite Dangerous.zip](https://github.com/msarilar/EDEngineer/files/692632/Elite.Dangerous.zip)

**Comment by msarilar** [comment]
@sqzbox yes indeed, they did not fix it yet !
