### ISSUE TITLE
Search bar

### ISSUE THREAD

**Issue by Yannick183** [msarilar/EDEngineer#212]
Wouldn't it be practical to include a global search bar for materials/data/plans ? For example just above the Material and Data tabs, 

- Typing "Thrusters" in it would reveal all the thrusters plans in the right panel, and why not the thrusters related materials on le left panel.

- Typing "Phosphorus" in it would reveal the material in the left panel, and why not all the related plans on the right side

- It could also support auto completion, so that when you start typing "Shield", you can get a more precise search with the suggestions (Shield Boosters, Worn Shield Emitters, etc...)

What do you think ?

**Comment by msarilar** [comment]
yeah I like the blueprint search idea, but not the material search (I'm always reticent to add filters on the left panel, plus there's not that much data in there and you can already sort by name)

auto-completion might be too annoying to implement because there are many things that should be searchable : name, type, shortened type (multi-cannon -> mc) etc...

**Comment by msarilar** [comment]
published in 1.0.6.7

**Comment by Psieonic** [comment]
Is there any reason you couldn't add the materials search to the right hand label though? 

I know there's a filter already, and that you can highlight on the left to filter, but typing a material is a hell of a lot faster for most of us than scrolling a list and clicking around.

The number one most used function for me at least, is asking EDE "What is this material used for?"

**Comment by Psieonic** [comment]
Label = panel*

**Comment by msarilar** [comment]
the search would be slower as there would be much more data to index, and on top of that most ingredients have a space in their name. as I decided to use the space character to delimit the different tokens to include in the search (i.e. each token is checked against each characteristic of each blueprint, i.e. the name, the engineers, the type and the grade)

**Comment by Psieonic** [comment]
For enough.  Rather than a search bar then, what about just some form of quick select for the materials pane?  Type the first three letters to quick skip down the list to the first match?  Then people can click/enter key to use the normal highlight filter.

**Comment by Psieonic** [comment]
Fair enough.** Yay autocorrect and no post edits. XD
