### ISSUE TITLE
Enhancement: Notification Text-to-Speech

### ISSUE THREAD

**Issue by rkodey** [msarilar/EDEngineer#214]
For those of us running in VR, it'd be awesome to have an option to send the Notification text to Microsoft's Text-to-Speech engine instead of the default Notification system.

The TTS engine is quite simple to invoke:

Set oTTS = CreateObject("SAPI.SpVoice")
oTTS.Speak("Just send the string value here, and Windows starts talkin!")

**Comment by msarilar** [comment]
major notification overhaul in next deploy bb365e494d6dbf5ab044d6860063e9346c19012e
