### ISSUE TITLE
share data : add shopping list and thresholds to the API

### ISSUE THREAD

**Issue by vetall812** [msarilar/EDEngineer#215]
If I remember correctly EDEngi can run server in background. Is it possible to get current material list with thresholds in JSON by http request?

PS. And shoplist ;)

two things I'm trying to do:
1) play with digits when I'm not home, may be share my thoughts via links.
2) get EDEngi info in VR. Here is workaround that can show you VR browser.

**Comment by vetall812** [comment]
OR! may we use this?
https://mashe.hawksey.info/2014/07/google-sheets-as-a-database-insert-with-apps-script-using-postget-methods-with-ajax-example/

**Comment by msarilar** [comment]
shopping list and thresholds aren't currently exported by the API

the API can currently be used to retrieve stocks and referential data (ingredients and blueprints)

**Comment by msarilar** [comment]
next deploy will have the thresholds in the cargo dump, and a new route "shopping-list"

60cad9060c0f476f6bc338866f6b5b072189b1f6
