### ISSUE TITLE
add engineer unlock materials as separate 'blueprints/synthesis' items

### ISSUE THREAD

**Issue by vetall812** [msarilar/EDEngineer#216]
for example 50 "Aberrant Shield Pattern Analysis" needed for The Sarge. So lets add new 'unlock' type "blueprint" so we can add it to shoplist.

// it will perfectly fit in current data scheme

**Comment by msarilar** [comment]
You can update the blueprints json file and submit a PR, I think that's a good idea!

https://github.com/msarilar/EDEngineer/blob/master/EDEngineer/Resources/Data/blueprints.json

**Comment by vetall812** [comment]
done. what about commodities?
Zacariah Nemo wants Xihe Companions for example.

**Comment by msarilar** [comment]
it's true, the bromellite from Bill Turner is a commodity too

right now commodities are entirely ignored by the application but when I initially wrote it I took them into account

when they removed commodities from blueprints recipes, I updated the application to just hide everything commodity-related

might be a good idea to have the blueprints for unlocks requiring only commodities (again, just like Bill Turner which was in your PR) even if they won't appear in the application for now ; at least it will be there

**Comment by vetall812** [comment]
fun thing is - i've just filtered your "entryData.json" for any "Needed" and add this info into PR.
I'll add all other required commodities in... well 5 minutes.

**Comment by msarilar** [comment]
ah you're right ; I think I did not initially add Xihe because it's not used in any blueprints

**Comment by vetall812** [comment]
done. now i guess we need to update entryData.json for "Landmines" etc.

**Comment by vetall812** [comment]
Took a look at entryData.json - can't help you with it, 'cos I do not know FormattedName for enries.

**Comment by msarilar** [comment]
the name of the item in lowercase and with spaces removed should be fine for now, don't worry
