### ISSUE TITLE
Enhancement: More organized shopping list

### ISSUE THREAD

**Issue by mikelimtw** [msarilar/EDEngineer#224]
Hi MSarilar,

I'm a big fan of your work on EDEngineer! You've literally saved my hairline. Anyway, I have a suggestion for the shopping list at the bottom right part of the EDEngineer window. Currently you just list all the materials sorted alphabetically. It's sort of hard to figure out what materials belong to which engineering item. Would it be possible that you group the materials required in a list next to the item being engineered? That would really make the shopping list much more readable. Thanks!

**Comment by msarilar** [comment]
see #158 :)
