### ISSUE TITLE
Feature request - unable to connect to log files

### ISSUE THREAD

**Issue by Redmunchkin** [msarilar/EDEngineer#228]
Hi, 
I can see that this app will be very handy, but unfortunately I'm unable to get it to work.. The issue is that i am unable to navigate to the log files created by ED and used by the APP.. 

My PC is part of a windows active directory and the log files are redirected to this share (by Active Directory)..
\\<Servername>\usershare$\Broadcasting\Saved Games\Frontier Developments\Elite Dangerous

As this is a hidden share I can not browse to the location and I can not see any way to enter this path in to the application... 

Would it be possible to have a text field for entering the folder location? or is there a config file somewhere i could manually change it?

Kind Regards
Red

**Comment by msarilar** [comment]
you can map your share into a drive (which should then be visible from EDEngineer) but I agree that we should be able to input an URI ; I'll see what I can do

**Comment by msarilar** [comment]
published in 1.0.7.3

**Comment by Redmunchkin** [comment]
Doh! should have thought of that work around !
..
Thanks that worked :)

Cool App, thanks for taking the time to develop it

Red

**Comment by Redmunchkin** [comment]
Thanks for the quick replys and the update!

Cheers
Red
