### ISSUE TITLE
[Bug?] Thresholds not persistent across sessions

### ISSUE THREAD

**Issue by ParadoxBomb** [msarilar/EDEngineer#229]
What happened: set up thresholds for each material, powered off computer. When I powered the computer back, on, all thresholds were reset to infinite
What I expected: thresholds to persist similar to favorites and shopping lists

EDEngineer v. 1.0.6.7

**Comment by ParadoxBomb** [comment]
Additional: While looking for the version number, I noticed that the "silent launch" option had also become unchecked.

**Comment by msarilar** [comment]
interesting, could have been linked to the update I published yesterday

could you check on your computer if these persists upon starting/restarting the application now ?

**Comment by ParadoxBomb** [comment]
I cycled the power, and it seems to have retained its settings this time. I'm wondering if for some reason it needed to restart again after updating to the new version. 0o
