### ISSUE TITLE
Add "shopping list" to "ignored and favorite" filter?

### ISSUE THREAD

**Issue by klausw** [msarilar/EDEngineer#234]
Sometimes it's useful to see additional details about recipes in the shopping list, for example to see which engineers offer them. How about adding a filter alongside the "ignored and favorite" filter to see just the current shopping list details?

**Comment by msarilar** [comment]
a filter to show only blueprints that are included in the shopping list? good idea, I'll bring that next update

**Comment by klausw** [comment]
Awesome, thanks!
