### ISSUE TITLE
Windows position isn't retained on HiRes/4K display

### ISSUE THREAD

**Issue by gingters** [msarilar/EDEngineer#235]
Hello,

Every time when I lock / unlock the EDEngineer Window, it jumps around the screen and does not keep the previous position. Mostly it jumps quite a bit to the bottom/right. This makes it impossible to keep the overlay roughly centered on the screen.

Also, whenever the application is restarted, the window starts at another location.

Additional info: I have a Dell UP3214Q monitor (4K), with a resolution of 3840x2160 and the recommended Windows Display scaling of 150%.

**Comment by msarilar** [comment]
I am not sure the solution I came up with solves the issue for good, so before deploying a fix for everybody that'd be great if you could test it on your side.

Here's a zip containing the upcoming version of EDEngineer (unzip it and run EDEngineer.exe, it will behave as a portable application without installation nor auto-update).

[EDEngineer.zip](https://github.com/msarilar/EDEngineer/files/1028709/EDEngineer.zip)

If you're running a multi-screen setup, could you also make sure it remembers *which* screen the app was running between restarts (I can't test multi-screen right now)?

Thanks!

**Comment by gingters** [comment]
Hello,

thanks for the quick response :)

With the version you linked to, the window position now seems stable. Locking / Unlocking the window now does not result in uncontrollable jumping anymore, the window retains the same start position now when the mode is changed.

Also, the window stays on the same screen for me.

Thanks again, that's great now :)

**Comment by msarilar** [comment]
great! thanks for testing, I'll deploy that this afternoon (you can delete the binaries)
