### ISSUE TITLE
"Frame Shift Wake Scanner" vs "Wake Scanner"

### ISSUE THREAD

**Issue by Velak** [msarilar/EDEngineer#237]
There are two entries for Wake scanners. "Wake scanner" has the Wide Angle, Long Range, and Fast. 

"Frame Shift Wake scanner" has the shielded, reinforced, and lightweight. 

The applicable engineers (Lori Jameson, Tiana Fortune, and Bill Turner) refer to them as "Wake Scanners" in the Specialisations / Modify your module menu. 

I propose they all be combined and referred to as "Wake Scanner" for consistency. 

It took me an embarrassingly long time to figure out why "long range" was not showing up as an option when I'd filter to only see "Frame Shift wake scanner"

**Comment by msarilar** [comment]
I agree!
I'll try to fix the json file when I have time, or you can submit a pull request by editing the blueprints file directly : https://github.com/msarilar/EDEngineer/blob/master/EDEngineer/Resources/Data/blueprints.json (`"Type": "Frame Shift Wake Scanner"` -> `"Type": "Wake Scanner"`)

**Comment by Velak** [comment]
By your command. :)

**Comment by msarilar** [comment]
cheers! I'll deploy that tomorrow evening most likely
