### ISSUE TITLE
improvements for the german translation

### ISSUE THREAD

**Issue by nepomuk16321** [msarilar/EDEngineer#241]
Hi Max,
Yesterday I looked at the complete translation again. I have found an error and translations that do not sound good in German.

- the error: "Rarity" - "Qualität" (quality) is called "Seltenheit" or "Rarität" but not "Qualität" !
- sounds bad, e.g. : "Unlock" - "Freischalten" is better than "Aufschließen" . Yes I know, it is my translation, but now I know what it stands for :-)
- e.g. : "Thermal Resistant" - "Thermalresistend" better is "Hitzebeständig"

Can you release the localization again for editing or should I insert the words and phrases (about 20) here ?
I have adapted the translations to the translations in the game.

Thx an have a nice day, greetings nepomuk

**Comment by msarilar** [comment]
You can always edit the file and submit a pull request.

Regarding translations of actual gameplay text (like blueprint names or materials), it's better to keep the name used by the game itself. If Frontier translates "Thermal Resistant" to "Thermalresistend", I'd rather keep it that way to not confuse german players. If Frontier uses "Hitzebeständig" instead then it's a translation error and needs to be fixed :) I do not verify localization submission (apart from syntax errors that would break the application) so it's possible some errors slipped in.

I added a new text for this button which will appear after selecting at least one ingredient so it's also a good occasion to provide a translation for it:

No Ingredient Highlighted:
![image](https://cloud.githubusercontent.com/assets/5569959/26781923/4c5b9b70-49f1-11e7-9ee2-44e9713ec1a4.png)

Three Ingredients Highlighted (see top left of window):
![image](https://cloud.githubusercontent.com/assets/5569959/26781931/5bdebd02-49f1-11e7-9ed5-5de56f2b2424.png)

**Comment by nepomuk16321** [comment]
Ok, I understand. I will review the translations again with the translations in ED.

Thx nepo
