### ISSUE TITLE
EDEng have crashing all the time after start

### ISSUE THREAD

**Issue by MartindForlon** [msarilar/EDEngineer#243]
Just after was downloaded latest actualisation EDEngineers stopped work for me. I tried use newly downloaded setup file and similar looking issue occured. Log files atached
[Crash_logs.zip](https://github.com/msarilar/EDEngineer/files/1056244/Crash_logs.zip)

**Comment by MartindForlon** [comment]
Update: uninstalled fully app and installed clean again did the trick, have ED Eng running again. Sorry for this false alarm

**Comment by msarilar** [comment]
well it's still not supposed to happen ; could you just check your event viewer and see for errors related to EDEngineer ? Windows Key + R `eventvwr` 

![image](https://user-images.githubusercontent.com/5569959/26862991-cbcaf72a-4b4f-11e7-81b4-06b65e7b58d8.png)

Then on the left `Windows Logs` => `Application`

**Comment by MartindForlon** [comment]
Will try check this tomorrow evening when get access to my gaming PC.
