### ISSUE TITLE
Incorrect blueprint

### ISSUE THREAD

**Issue by spoonwzd** [msarilar/EDEngineer#244]
At Felicity Farseer base resource costs are Mech Scrap, Germanium and Classified Scan Databanks, but EDEngineer lists the materials as Mech Scrap, Iron and CSD's.

![image](https://user-images.githubusercontent.com/6536570/27013911-e4d65974-4ee4-11e7-8e72-aa2512f517dc.png)

![image](https://user-images.githubusercontent.com/6536570/27013913-f164fa42-4ee4-11e7-8edf-e7f8fbd75e7a.png)

**Comment by msarilar** [comment]
well spotted! feel free to edit the https://github.com/msarilar/EDEngineer/blob/master/EDEngineer/Resources/Data/blueprints.json and open a pull request, otherwise I'll do that when I have some free time

**Comment by msarilar** [comment]
will be available next deploy (I'll wait a bit in case there's some more issues/localization to reduce the number of deployments)

https://github.com/msarilar/EDEngineer/pull/245#
