### ISSUE TITLE
Synthesis generates more than one warning for materials almost full, if near max materials

### ISSUE THREAD

**Issue by Tkael** [msarilar/EDEngineer#249]
Only one notification should be generated after synthesis if near max materials.
I'm unsure if the same behavior is applied for other notification types, but it may.

**Comment by Tkael** [comment]
Also: `Material almost full, you only have one slots left` and `Material almost full, you only have zero slots left`. Slots should be singular for one slot, and when there are zero slots left the material is no longer "almost full" (re-write as "Material storage is now full"?).

**Comment by msarilar** [comment]
should be trivial to fix

however I need to fix an issue with my certificate first, I think right now if I push an update it would make Windows reject it automatically

**Comment by msarilar** [comment]
removed the warning so it's now irrelevant
