### ISSUE TITLE
Selling Pattern Delta Obelisk data not detected.

### ISSUE THREAD

**Issue by Voz-DeCarabas** [msarilar/EDEngineer#25]
The selling of obelisk data not picked up in the count of data elements.  Relevant line from the Journal.

{ "timestamp":"2016-11-03T20:11:04Z", "event":"ScientificResearch", "Name":"ancientlanguagedata", "Category":"Encoded", "Count":21 }

[Journal.161103193445.01.zip](https://github.com/msarilar/EDEngineer/files/576558/Journal.161103193445.01.zip)

**Comment by msarilar** [comment]
Thanks for investigating the issue, I'll make sure it's in the next version!
