### ISSUE TITLE
Thresholds

### ISSUE THREAD

**Issue by mikelimtw** [msarilar/EDEngineer#250]
I have a suggestion for thresholds. When you set items on the shopping list or delete them, can you automatically fill in the material/data values in the thresholds? That would be a great ease of use/convenience feature. Thanks!

**Comment by Tkael** [comment]
I actually don't want this, since I want to have certain materials at certain levels before I begin placing items on my shopping list. Perhaps having a different notification when adding/removing materials relevant to a shopping list would achieve the same purpose though?
