### ISSUE TITLE
Found new material+data after update 2.3.10

### ISSUE THREAD

**Issue by JohnXaverius** [msarilar/EDEngineer#251]
I found new materials and data in Hip 19026 (Thargoid facility Base - Loc: B1C (-17 / -152))
Flight log in attachment.
JX.

[Journal.170627093154.01.log.zip](https://github.com/msarilar/EDEngineer/files/1105337/Journal.170627093154.01.log.zip)
[Journal.170627093154.01_shorted.log.zip](https://github.com/msarilar/EDEngineer/files/1105336/Journal.170627093154.01_shorted.log.zip)

**Comment by msarilar** [comment]
great stuff, is that the unknowncarapace thing?
I can't play the game right now so I don't know what technical key maps to which name (for example, `ancientbiologicaldata` maps to `Pattern Alpha Obelisk Data`), could you help me out?

**Comment by JohnXaverius** [comment]
OK. No problem.
But I do not know if I have all the possible data and materials that can be found on the ThargoidSite.
Give me some time. :)

**Comment by JohnXaverius** [comment]
For now, I have this. I'm going to scan another Uplink and destroy a couple of scavengers. :)

Data:
tg_compositiondata = Unknown material composition data
tg_residuedata = Unknown residue data analysis
unknownshipsignature = Unknown ship signature
tg_structuraldata = Unknown structural data
unknownwakedata = Unknown wake data

Material:
unknownenergycell = Unknown energy Cell
unknownenergysource = Unknown Fragment
unknownorganiccircuitry = Unknown organic circuitry
unknowntechnologycomponents = Unknown Technology Components

![screenshot_0018](https://user-images.githubusercontent.com/29731838/27591579-61408146-5b52-11e7-8c3a-404e55c223a3.jpg)
![screenshot_0019](https://user-images.githubusercontent.com/29731838/27591578-614055b8-5b52-11e7-8b7d-770df3696f6b.jpg)

**Comment by msarilar** [comment]
brilliant, thanks very much

**Comment by JohnXaverius** [comment]
So. I scanned all (hopefully) UplinkDevice and destroyed about 50 scavengers. I did not get any more information.

**Comment by msarilar** [comment]
thanks again, that was of great help
