### ISSUE TITLE
API doesn't work with CMDR names with spaces

### ISSUE THREAD

**Issue by Uriei** [msarilar/EDEngineer#257]
My CMDR is "Mila Strelok", and http://localhost:44405/commanders returns
`["Mila Strelok"]`
but when I try to do any API call for my CMDR it says
`Commander Mila%20Strelok not found (à¹‘Â´â•¹â€¸â•¹`à¹‘)`

and urls are resolved as http://localhost:44405/Mila%20Strelok/materials, so the error here I guess is that the API doesn't resolve %20 as a space.

**Comment by msarilar** [comment]
thanks for reporting the issue, I fixed this in 5ad4841 and just deployed
