### ISSUE TITLE
MiningRefined events are not processed correctly

### ISSUE THREAD

**Issue by srjek** [msarilar/EDEngineer#26]
Unlike other events, MiningRefined events have their Type field in the format "$_<mineralname>_\_name;"

Example Logs: http://pastebin.com/raw/vg3w4mXy
Near the end of the logs, both samarium and lepidolite have MiningRefined events, and the lepidolite also has a MarketSell event later on.

**Comment by msarilar** [comment]
thanks for the report, will be fixed in next version 1.0.0.19!
