### ISSUE TITLE
2.4 Update : Thargoid Related Materials need renaming & New Materials/Data

### ISSUE THREAD

**Issue by Athanasius** [msarilar/EDEngineer#260]
You have things like Unknown Carapace and Unknown Organic Circuitry.  In 2.4 the game is now calling them Thargoid Carapace and Thargoid Organic Circuitry.  It's the same item as EDE has picked them up under the Unknown names, and shows the same amounts as I have of the Thargoid ones.

**Comment by Athanasius** [comment]
There seems to be a more comprehensive list here: https://github.com/EDDiscovery/EDDiscovery/issues/1229

**Comment by HighwaymanEd** [comment]
I had an error pop up last night after scanning a Thargoid Interceptor: "Unknown material, please contact the author ! tg_shipflightdata"

**Comment by msarilar** [comment]
Thanks for the report! Could you check #251 for how we added 2.3 materials? We will do that in a similar fashion (I need the `technical name <-> game name` mapping)

**Comment by JohnXaverius** [comment]
Hi, i can post some of data and material. But i haven't all. Because we destroyed (for now) only one Thargoid ship.

**Comment by HighwaymanEd** [comment]
Sorry for the delay, here you go

tg_structuraldata = Thargoid Structural Data
tg_shipflightdata = Ship Flight Data
tg_residuedata = Residue Data
tg_compositiondata = Thargoid Material Composition Data

**Comment by msarilar** [comment]
Thanks a lot! Do they all have the same rarity?
Also do you think there are new materials in the game or only these datas?

I'll try and update tonight with the updated naming as well.

**Comment by JohnXaverius** [comment]
If you wait at least until 5 pm, I'll check it out. I did not get to the PC before.
But I think there was more data+material.

**Comment by JohnXaverius** [comment]
Hi,
HighwaymanEd have right.

And rename this item in DataStorage Unknown XYZ  to Thargoid XYZ, just like this:
tg_compositiondata = Thargoid material composition data
tg_residuedata = Thargoid residue data
unknownshipsignature = Thargoid ship signature
tg_structuraldata = Thargoid structural data
unknownwakedata = Thargoid  wake data
tg_shipflightdata = Ship Flight Data

MATERIAL just like this:
unknowncarapace = Thargoid carapace
unknownenergycell = Thargoid energy Cell
unknownenergysource = Unknown Fragment
unknownorganiccircuitry = Thargoid organic circuitry
unknowntechnologycomponents = Thargoid Technology Components

After death of TH sometimes showed "Thargoid Heart" and other materials that I did not have a chance to pick up. I'll contact friends and we try to shoot down one more TH.

Sorry for my bad english. ;)

**Comment by msarilar** [comment]
> unknownenergysource = Unknown Fragment (Here, I do not know exactly what and how. I do not have it.)

should be `Sensor Fragment`

also I'm adding `tg_shipsystemsdata`, assuming it refers to `Ship System Data` (just guessing the name) as somebody posted on discord this screenshot:

![image](https://user-images.githubusercontent.com/5569959/31135893-c82011cc-a866-11e7-8915-d4794e168146.png)

**Comment by msarilar** [comment]
I published an update with updated names and new stuff, got some more provided by a guy on discord

Thanks everyone :) Don't hesitate to open another issue if a new material is discovered!
