### ISSUE TITLE
Starting from the command line

### ISSUE THREAD

**Issue by Tkael** [msarilar/EDEngineer#261]
With VoiceAttack, I like to start EDEngineer automatically whenever I start Elite: Dangerous. I'm able to do this using a batch file containing the following code (which I share in the hope that it is helpful to other users of this fine program):
`rundll32.exe dfshim.dll,ShOpenVerbShortcut %appdata%\Microsoft\Windows\Start Menu\Programs\Max\EdEngineer.appref-ms`
o7!

**Comment by msarilar** [comment]
you can just call directly the `appref-ms` like that in the console without the `rundll32.exe and other parameters`:

`> "C:\Users\%USERNAME%\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\EDEngineer\EDEngineer.appref-ms"`

**Comment by preinboth** [comment]
I can't get EDengineer to start from a batch file.
What am I doing wrong here?

Thanks for the help

:: start EDengineer
start "" "C:\Users\%USERNAME%\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Max\EDEngineer\EDEngineer.appref-ms"
