### ISSUE TITLE
crash after updating to 10.8.4

### ISSUE THREAD

**Issue by rdslw** [msarilar/EDEngineer#264]
This is error (shown in window):

System.Windows.Markup.XamlParseException: Wywołanie konstruktora dla typu „EDEngineer.Views.MainWindow” zgodnego z określonymi ograniczeniami wiązania spowodowało wyjątek. ---> System.ArgumentOutOfRangeException: Unknown key : Unknown Fragment
Nazwa parametru: key
   w EDEngineer.Models.Utils.Collections.SortedObservableCounter.Increment(String key, Int32 value)
   w EDEngineer.Models.State.IncrementCargo(String name, Int32 change)
   w EDEngineer.Models.Operations.ManualChangeOperation.Mutate(State state)
   w EDEngineer.Views.CommanderViewModel.MutateState(JournalEntry entry)
   w EDEngineer.Views.CommanderViewModel.ApplyEventsToSate(IEnumerable`1 allLogs)
   w EDEngineer.Views.CommanderViewModel.LoadState(IEnumerable`1 events)
   w EDEngineer.Views.CommanderViewModel..ctor(String commanderName, IEnumerable`1 logs, Languages languages, List`1 entryDatas)
   w EDEngineer.Views.MainWindowViewModel.LoadState(Boolean forcePickFolder)
   w EDEngineer.Views.MainWindowViewModel..ctor(Languages languages)
   w EDEngineer.Views.MainWindow..ctor()
   --- Koniec śladu stosu wyjątków wewnętrznych ---
   w System.Windows.Markup.WpfXamlLoader.Load(XamlReader xamlReader, IXamlObjectWriterFactory writerFactory, Boolean skipJournaledProperties, Object rootObject, XamlObjectWriterSettings settings, Uri baseUri)
   w System.Windows.Markup.WpfXamlLoader.LoadBaml(XamlReader xamlReader, Boolean skipJournaledProperties, Object rootObject, XamlAccessLevel accessLevel, Uri baseUri)
   w System.Windows.Markup.XamlReader.LoadBaml(Stream stream, ParserContext parserContext, Object parent, Boolean closeStream)
   w System.Windows.Application.LoadBamlStreamWithSyncInfo(Stream stream, ParserContext pc)
   w System.Windows.Application.LoadComponent(Uri resourceLocator, Boolean bSkipJournaledProperties)
   w System.Windows.Application.DoStartup()
   w System.Windows.Application.<.ctor>b__1_0(Object unused)
   w System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   w System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by CMDR-Cometborne** [comment]
Same issue here.  Are you carrying Sensor Fragments as material? I am.

**Comment by rdslw** [comment]
I do, but I did this things and it helped:
* run command rundll32 %windir%\system32\dfshim.dll CleanOnlineAppCache
* killed all smartscreen processes
* run app again: it updated to newest version

dont know what heleped but it works now.

**Comment by msarilar** [comment]
Just patched the app, sorry about that!

The patch should be available as soon as RawGitHub cdn catches up.

**Comment by rdslw** [comment]
THank you for ultra fast update.

BTW, what is needed for the windows 10 not complaining about unsigned app?

**Comment by msarilar** [comment]
well it's signed, just that I use my own cert and I did not publish it to a paying service like VeriSign or similar so Windows doesn't recognize it

not much to do about it, but it's nice to have as if someone else hijacks my GitHub and publishes their own EDEngineer with nasty things in it but sign with another certificate then Windows will plainly just refuse to update the app

**Comment by rdslw** [comment]
I highly appreciate your app and work. If this is up to 100$, I'd happily send you this for you to buy such cert.

**Comment by rdslw** [comment]
BTW, update resetted (?) all threshold I was meticulously was setting in the last few months.
Any chance how to restore it? 
:-(

**Comment by msarilar** [comment]
well to be frank it's not a money issue, I just need to get it done :d
also I get can a free one on https://letsencrypt.org/ but I just need to figure out a way to make the update smoothless (i.e. without having everyone to uninstall and then install again with the new certificate)
