### ISSUE TITLE
thresholds 'in-window' editing

### ISSUE THREAD

**Issue by rdslw** [msarilar/EDEngineer#265]
Currently you can edit 'in-window' amount of material which you have - it's very convenient, although it is mostly done only once, initially when syncing EDEngineer with current state. Later this is not used.

Much more useful, would be allowing editing thresholds in-window, by simply clicking number, entering value (e.g. 20) and enter. This operation is done multiple times by cmdrs, and faster access would be convenient.

Current threshold setting option is very cumbersome: open edengineer, locate small settings icon, click, choose tresholds, in new window locate the material, click, enter, ok, close. 

Rationale:
Due to the low material limit (1000 khem khem :) ) cmdrs use thresholds very actively to quickly throw out just acquired material which exceeds the tresholds. Also commanders use multiple different thresholds for different materials (e.g. CIF: 50, some useless thing: 1, others 10, things on my shopping list: 20 etc.). This makes one, or two limits for everything not a useful mechanism. I personally use around 6 different thresholds which are very differently and uniquely assigned to materials. I also actively change them (after engineering something and no longer needing to have high number of given material).

Would you consider implementing it?

**Comment by msarilar** [comment]
added in f74d6f350b8d5e1f41bc3ebec803849e36b3476f
