### ISSUE TITLE
Add support for CORS response to REST API

### ISSUE THREAD

**Issue by jvarsoke** [msarilar/EDEngineer#269]
Could you please add CORS response headers to the REST API?  I'm trying to do access the API from the browser on another computer, but neither the JSONP, nor CORS options are available.  And thus inherent Cross-Site Scripting problems are occurring.

Hopefully this will make it easy (an example of adding CORS to suave.io): http://www.fssnip.net/mL/title/CORS-response-with-Suave 

Unfortunately, F# isn't one of the languages in my toolbox, so I'd be embarrassed to send you a pull request.

**Comment by msarilar** [comment]
fixed in a6b63a

**Comment by jvarsoke** [comment]
Much thanks.  Now I can destroy my nginx proxy/workaround.

**Comment by msarilar** [comment]
Well try it before, I just kleisli'd the response into suave's CORS monad without much testing 😅
