### ISSUE TITLE
Slight Alignment Issue

### ISSUE THREAD

**Issue by badbud65** [msarilar/EDEngineer#270]
As you can see from the image, there is a small alignment issue with the ticks and crosses, especially when you have a lot of materials in your shopping list.

<a href="https://imgur.com/8L66P2t"><img src="https://i.imgur.com/8L66P2t.png" title="source: imgur.com" /></a>

**Comment by msarilar** [comment]
fixed in 926192aad3733105b3214f7a99cec1745238e4ca
