### ISSUE TITLE
Threshold window

### ISSUE THREAD

**Issue by baja2215** [msarilar/EDEngineer#271]
When I open the threshold window I am unable to do anything in it - I mean literally all I can do is close it via windows. Further it only appears as the minimize/maximize/close buttons in the top right of the window until I [Win]+[Shift]+[Left/right arrow] it only another monitor.

I don't know if this is an issue with my machine etc - but everything else works fine. If anybody else has come across this problem hopefully there is a solution. I have uninstalled and re-installed etc.

Also wondering where the favourites/shopping lists are stored etc as I'd like to duplicate them onto another PC.

**Comment by msarilar** [comment]
Interesting issue. Are you using a locked or unlocked window? Also could you make sure that there are no modal popup hiding in the background (using Alt+Tab). Maybe the event viewer (Window+R, "eventvwr", Windows Logs ▶️ Application) could report some stuff about EDEngineer regarding this problem even though I doubt it ; worth looking into it though!

Regarding the settings location, it should be in `C:\Users\%USERNAME%\AppData\Local\EDEngineer` then into the most recent `EDEngineer.exe_Url_***` folder. There should be a `user.config` file in here.

**Comment by baja2215** [comment]
I'm using an unlocked window. Not seeing anything in application logs.

Nothing under that path for the config files; there is an entry under AppData\Roaming but that only contains a single file for manual changes.

Did a search for that file and identified it at:
C:\Users\<username>\AppData\Local\Apps\2.0\Data\8BT6NLDG.AVD\J4V9WKG7.Q3Y\eden..tion_c7c2cd04d2cdd815_0001.0000_7b273d9213407ebb\Data\1.0.0.0\user.config

There were others but this is clearly the right one and most recent.
