### ISSUE TITLE
1.0.8.4 Upgrade - Missing Shortcuts

### ISSUE THREAD

**Issue by BeckyYork** [msarilar/EDEngineer#273]
I upgraded to 1.0.8.4 and all my shortcuts have vanished.

If i revert to a previous version in control panel features & programmes they come back but then vanish again when I install the newest version.

Additionally, why on earth is the app installed here....

C:\Users\username\AppData\Local\Apps\2.0\J4XKZHQO.QY6\7JT7NDD6.AYZ\eden..tion_c7c2cd04d2cdd815_0001.0000_7b273d9213407ebb

I'm never going to find that!

C:\Program Files (x86)\EDEngineer   please!

**Comment by msarilar** [comment]
No idea for the shortcut loss, that's quite odd. When you mean *all* your shortcuts, which one do you talk about? I believe there's only one (which is used to show/hide the window). Maybe we are not thinking of the same thing?

The install path is linked to the deployment method I used when I first decided to make EDEngineer public. ClickOnce (outdated and bad, but easy and fast) puts the app in here (obfuscated and cryptic, but not in Program Files so *never* requires administrative rights).

There are alternatives for deployment, like Squirell, but it needs some work to be done as well as finding a place to host the release files (don't think I can use GitHub's CDN for that, but maybe I'm wrong). On top of that I believe it would mean making *everybody* uninstall their current EDEngineer to install the new one (using Squirell instead) and finding a way to migrate the settings.

I might do all that later on, maybe if I get back on the game :)
