### ISSUE TITLE
Split Materials into Manufactured and Elements

### ISSUE THREAD

**Issue by daelra** [msarilar/EDEngineer#275]
ED Engineer is one of those essential ED addons so thank you for that. 

I have a couple of suggestions which I hope you agree will make the app even better.

Firstly, is there no way to split Materials into Elements and Manufactured? Often when in my SRV, the only things I'm looking for are elements and when I'm scooping in space, it's just manufactured items so it would be great if I could hide either elements or manufactured items. In fact would it not be better if there were three on/off toggle selection boxes where the Materials and Data headings are so the user could pick either 1, 2 or all the items depending on their requirements.

Secondly, I use the very excellent 'thresholds' feature but it's a bit annoying that I can't increase or decrease the number directly on the main list. I never use the +/- icons on the right so could they be toggled to increase/decrease the threshold amount instead of the quantity?

Anyway, thanks for all your time and effort on this. It really is an indispensable app for ED.

**Comment by msarilar** [comment]
> Firstly, is there no way to split Materials into Elements and Manufactured?

Nope not yet, but I could see this in the future. Just need to think about a good way of presenting the information :)

> Secondly, I use the very excellent 'thresholds' feature but it's a bit annoying that I can't increase or decrease the number directly on the main list

Already the case as part of the latest update

**Comment by msarilar** [comment]
deployed in latest update

**Comment by daelra** [comment]
Thanks Max. Even more useful with the Materials split now. On the second question though, my +- buttons on the left column still add/remove the number of materials I have. My second question was to have the option to change this so that they change the threshold rather than having to go to the configure threshold page.

**Comment by msarilar** [comment]
you can edit the numbers directly 
![image](https://user-images.githubusercontent.com/5569959/32144045-359b9798-bcb3-11e7-8681-f2e3e8e8c93d.png)

**Comment by daelra** [comment]
Cool. I missed that.

Thanks for including it.
