### ISSUE TITLE
ATYPICAL ENCRYPTION ARCHIVES - Found in Encoded USS

### ISSUE THREAD

**Issue by badbud65** [msarilar/EDEngineer#279]
The description for this is the tool is only "Surface POI" 

<a href="https://imgur.com/jTgva8i"><img src="https://i.imgur.com/jTgva8i.png" title="source: imgur.com" /></a>

**Comment by msarilar** [comment]
thanks for reporting!
added in 1de519dc22dffa41d2b0eb1141de186d49ed7785
