### ISSUE TITLE
Request: Sort by amount over / under threshold

### ISSUE THREAD

**Issue by Tkael** [msarilar/EDEngineer#280]
When I need to clean out my material and data stores, it'd be nice to be able to get a sorted list of the materials that deviate the most from my predefined thresholds (rather than a simple sort by count) so that I can prioritize those items that are furthest out of equilibrium for deletion. Thanks!

**Comment by msarilar** [comment]
added in cfad5fc751aca83726d3e0d54bb06a30712251af

**Comment by Tkael** [comment]
that was fast. Thanks!
