### ISSUE TITLE
API: Add Threshold to materials.json/.xml

### ISSUE THREAD

**Issue by jvarsoke** [msarilar/EDEngineer#285]
Would be nice if the data-object for each Material included the user specified Threshold.

E.g.:

```
<root>
<item>
<Kind>Material</Kind>
<Name>Antimony</Name>
<Count>5</Count>
<Threshold>10</Threshold>
</item>

```
If there is another API call to get the Thresholds, please point me to the documentation (couldn't find any reference), but it would be easier on consumption side to include it in the Materials call, since they seem to be related and directly correlated.

Thanks!

**Comment by msarilar** [comment]
added in 3a492b99cf7e3299605f235addd539df1945b904
