### ISSUE TITLE
Translate to Spanish (my group can help)

### ISSUE THREAD

**Issue by omicrono** [msarilar/EDEngineer#29]
Hi, EDEngineer is a great application and is very useful for us.
We are a group of spanish commanders and we can help you for translate to spanish.
We will be happy to translate it into Spanish.
We could collaborate with you and get a version in Spanish?

Best Regards.

**Comment by msarilar** [comment]
The application doesn't handle localization yet. 

It should be doable but it's quite a bit of work!
PR are welcome :)

**Comment by msarilar** [comment]
Please check this file : https://github.com/msarilar/EDEngineer/blob/master/EDEngineer/Resources/Data/localization.json

Ctrl+F for : `"es": null`

I've integrated the translations you already did but there's some I need before fully implement localization :)

Good luck!

**Comment by msarilar** [comment]
> @omicrono
>      
> omicrono commented 2 days ago
> Hi, I'll give you the json files translated into Spanish.
> 
> https://github.com/omicrono/EDEngineer-Spanish-Version-master/tree/master/ficheros%20json%20traducidos
> I have created a fork translated into Spanish as long as you can localize the application
> 
> https://github.com/omicrono/EDEngineer-Spanish-Version-master
> thanks for the interest. If I can help, tell me something.
> 
> Greetings and thansk for all.
>  @msarilar
>      EDEngineer owner
> msarilar commented 2 days ago
> thanks for the good work @omicrono
> 
> let's keep the spanish translation items in the issue you created. that ticket is dedicated to general globalization ; before any translation is implemented, the application needs to be able to handle them (and it's not the case currently)
> 
> I've edited the original post to make it clearer :)
>  @omicrono
>      
> omicrono commented 2 days ago • edited
> Sorry, i change the name of repositorie for upgrade to last version, the new repositorie is:
> 
> https://github.com/omicrono/EDEngineer_Spanish_Version
> 
> and the json files:
> https://github.com/omicrono/EDEngineer_Spanish_Version/tree/master/ficheros%20json%20traducidos
> 
> Greetings.

**Comment by msarilar** [comment]
@omicrono I've published the 1.0.1.0 version which include the translations you did. could you take a look? please note that language can be changed without closing the app (click in the new option in the tasktray icon to open the language selection dialog, and switch between english/spanish to confirm everything's fine)

**Comment by omicrono** [comment]
I'm going to try it, cmdr tcas is translating some missing texts, thank you very much for all the work

regards

**Comment by msarilar** [comment]
congratz, it's all done but one last line I added recently ("please select a language") 

![](http://i.imgur.com/c47zHrI.png)

**Comment by msarilar** [comment]
also @omicrono the ordering is ready too and will be deployed alongside the spanish version

**Comment by msarilar** [comment]
I took the liberty to translate the last missing text:

"Select Language" => "Cambiar Idioma"

the new version is now released and you can fully enjoy it in spanish, thanks to you guys ! 🎉 spread the news :)
