### ISSUE TITLE
ED Engineer Launching, but the window doesn't come up

### ISSUE THREAD

**Issue by rodneywmcbride** [msarilar/EDEngineer#292]
ED Engineer is launching, but is not accessible.

Rebooting hasn't helped, reinstalling just launches the app, again, no window. The Ctrl-F10 doesn't bring the window up either.

**Comment by msarilar** [comment]
Did you check the wiki ? https://github.com/msarilar/EDEngineer/wiki/Troubleshooting-Issues I think the issue is already covered in here

**Comment by rodneywmcbride** [comment]
Thank you.

That information helped me fix the issue. The window was hidden.

Thanks again !!!

Thanks,

Rodney McBride

Atlanta Dual Sport Adventure Riders
ADVrider.com
