### ISSUE TITLE
new Thargoïd materials, not implemented yet!

### ISSUE THREAD

**Issue by Pyag4157624** [msarilar/EDEngineer#293]
...not more to say, the app is asking me to contact the author to inform him/her that some work needs to be done on the new Thargoïds materials, that's all Folks!

**Comment by msarilar** [comment]
are you sure you are using the latest version of the app ? the error message should tell you what data is not recognized (if it doesn't then you're most likely using an older version)

I think the latest version should be 1.0.8.8, you can see that when right clicking the icon in the task tray or clicking the settings gear in the UI

**Comment by Pyag4157624** [comment]
Dear Max,

 

Thanks for answering, I’ll check the version right now. It is version 1.0. So I’ll go right away and dld the new one, by the way, thanks a lot, very helpful app! Bravo!

 



This is what I get, and more of the same taste after ravaging thargoïd scavengers…

I am often having trouble with the reduced window disappearing from my second screen, have to maximize it than reduce size by hand, shortcut does not work (crtl+F10).

 

 

 

De : Max [mailto:notifications@github.com] 
Envoyé : mardi 5 décembre 2017 16:56
À : msarilar/EDEngineer <EDEngineer@noreply.github.com>
Cc : Pol Guillard <pol.guillard@mac.com>; Author <author@noreply.github.com>
Objet : Re: [msarilar/EDEngineer] new Thargoïd materials, not implemented yet! (#293)

 

are you sure you are using the latest version of the app ? the error message should tell you what data is not recognized (if it doesn't then you're most likely using an older version)

I think the latest version should be 1.0.8.8, you can see that when right clicking the icon in the task tray or clicking the settings gear in the UI

**Comment by Pyag4157624** [comment]
Perfectly working, I had the old version. One thing, still, can't seem to find the app menu where I can change the language, it's in French and I play in English, less confusion with the materiel and data naming.

**Comment by msarilar** [comment]
interesting ; try to right click the icon in the task tray (bottom right, in the taskbar), you should get all the options from there

**Comment by Pyag4157624** [comment]
Nope, I get windows commands

**Comment by Pyag4157624** [comment]
You mean your app icon right?

**Comment by msarilar** [comment]
![image](https://user-images.githubusercontent.com/5569959/33730296-d446cabc-db7f-11e7-9d4f-97cdfe6edabe.png)
I meant this

**Comment by Pyag4157624** [comment]
nope, can't see it I see this :
![capture d ecran 2](https://user-images.githubusercontent.com/34247372/33735786-9ebd4f4a-db90-11e7-9b9e-ab4ef1699697.png)

**Comment by msarilar** [comment]
click on the purple gear on the top right of your window, it'll do the same

I screenshotted the task tray, not the app itself

![image](https://user-images.githubusercontent.com/5569959/33735893-f5d58040-db90-11e7-886a-e145b9fbaaef.png)

**Comment by Pyag4157624** [comment]
Yessssss!
