### ISSUE TITLE
Change Font Size

### ISSUE THREAD

**Issue by rosscarlson** [msarilar/EDEngineer#294]
Title pretty much says it all, would love the ability to increase the font size of the shopping list - or a way to export it.  I run a 3 27" setup that is really built only for gaming so reading at distance is hard at normal font size.  I could use Windows scaling but that causes far too many other issues.

**Comment by msarilar** [comment]
Hey Ross,

It's already there 😉 

![image](https://user-images.githubusercontent.com/5569959/34275895-76017468-e69f-11e7-995d-644dae38cecf.png)
![image](https://user-images.githubusercontent.com/5569959/34275907-86bb2ee8-e69f-11e7-8f48-7dd54e18d34e.png)

**Comment by rosscarlson** [comment]
Well look at that - apparently I took my stupid pills instead of the other ones!  In fairness it is a little buried ;-)

How about the ability to export the shopping list?  What I generally do is build my shopping list then start a notepad document with only the things I need to actually find so it's easier to dig through.

**Comment by msarilar** [comment]
already possible via the API, check it out https://github.com/msarilar/EDEngineer/wiki/API-Reference

also let's keep each ticket its own subject (that one was about font size 😉)
