### ISSUE TITLE
Material Location Tracking

### ISSUE THREAD

**Issue by rosscarlson** [msarilar/EDEngineer#296]
So this is a bit complex so bear with me.  This would also require a database on the backend which is something I'm happy to provide.

So ED Engineer knows about my materials the moment I pick them up from the Journal.  If you look at the logs a few/many entries before you'll see the event where I dropped from supercruise at the planet where I gathered it, such as:

{ "timestamp":"2017-12-22T15:17:37Z", "event":"SupercruiseExit", "StarSystem":"35 Vulpeculae", "Body":"35 Vulpeculae B 1", "BodyType":"Planet" }
......lot of other stuff.....
{ "timestamp":"2017-12-22T15:23:01Z", "event":"MaterialCollected", "Category":"Raw", "Name":"niobium", "Count":3 }

So it knows what, when, where and by whom something was picked up.  Imagine if that was tracked in a database for all materials - I go to the database looking for say Nickel and I see that Exigeous just got 3 of them on 35 Vulpeculae B 1 - imagine how helpful that would be.  You could see realtime information with actual live game data as to where things are.  You'd see pickup rates and all kind of useful information for tracking things down.

Then the display of that could be integrated directly into the app - essentially everyone running the app is helping everyone else know where to look for and find things.  It's one thing to read "you can find X in these places" rather than "5 commanders found X in X location in the last 4 hours", etc.

Thoughts?  If I had the skill/time to code the desktop piece I would in a heartbeat as personally I think this would be a killer feature, hell one I'd personally pay for!!!

-Ross

**Comment by rosscarlson** [comment]
Looking at the logs further it seems you don't see if it was a USS that you dropped into but I see the following (these were from bounty hunting)

{ "timestamp":"2017-12-22T09:42:23Z", "event":"SupercruiseExit", "StarSystem":"Kunggalerni", "Body":"Kunggalerni 1 A Ring", "BodyType":"PlanetaryRing" }
.....lot in the middle....
{ "timestamp":"2017-12-22T09:50:49Z", "event":"MaterialCollected", "Category":"Manufactured", "Name":"protolightalloys", "Count":3 }

So you'd just have to keep track of where the ship is from the supercruise jumps/drops which shouldn't be too hard.

**Comment by rosscarlson** [comment]
Any thoughts?  I'm absolutely going to do this - so at best if you/someone is up for helping great at worst I'll just fork the project and add it myself.  No worries if there's no interest, just wondering what you're thinking.

**Comment by msarilar** [comment]
This is quite ambitious :)

I think you're better off using a custom "connector" to upload all logs to a dedicated server and put the json entries into an elastic search cluster (or similar, but ES seems adapted to what you want to do).

You would need to handle anonymity (and duplicates! could be tricky) but once everybody's logs in on the cluster, then it'd be easy to query it (or use any visualization frontend like [grafana](https://grafana.com/) or [kibana](https://www.elastic.co/products/kibana)).

I don't know if EDEngineer should be the "connector" that sends logs to the cluster but if we decide to do it then I think adding a button to upload logs (after anonymization) won't take long.

**Comment by rosscarlson** [comment]
While I don't think it'll be easy I also don't think it's super hard - you're already logging when you get the material so all that would need to be added would be calling a web URL passing the information over.  You could present a few options, like if they want to share it and if so anonymously or not.  After that you have all the information available, what, who, where and how many.

So you wouldn't need to send all the logs, just call the URL each time something is added to the inventory.  The calls would be super lightweight, very little bandwidth usage and I'd host the back end on Amazon AWS so it could grow as needed.

While I could/have another connector created that seems heavy handed and hard to get mass adoption.  As it is EDE is the single most useful third party tool for Engineering and as that's what this data is for it feels like a very natural fit.  You could then add links to the frontend for the data from each material, sorta like you show where they can be found in general.

Every time I think about this or tell someone about it I get more excited by the prospect.  To me the single worst thing with engineering is where to find materials.  It's one thing to know "Find them in High Grade USS in Federation Boom" but another to know "X commander found X in X system X minutes ago" taking much of the wondering or guesswork out of it for new commanders.  Sometimes I'm flying around thinking "this is the right system type isn't it?" by knowing that someone just got them in this system recently would be huge.

Thoughts?  Again I'd love to do the database and web frontend of this, just not a C/VB/Java developer so that's beyond my current skillset.

-Ross

**Comment by msarilar** [comment]
I understand the feature and its usefulness, I agree that finding out *where* to go to find a specific material is annoying and it would be great to have it inside the app.

The main flaw though in that there's no way to correctly identify a log as genuine (e.g. it's not handcrafter by a griefer). EDEngineer is also as stateless as possible regarding logs (it reads through them at each startup) so I'll need to come up with a solid solution to store which logs were already sent to that service and if the user reinstalls or use a different computer then we'd start to have duplicate entries.

There's eddb that seems to have a page for raw material search here https://eddb.io/body where you can input a reference system (that'd be the current system of the player). There doesn't seem to be any API for that specifc search but it would be easy to "spoof" a browser search with an HTTP request as the posted content is pretty straightforward (viewed in chrome, the anti-XSS tag `_csrf` could be generated). Here's an example for a search for Antimony near Diaguandry (sorted by distance):

![image](https://user-images.githubusercontent.com/5569959/35233260-e12a8204-ff9d-11e7-9850-04de5e5a4f73.png)

I would need to map the system name to the id used here and I'm not sure that's in the logs ; the id could very well be an arbitrary number assigned to a given system. But more importantly so I would need to contact the guy who maintains eddb to ask for his authorization 😉 

I'll keep thinking about this and leaving this open, that's a long term goal that could be useful to everybody.

**Comment by msarilar** [comment]
closing this one for now as i've added the top system location

we'll open one in the future if more improvements are needed

**Comment by rosscarlson** [comment]
Just updating really quick as I see you added this a while back - but one question, as I'm planning a part 2 video tutorial - when it shows me a location is that just from my personal data/experience or from ALL players?  Just curious if it's a local or central database - hard to tell on my end.

**Comment by msarilar** [comment]
only from your own experience, nothing's shared as of now

I've recently added a graph that shows mat progression over time (available in the menu), a long term idea is to cross these recording with the system information such that you can see where was the most recent place where you got a material

**Comment by msarilar** [comment]
if you're able to do it, I'd be grateful if you include the fact that you can drag/drop the red horizontal bar splitting the shopping list from the blueprint list which makes the scrollbar appear

many people don't seem to understand (it's not very intuitive) and keep asking about a scrollbar in the shopping list while it's already there (just need to resize the shopping list with the horizontal splitter)
