### ISSUE TITLE
Cannot install after initial setup.exe download

### ISSUE THREAD

**Issue by InfiniteDreamer666** [msarilar/EDEngineer#297]
Hi
for last 2 days i've been trying to install ed engineer 
have followed all instructions.
after downloading initial setup.exe - then run it get the following error

An error occurred trying to download 'https://raw.githubusercontent.com/msarilar/EDEngineer/master/EDEngineer/releases/EDEngineer.application'.

See the setup log file located at 'C:\Users\ID2014\AppData\Local\Temp\VSD35D.tmp\install.log' for more information.

i have tried all the fixes mentioned on the troubleshooting page but nothing seems to work
have tried compatibility - no luck.

Please help - really want to use this app with ED

Steve

**Comment by msarilar** [comment]
what happen when you save the file at `https://raw.githubusercontent.com/msarilar/EDEngineer/master/EDEngineer/releases/EDEngineer.application` (open in a new tab then ctrl+S somewhere on your computer) and then open that file?

**Comment by InfiniteDreamer666** [comment]
Hi - when i click on that file it opens up a window/tab with a load of script on it. if i ctrl + s it opens up a save wiundow but it wants to save it as a text file.
i did try this but obv it just opens up the script in notepad

**Comment by msarilar** [comment]
rename the file to `EDEngineer.application` and try again

**Comment by InfiniteDreamer666** [comment]
Cheers! thats done it - i never thought to change the save type to all files instead of txt file.
have downloaded and run and its working fine - will play with it later 
Cheers again
Steve
