### ISSUE TITLE
Wreckage Components cargo canisters being detected as materials

### ISSUE THREAD

**Issue by Synoxys** [msarilar/EDEngineer#302]
When I pick up a cargo canister containing "Wreckage Components" EDEngineer registers this as though I picked up the "Wreckage Components" _material_ that is currently dropped by thargoid interceptors. When I pick up the canisters, it adds 1 to the total count for every canister I pick up.

**Comment by msarilar** [comment]
thanks for reporting the problem, it's now fixed in the latest update :)
