### ISSUE TITLE
New storage limits for data and materials in ED 3.0

### ISSUE THREAD

**Issue by Gimi1967** [msarilar/EDEngineer#303]
I'm taking the liberty of adding some change requests based on the updates in ED 3.0.
This is based on the changes seen in ED beta 3.0.

Implement new storage limits for data and materials in ED 3.0. 
Notification when limit reached for any material at 100% only

Implement new storage limits:
Limits are for each material type, for all categories, manufactured, elements and data.
100 items for tier 5, very rare
150 items for tier 4, rare
200 items for tier 3, standard
250 items for tier 2, common
300 items for tier 1, very common

**Comment by msarilar** [comment]
given the limit rework, is the warning when full and threshold feature even relevant now? I'm thinking about removing it completely

**Comment by Gimi1967** [comment]
Removing completely would work. The notification in game should be enough.

**Comment by msarilar** [comment]
released in 1.0.9.1
