### ISSUE TITLE
Changes for synthesizing FSD boost in ED 3.0.

### ISSUE THREAD

**Issue by Gimi1967** [msarilar/EDEngineer#304]
I'm taking the liberty of adding some change requests based on the updates in ED 3.0.
This is based on the changes seen in ED beta 3.0.

Implement changes for synthesizing FSD boost in ED 3.0.
Recipes have changed and are now:

FSD Basic
Carbon 1
Vanadium 1
Germainium 1

FSD Standard
Carbon 1
Vanadium 1
Germainium 1
Cadmium 1
Niobium 1

FSD Premium
Carbon 1
Germainium 1
Arsenic 1
Niobium 1
Ytrium 1
Polonium 1

Synthesis should be updated in this file : https://github.com/msarilar/EDEngineer/blob/master/EDEngineer/Resources/Data/blueprints.json

**Comment by msarilar** [comment]
thanks for reporting, fixed in 22af6f0b5f21ddc5bc753512435a74060ee7fc02 (will be in next update)
