### ISSUE TITLE
 Recipes for experimental effects on weapons and modules in ED 3.0

### ISSUE THREAD

**Issue by Gimi1967** [msarilar/EDEngineer#305]
I'm taking the liberty of adding some change requests based on the updates in ED 3.0.
This is based on the changes seen in ED beta 3.0.

Implement recipes for experimental effects in ED 3.0

Experimental effects are now treated as separate recipes.
These are applied to a module separately while docked at engineer, and at a price in materials according to the recipes.

Help wanted to collect and verify recipes for experimental effects:

There si a list compiled from the beta here for weapons:
[https://docs.google.com/spreadsheets/d/1yo1iHP9KUXpoBaIzJsRsDxfAcQa7cBq0YUIFy3m2NII/edit#gid=739612056](https://docs.google.com/spreadsheets/d/1yo1iHP9KUXpoBaIzJsRsDxfAcQa7cBq0YUIFy3m2NII/edit#gid=739612056)

and here for modules:
[https://docs.google.com/spreadsheets/d/1yo1iHP9KUXpoBaIzJsRsDxfAcQa7cBq0YUIFy3m2NII/edit#gid=621486008](https://docs.google.com/spreadsheets/d/1yo1iHP9KUXpoBaIzJsRsDxfAcQa7cBq0YUIFy3m2NII/edit#gid=621486008)

**Comment by msarilar** [comment]
published in 1.0.9.4
