### ISSUE TITLE
No developer onboarding documentation

### ISSUE THREAD

**Issue by sporebat** [msarilar/EDEngineer#308]
I'd chip in and help, but I can't even get it to build, despite having written >100K lines of C# ending a few years back. Things I've noticed so far:

* You might need to turn off signing
* There's one unit test, but I'm not sure how to run it
* There's some F# in `EDEngineer.Server`. F# is not installed in VS Community by default, and you'll get weird errors if you don't install it.
* `Item1` is not defined in `Server.fs` line 229, for some reason
* `Item2` is not defined in `Server.fs` line 229, either
* The metadata file for `EDEngineer.Server` could not be found, but I figure that's because of the above
* The referenced component "Windows" could not be found, but deleting it from EDEngineer References didn't seem to hurt

Give me a hand on solving these, and I'll kick off by writing you some step by step instructions on how to get VS Community set up, the project building, and the tests running.

**Comment by msarilar** [comment]
>There's one unit test, but I'm not sure how to run it

don't bother, I didn't add any tests 😔 

> The referenced component "Windows" could not be found, but deleting it from EDEngineer References didn't seem to hurt

don't, it's used for the toast notification manager for windows 8+ users

>Item1 is not defined in Server.fs line 229, for some reason

weird that there is an explicit tuple here, I've decomposed it in the latest commit https://github.com/msarilar/EDEngineer/commit/f47570871146e5507bfb6aa802526481a4f72fb8

**Comment by sporebat** [comment]
Ok, got it buiding with a few changes:

* Dropped `Windows`
* Added `Windows.UI`
* Added `Windows.Data` and set its `PublishState` to `Exclude`, matching `Windows.UI` (which already had a `PublishState`)
* Disabled `SignManifests`
* Dropped the unused `using Windows.UI.Xaml` in `EDEngineer/Converters/BooleanToEnumConverter.cs`

**Comment by zurie** [comment]
I also was interested in getting this to build now that 3.0 is out.  Huge fan of EDEngineer for 2.4 but with 3.0 those notifcations are super annoying that you are 873 items over your limit of 500 ;)    Is there a branch that you can publish with the changes @sporebat or should I expect some updates in the next bit and wait for that before trying to get my feet wet.

**Comment by msarilar** [comment]
I'll have a look at @sporebat changes if he opens a PR although I'm not sure about the `Windows.UI` replacing `Windows` change (I'll need to try a few things beforehand)

Wasn't aware the 3.0 already got released though, I'll try and see what I can do. In the meantime, you can disable the notifications @zurie (there's a menu for that where you can customize them if you click on the gear icon or right click the task tray icon)

**Comment by zurie** [comment]
ok thanks!   Lots of engineering changes!  no more 500/500 1000/1000 cap, now its per material.  I will do the notification changes and keep a eye on things.  Great work o7

**Comment by Tachy** [comment]
Hi Max, do you know the Elite Dangerous-Tool developer-Network in Discord?
https://discord.gg/cpfU2pP

**Comment by msarilar** [comment]
by the way, I made the application signing only relevant when building in release mode (so you'll be able to build in debug)

plus I've added CI here : https://msarilar.visualstudio.com/EDEngineer/_build/index?definitionId=1
with the build badge on the project README (check it out)

next step will be to add tests (log parsing at first, with sample json from actual logs and expected operations) with NUnit and [Moq](https://github.com/Moq/moq4/wiki/Quickstart) and eventually [SpecFlow](http://specflow.org/getting-started/) to be even more neat
