### ISSUE TITLE
Cannot reinstall nor could i previously install updates

### ISSUE THREAD

**Issue by TheRealMondo** [msarilar/EDEngineer#309]
Every fix i have found on your help page hasn't worked. I get 
![image](https://user-images.githubusercontent.com/32818268/36766653-cbab4c82-1c04-11e8-9d3d-2e4246ef5c4c.png) when i try to install. Below ill have the Details file it gives me. Thanks in advance
[P04HYMAH.log](https://github.com/msarilar/EDEngineer/files/1765374/P04HYMAH.log)

**Comment by msarilar** [comment]
Try to go in this folder :
`C:\Users\%USERNAME%\AppData\Local\Apps\2.0`

then navigate until you find a `manifests` folder. delete any file in there that starts with `eden..`

**Comment by TheRealMondo** [comment]
Worked first try, thanks!
