### ISSUE TITLE
Install does nothing but create shortcut?

### ISSUE THREAD

**Issue by Sotales** [msarilar/EDEngineer#31]
Posted on the Frontier forums as well. Downloaded this today and when I ran the setup.exe it looks like it connects to a server and then closes. Nothing seems to be installed except for a shortcut in my start menu that has no target and does nothing when i use it.

**Comment by msarilar** [comment]
You did not even see release notes?

**Comment by msarilar** [comment]
Here are the instructions I replied on the forums:

I've added today an error window in case of irrecoverable errors, so you might have had one but no message was shown to you because you installed before I published ; you can update the application and let me know. If all else fails, try to uninstall the software and start again.

**Comment by Sotales** [comment]
The first time it just closed after it seemed to download some files. Trying it again I get this log.
[3DZJ45NO.txt](https://github.com/msarilar/EDEngineer/files/579061/3DZJ45NO.txt)

**Comment by Sotales** [comment]
I didn't see it anywhere, but does this need to be installed from any specific location? I am just opening it from my default download folder.

**Comment by msarilar** [comment]
Make sure in the task manager:
* The application is not running
* Any "ClickOnce" process is killed
* Any "SmartScreen" process is killed

**Comment by Sotales** [comment]
Thanks, it was the SmartScreen I suppose. Should have known better as that has prevented me from installing things in the past.

**Comment by msarilar** [comment]
Great ; SmartScreen can be great as a protection, but sometimes it causes deadlocks with ClickOnce. Your SmartScreen protection just needed a restart (killing it did that).

Could you reference that issue URL in your forum post in case other people encounters the same issue? That'd be great.
