### ISSUE TITLE
unrecognized ingredient - Rhenium

### ISSUE THREAD

**Issue by JohnXaverius** [msarilar/EDEngineer#316]
{
"Name": "Rhenium",
"Rarity": "VeryCommon",
"FormattedName": "rhenium",
"Kind": "Material",
"Subkind": "Raw",
"OriginDetails": [ "Minning" ],
"Group": "Category6"
}
![born lead rhenium](https://user-images.githubusercontent.com/29731838/36945393-b4fa01ca-1fad-11e8-9dc7-cc15e443ad2d.jpg)

**Comment by msarilar** [comment]
fixed in 8845f903bb8f2a9ac42d14ab74ab4cf6f855581d (will be in next update)
