### ISSUE TITLE
EDEngineer can't install

### ISSUE THREAD

**Issue by sebaspitt** [msarilar/EDEngineer#319]
Hi, here I include details from installer details after error notice, Thx!

INFORMACIÓN DE VERSIÓN DE LA PLATAFORMA
	Windows 			: 10.0.16299.0 (Win32NT)
	Common Language Runtime 	: 4.0.30319.42000
	System.Deployment.dll 		: 4.7.2556.0 built by: NET471REL1
	clr.dll 			: 4.7.2633.0 built by: NET471REL1LAST_C
	dfdll.dll 			: 4.7.2556.0 built by: NET471REL1
	dfshim.dll 			: 10.0.16299.15 (WinBuild.160101.0800)

ORÍGENES
	Dirección URL de la implementación			: https://raw.githubusercontent.com/msarilar/EDEngineer/master/EDEngineer/releases/EDEngineer.application

RESUMEN DEL ERROR
	Abajo se muestra un resumen de los errores; los detalles de estos errores se incluyen en el registro.
	* La activación de https://raw.githubusercontent.com/msarilar/EDEngineer/master/EDEngineer/releases/EDEngineer.application dio como resultado una excepción. Se detectaron los siguientes mensajes de error:
		+ El ensamblado referido no está instalado en su sistema. (Excepción de HRESULT: 0x800736B3)

RESUMEN DE ERRORES DE TRANSACCIÓN DEL ALMACÉN DE COMPONENTES
	No se detectó ningún error de transacción.

ADVERTENCIAS
	No se generó ninguna advertencia durante esta operación.

ESTADO DE PROGRESO DE LA OPERACIÓN
	* [05/03/2018 19:39:33] : Se ha iniciado la activación de https://raw.githubusercontent.com/msarilar/EDEngineer/master/EDEngineer/releases/EDEngineer.application.

DETALLES DEL ERROR
	Se detectaron los siguientes errores durante esta operación.
	* [05/03/2018 19:39:43] System.Runtime.InteropServices.COMException
		- El ensamblado referido no está instalado en su sistema. (Excepción de HRESULT: 0x800736B3)
		- Origen: System.Deployment
		- Seguimiento de la pila:
			en System.Deployment.Internal.Isolation.IStore.GetAssemblyInformation(UInt32 Flags, IDefinitionIdentity DefinitionIdentity, Guid& riid)
			en System.Deployment.Internal.Isolation.Store.GetAssemblyManifest(UInt32 Flags, IDefinitionIdentity DefinitionIdentity)
			en System.Deployment.Application.ComponentStore.GetAssemblyManifestFromStore(DefinitionIdentity asmId)
			en System.Deployment.Application.ComponentStore.GetAssemblyManifestWithRetry(DefinitionIdentity asmId, TimeSpan retryInterval, Int32 maxRetryCount)
			en System.Deployment.Application.ComponentStore.GetSubscriptionStateInternal(DefinitionIdentity subId)
			en System.Deployment.Application.SubscriptionStore.GetSubscriptionStateInternal(SubscriptionState subState)
			en System.Deployment.Application.SubscriptionStore.CheckAndReferenceApplication(SubscriptionState subState, DefinitionAppId appId, Int64 transactionId)
			en System.Deployment.Application.DownloadManager.DownloadDeploymentManifestDirectBypass(SubscriptionStore subStore, Uri& sourceUri, TempFile& tempFile, SubscriptionState& subState, IDownloadNotification notification, DownloadOptions options, ServerInformation& serverInformation)
			en System.Deployment.Application.DownloadManager.DownloadDeploymentManifestBypass(SubscriptionStore subStore, Uri& sourceUri, TempFile& tempFile, SubscriptionState& subState, IDownloadNotification notification, DownloadOptions options)
			en System.Deployment.Application.ApplicationActivator.PerformDeploymentActivation(Uri activationUri, Boolean isShortcut, String textualSubId, String deploymentProviderUrlFromExtension, BrowserSettings browserSettings, String& errorPageUrl, Uri& deploymentUri)
			en System.Deployment.Application.ApplicationActivator.PerformDeploymentActivationWithRetry(Uri activationUri, Boolean isShortcut, String textualSubId, String deploymentProviderUrlFromExtension, BrowserSettings browserSettings, String& errorPageUrl)
--- Fin del seguimiento de la pila de la ubicación anterior donde se produjo la excepción ---
			en System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
			en System.Deployment.Application.ApplicationActivator.PerformDeploymentActivationWithRetry(Uri activationUri, Boolean isShortcut, String textualSubId, String deploymentProviderUrlFromExtension, BrowserSettings browserSettings, String& errorPageUrl)
			en System.Deployment.Application.ApplicationActivator.ActivateDeploymentWorker(Object state)

DETALLES DE TRANSACCIÓN DEL ALMACÉN DE COMPONENTES
	No hay información disponible sobre la transacción.

**Comment by msarilar** [comment]
did you try the steps here ? 
https://github.com/msarilar/EDEngineer/wiki/Troubleshooting-Issues

**Comment by sebaspitt** [comment]
Fixed, thx!
