### ISSUE TITLE
Localization - Help Translate the Application [ES/DE/FR/RU: a few text missing]

### ISSUE THREAD

**Issue by msarilar** [msarilar/EDEngineer#32]
Use localization for everything string of characters in the application.
PR are welcome

https://github.com/msarilar/EDEngineer/blob/master/EDEngineer/Resources/Data/localization.json

**Comment by omicrono** [comment]
Hi, I'll give you the json files translated into Spanish.
>>> https://github.com/omicrono/EDEngineer-Spanish-Version-master/tree/master/ficheros%20json%20traducidos

I have created a fork translated into Spanish as long as you can localize the application
>>> https://github.com/omicrono/EDEngineer-Spanish-Version-master

thanks for the interest. If I can help, tell me something.

Greetings and thansk for all.

**Comment by msarilar** [comment]
thanks for the good work @omicrono 

let's keep the spanish translation items in the issue you created. that ticket is dedicated to general globalization ; before any translation is implemented, the application needs to be able to handle them (and it's not the case currently)

I've edited the original post to make it clearer :)

**Comment by omicrono** [comment]
Sorry, i change the name of repositorie for upgrade to last version, the new repositorie is:

https://github.com/omicrono/EDEngineer_Spanish_Version

**Comment by msarilar** [comment]
Spanish translation is handled by @omicrono in #29

**Comment by msarilar** [comment]
Russian translation is currently under going in #50

**Comment by msarilar** [comment]
German translation is currently under going in #49

**Comment by msarilar** [comment]
Spanish translation finished as of 1.0.1.2

**Comment by msarilar** [comment]
@Morozova 
@Scorprox 
@calvin00

Since you guys seem to be pretty active, I just wanted to let you know that I'll be away in Lithuania for a week and won't be able to review and merge your pull requests.

I'll proceed first thing when I come back home :)

Here's the current translation status:

<p align="center">
  <img src="http://i.imgur.com/C0geuSN.png" alt="Translation Progress"/>
</p>
