### ISSUE TITLE
Update ED Engineer to read the new ED 3.02 journals.

### ISSUE THREAD

**Issue by Gimi1967** [msarilar/EDEngineer#322]
I'm again taking the liberty of adding a change requests based on the updates in ED 3.0.2
There are some changes in the journal that I assume will have an impact on ED Engineer.

Update ED Engineer to read the new ED 3.0.2 journals.

Change log for Journal documentation Version 16:
Version 16 – for v3.0.2 (5th March 2018)
•	MissionCompleted: if rewards include materials, add category
•	MaterialTrade: include category
•	Status.json: when driving SRV, lat and long changes of 0.0005deg trigger update (in ship remains at 0.02deg)
•	EngineerCraft: some modifications have string values, not float
•	MissionAccepted: add a flag indicating if it is a wing mission
•	New "CargoDepot" event for progress in a wing delivery mission
•	Also fixed:
     o	  Fix localisation of strings where we don't have any substitution parameters to insert into them
     o	  Materials inventory at startup: omit items with a count of zero
     o	  SellDrones: fix sell price (was previously using buy price)

Updated documentation for ED 3.0.2 journals is available here:

https://forums.frontier.co.uk/showthread.php/401661-Journal-Documentation-for-v3-0?p=6335367&viewfull=1#post6335367

**Comment by msarilar** [comment]
thanks for letting me know ; I don't think any of these changes should impact EDEngineer though

**Comment by Gimi1967** [comment]
I'm opening issues as you no longer play (taking a break).
I assume that keeping on top of updates and changes in the game is not on the top of you list of priorities.
If you want me to shut up, just give the word :)

I really appreciate that you continue to update ED Engineer even though you are not playing the game right now.

**Comment by msarilar** [comment]
no this is helpful for sure and I don't mind at all 

I even missed a change in the mission completed event which got updated with 3.0 (materials reward used to be in a separated event but not anymore) so I'll watch more closely if anything new comes up :)
