### ISSUE TITLE
options missing 1.0.9.7

### ISSUE THREAD

**Issue by phantomguru** [msarilar/EDEngineer#323]
had issues updating to latest version so removed outdated version and reinstall latest version successfully. However, i now have no options for thresholds and the only Notifications for blueprints. 
win10 Pro 64.

![ede-options](https://user-images.githubusercontent.com/34688463/37114743-069fd6d8-21fe-11e8-8337-2ce8dd4291f2.png)

![ede-notifications](https://user-images.githubusercontent.com/34688463/37114843-5890ecd4-21fe-11e8-8369-d196317cc054.png)

**Comment by msarilar** [comment]
yes, thresholds are now removed as well as threshold and cargo almost full notifications
they became irrelevant now that the cargo has been reworked
