### ISSUE TITLE
ClickOnce crashes

### ISSUE THREAD

**Issue by StrasnyLada** [msarilar/EDEngineer#326]
Hello,
first of all thank you for this amazing tool, it makes ED much more enjoyable. Now to my problem:
The whole problem started some time ago (a month maybe more), after EDEngineer selfupdated. Now I am not able to run, install or uninstall EDEngineer because every time I try, I get a "clickonce application stopped working". This also happens when I download and run either **setup.exe** or **EDEngineer.application**.

Details of the crash here:
`Podpis problému:

  Název události problému:	CLR20r3
  Podpis problému 01:	dfsvc.exe
  Podpis problému 02:	4.7.2053.0
  Podpis problému 03:	58fa6cbd
  Podpis problému 04:	mscorlib
  Podpis problému 05:	4.7.2117.0
  Podpis problému 06:	59cf513d
  Podpis problému 07:	43e1
  Podpis problému 08:	1e
  Podpis problému 09:	N3CTRYE2KN3C34SGL4ZQYRBFTE4M13NB
  Verze operačního systému:	6.1.7601.2.1.0.256.48
  ID národního prostředí:	1029
  Další informace 1:	8f81
  Další informace 2:	8f81fec7dc9c562526e7c63917770b2d
  Další informace 3:	551d
  Další informace 4:	551dc284711ab1b9e505cf52155aa0cc
`
I also tried to delete anything starting with _eden..._ in the "Users\Username\AppData\Local\Apps\2.0" and its subfolders, but to no avail.
If you need any more information, ask, I shall provide.

**Comment by msarilar** [comment]
you might want to check Windows Logs as explained here : https://github.com/msarilar/EDEngineer/issues/310#issuecomment-370152359

also make sure to run `rundll32 %windir%\system32\dfshim.dll CleanOnlineAppCache` in a terminal

**Comment by StrasnyLada** [comment]
Název protokolu:Application
Zdroj:         .NET Runtime
Datum:         9.3.2018 7:30:21
ID události:   1026
Kategorie úlohy:Není
Úroveň:        Chyba
Klíčová slova: Klasické nastavení
Uživatel:      Není k dispozici
Počítač:       Gawain
Popis:
Aplikace: dfsvc.exe
Verze Framework: v4.0.30319
Popis: Proces byl ukončen z důvodu neošetřené výjimky.
Informace o výjimce: System.TypeLoadException
   na System.Reflection.CustomAttribute._CreateCaObject(System.Reflection.RuntimeModule, System.IRuntimeMethodInfo, Byte**, Byte*, Int32*)
   na System.Reflection.CustomAttribute.CreateCaObject(System.Reflection.RuntimeModule, System.IRuntimeMethodInfo, IntPtr ByRef, IntPtr, Int32 ByRef)
   na System.Reflection.CustomAttribute.GetCustomAttributes(System.Reflection.RuntimeModule, Int32, Int32, System.RuntimeType, Boolean, System.Collections.IList, Boolean)
   na System.Reflection.CustomAttribute.GetCustomAttributes(System.RuntimeType, System.RuntimeType, Boolean)
   na System.ComponentModel.ReflectTypeDescriptionProvider.ReflectGetAttributes(System.Type)
   na System.ComponentModel.ReflectTypeDescriptionProvider+ReflectedTypeData.GetAttributes()
   na System.ComponentModel.TypeDescriptor+TypeDescriptionNode+DefaultTypeDescriptor.System.ComponentModel.ICustomTypeDescriptor.GetAttributes()
   na System.ComponentModel.TypeDescriptor.GetAttributes(System.Type)
   na System.ComponentModel.ReflectTypeDescriptionProvider+ReflectedTypeData.GetConverter(System.Object)
   na System.ComponentModel.TypeDescriptor+TypeDescriptionNode+DefaultTypeDescriptor.System.ComponentModel.ICustomTypeDescriptor.GetConverter()
   na System.Windows.Forms.TableLayoutSettings..ctor(System.Runtime.Serialization.SerializationInfo, System.Runtime.Serialization.StreamingContext)

Informace o výjimce: System.Reflection.TargetInvocationException
   na System.RuntimeMethodHandle.SerializationInvoke(System.IRuntimeMethodInfo, System.Object, System.Runtime.Serialization.SerializationInfo, System.Runtime.Serialization.StreamingContext ByRef)
   na System.Runtime.Serialization.ObjectManager.CompleteISerializableObject(System.Object, System.Runtime.Serialization.SerializationInfo, System.Runtime.Serialization.StreamingContext)
   na System.Runtime.Serialization.ObjectManager.FixupSpecialObject(System.Runtime.Serialization.ObjectHolder)
   na System.Runtime.Serialization.ObjectManager.DoFixups()
   na System.Runtime.Serialization.Formatters.Binary.ObjectReader.Deserialize(System.Runtime.Remoting.Messaging.HeaderHandler, System.Runtime.Serialization.Formatters.Binary.__BinaryParser, Boolean, Boolean, System.Runtime.Remoting.Messaging.IMethodCallMessage)
   na System.Runtime.Serialization.Formatters.Binary.BinaryFormatter.Deserialize(System.IO.Stream, System.Runtime.Remoting.Messaging.HeaderHandler, Boolean, Boolean, System.Runtime.Remoting.Messaging.IMethodCallMessage)
   na System.Resources.ResourceReader.DeserializeObject(Int32)
   na System.Resources.ResourceReader.LoadObjectV2(Int32, System.Resources.ResourceTypeCode ByRef)
   na System.Resources.ResourceReader.LoadObject(Int32)
   na System.Resources.ResourceReader+ResourceEnumerator.get_Entry()
   na System.Resources.ResourceReader+ResourceEnumerator.get_Current()
   na System.ComponentModel.ComponentResourceManager.FillResources(System.Globalization.CultureInfo, System.Resources.ResourceSet ByRef)
   na System.ComponentModel.ComponentResourceManager.FillResources(System.Globalization.CultureInfo, System.Resources.ResourceSet ByRef)
   na System.ComponentModel.ComponentResourceManager.FillResources(System.Globalization.CultureInfo, System.Resources.ResourceSet ByRef)
   na System.ComponentModel.ComponentResourceManager.ApplyResources(System.Object, System.String, System.Globalization.CultureInfo)
   na System.Deployment.Application.SplashPiece.InitializeComponent()
   na System.Deployment.Application.SplashPiece..ctor(System.Deployment.Application.UserInterfaceForm, System.Deployment.Application.SplashInfo)
   na System.Deployment.Application.UserInterfaceForm.InitializeContent()
   na System.Deployment.Application.UserInterfaceForm..ctor(System.Threading.ManualResetEvent, System.Deployment.Application.SplashInfo)
   na System.Deployment.Application.UserInterface.UIThread()
   na System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   na System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   na System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   na System.Threading.ThreadHelper.ThreadStart()


Kód XML události:
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name=".NET Runtime" />
    <EventID Qualifiers="0">1026</EventID>
    <Level>2</Level>
    <Task>0</Task>
    <Keywords>0x80000000000000</Keywords>
    <TimeCreated SystemTime="2018-03-09T06:30:21.000000000Z" />
    <EventRecordID>79599</EventRecordID>
    <Channel>Application</Channel>
    <Computer>Gawain</Computer>
    <Security />
  </System>
  <EventData>
    <Data>Aplikace: dfsvc.exe
Verze Framework: v4.0.30319
Popis: Proces byl ukončen z důvodu neošetřené výjimky.
Informace o výjimce: System.TypeLoadException
   na System.Reflection.CustomAttribute._CreateCaObject(System.Reflection.RuntimeModule, System.IRuntimeMethodInfo, Byte**, Byte*, Int32*)
   na System.Reflection.CustomAttribute.CreateCaObject(System.Reflection.RuntimeModule, System.IRuntimeMethodInfo, IntPtr ByRef, IntPtr, Int32 ByRef)
   na System.Reflection.CustomAttribute.GetCustomAttributes(System.Reflection.RuntimeModule, Int32, Int32, System.RuntimeType, Boolean, System.Collections.IList, Boolean)
   na System.Reflection.CustomAttribute.GetCustomAttributes(System.RuntimeType, System.RuntimeType, Boolean)
   na System.ComponentModel.ReflectTypeDescriptionProvider.ReflectGetAttributes(System.Type)
   na System.ComponentModel.ReflectTypeDescriptionProvider+ReflectedTypeData.GetAttributes()
   na System.ComponentModel.TypeDescriptor+TypeDescriptionNode+DefaultTypeDescriptor.System.ComponentModel.ICustomTypeDescriptor.GetAttributes()
   na System.ComponentModel.TypeDescriptor.GetAttributes(System.Type)
   na System.ComponentModel.ReflectTypeDescriptionProvider+ReflectedTypeData.GetConverter(System.Object)
   na System.ComponentModel.TypeDescriptor+TypeDescriptionNode+DefaultTypeDescriptor.System.ComponentModel.ICustomTypeDescriptor.GetConverter()
   na System.Windows.Forms.TableLayoutSettings..ctor(System.Runtime.Serialization.SerializationInfo, System.Runtime.Serialization.StreamingContext)

Informace o výjimce: System.Reflection.TargetInvocationException
   na System.RuntimeMethodHandle.SerializationInvoke(System.IRuntimeMethodInfo, System.Object, System.Runtime.Serialization.SerializationInfo, System.Runtime.Serialization.StreamingContext ByRef)
   na System.Runtime.Serialization.ObjectManager.CompleteISerializableObject(System.Object, System.Runtime.Serialization.SerializationInfo, System.Runtime.Serialization.StreamingContext)
   na System.Runtime.Serialization.ObjectManager.FixupSpecialObject(System.Runtime.Serialization.ObjectHolder)
   na System.Runtime.Serialization.ObjectManager.DoFixups()
   na System.Runtime.Serialization.Formatters.Binary.ObjectReader.Deserialize(System.Runtime.Remoting.Messaging.HeaderHandler, System.Runtime.Serialization.Formatters.Binary.__BinaryParser, Boolean, Boolean, System.Runtime.Remoting.Messaging.IMethodCallMessage)
   na System.Runtime.Serialization.Formatters.Binary.BinaryFormatter.Deserialize(System.IO.Stream, System.Runtime.Remoting.Messaging.HeaderHandler, Boolean, Boolean, System.Runtime.Remoting.Messaging.IMethodCallMessage)
   na System.Resources.ResourceReader.DeserializeObject(Int32)
   na System.Resources.ResourceReader.LoadObjectV2(Int32, System.Resources.ResourceTypeCode ByRef)
   na System.Resources.ResourceReader.LoadObject(Int32)
   na System.Resources.ResourceReader+ResourceEnumerator.get_Entry()
   na System.Resources.ResourceReader+ResourceEnumerator.get_Current()
   na System.ComponentModel.ComponentResourceManager.FillResources(System.Globalization.CultureInfo, System.Resources.ResourceSet ByRef)
   na System.ComponentModel.ComponentResourceManager.FillResources(System.Globalization.CultureInfo, System.Resources.ResourceSet ByRef)
   na System.ComponentModel.ComponentResourceManager.FillResources(System.Globalization.CultureInfo, System.Resources.ResourceSet ByRef)
   na System.ComponentModel.ComponentResourceManager.ApplyResources(System.Object, System.String, System.Globalization.CultureInfo)
   na System.Deployment.Application.SplashPiece.InitializeComponent()
   na System.Deployment.Application.SplashPiece..ctor(System.Deployment.Application.UserInterfaceForm, System.Deployment.Application.SplashInfo)
   na System.Deployment.Application.UserInterfaceForm.InitializeContent()
   na System.Deployment.Application.UserInterfaceForm..ctor(System.Threading.ManualResetEvent, System.Deployment.Application.SplashInfo)
   na System.Deployment.Application.UserInterface.UIThread()
   na System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   na System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   na System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   na System.Threading.ThreadHelper.ThreadStart()

</Data>
  </EventData>
</Event>

**Comment by JohnXaverius** [comment]
Zdar Láďo, to vypadá, že máš dojebanej FrameWork. Našel jsem k tomu nějakou CheckTool.
Zkusil bych napřed ten, pak bych zkusil kompletně přeinstalovat Framework.

https://social.msdn.microsoft.com/Forums/vstudio/en-US/125e76cc-dc83-436c-8502-9b3e60cfb5d5/net-framework-version-v4030319-description-the-process-was-terminated-due-to-an-unhandled?forum=netfxsetup

Popř. ještě můžeš zkusit pustit kontrolu integrity systémových souborů
CMD line: SFC /scannow

https://support.microsoft.com/cs-cz/help/929833/use-the-system-file-checker-tool-to-repair-missing-or-corrupted-system

**Comment by StrasnyLada** [comment]
Díky, to bylo přesně ono. Test na .NET Framework 2.0, 3.0, 3.5 prošel, od 4.0 nahoru fail. opraveno a EDEngineer jede.
-----
Kudos to JohnXaverius for links to verify .NET Framework. Reinstalled .NET 4.7 and EDEngineer is working again.
