### ISSUE TITLE
no scrolling in shopping list

### ISSUE THREAD

**Issue by guitarpy** [msarilar/EDEngineer#330]
I've put together a rather large shopping list, considering all the g1-5 mats needed to fully engineer a corvette in 3.0 from the ground up, and I've noticed that there appears to be no way to scroll in the shopping list...I've had to up my resolution to 4k and lower my text size to see the whole list...scrolling functionality would be greatly appreciated so that I don't need to break out a magnifying glass to see what I need.
![edengineer_2018-03-10_23-24-46](https://user-images.githubusercontent.com/37273394/37256939-1a1fa250-2538-11e8-8d29-54c8ec4ddf39.png)

All in, GREAT WORK on this app, it has become an integral part of my engineering. Kudos

**Comment by msarilar** [comment]
The red separator between the blueprints and the shopping list can be dragged around to change the size of the shopping list panel (double clicking it will reset it to a dynamic behaviour)

You can also change the font size in the graphics configuration

![image](https://user-images.githubusercontent.com/5569959/37256961-9aa793fe-2562-11e8-9ddd-f6d2d09d2395.png)

**Comment by guitarpy** [comment]
I've dragged it to the top...didn't realize the font size could be changed...that'll be handy, but even with the size changed to just plain unreadable without a magnifying glass, the list on the right of the panel runs off the bottom of the page. 

For now I've discovered a workaround by filtering non-craftable against my shopping list in the scrollable upper right panel, but scrolling functionality on the lower right panel would be a godsend, as checking things off on my list is going to be difficult if they are off the bottom of the screen.  

I really appreciate the fast response - keep up the good work.

**Comment by guitarpy** [comment]
Pre 3.0 it wasn't an issue...but with 3.0 to do a ground up engineering each module requires 5 items on the list, and most require an experimental on  there as well....my shopping lists are a lot longer these days with 6 entries per module in place of 1, and I've always done my engineering in 1 fell swoop...make the list....get all the mats....go to all the engineers - this wouldn't have been possible without your software, and I'm forever grateful for all the hard work you've done to date.

**Comment by msarilar** [comment]
Glad to hear the app is still being useful :)

I might have misunderstood the problem but here are the two scroll bars available:
![image](https://user-images.githubusercontent.com/5569959/37257185-da3a2a4c-2565-11e8-9132-862e6b5352a0.png)

**Comment by guitarpy** [comment]
oddly enough it just came back on mine...it was not appearing/functioning before...now suddenly it is...very strange....I haven't even closed/re-opened the program and suddenly it works...LOL

**Comment by msarilar** [comment]
all right then :)
