### ISSUE TITLE
Czech Localization

### ISSUE THREAD

**Issue by JohnXaverius** [msarilar/EDEngineer#331]
Hi @msarilar , what do I have to do, to translate EDEngineer into my language? :)
I need to know which files contain language data and possibly if you have a procedure, how it should look.
Thanks

**Comment by msarilar** [comment]
you're very welcome to add czech localization in the localization file here : https://github.com/msarilar/EDEngineer/blob/master/EDEngineer/Resources/Data/localization.json

you will need to add a "language" block (similar to the others) and then add a localization for each text below. if a translation is not provided for a given text, then the english version is used.

for instance, this is the brazilian localization PR : https://github.com/msarilar/EDEngineer/pull/268/files

**Comment by JohnXaverius** [comment]
OK. File downloaded.
Shortcut for Czech is **cs** or **cz** or doesn't matter?
And last question. :)
Special characters such as "**ě š č ř ž ý á í é**" will not be a problem with them?

**Comment by msarilar** [comment]
should be `cs` for the two letter code (https://en.wikipedia.org/wiki/List_of_ISO_639-1_codes, https://www.loc.gov/standards/iso639-2/php/langcodes_name.php?iso_639_1=cs)

these letters shouldn't cause issues, there's already the russian localization with cyrillic alphabet which works fine so I don't think the caron on letters will cause problems 🙂

**Comment by msarilar** [comment]
https://github.com/msarilar/EDEngineer/pull/358
