### ISSUE TITLE
Missing mods

### ISSUE THREAD

**Issue by svetislavn** [msarilar/EDEngineer#334]
Mods for Power Distributor Engine Focused (grade 4 and 5) and Power Plant Low Emissions (grade 4 and 5), are missing.

**Comment by msarilar** [comment]
Thanks for reporting!

Feel free to update the blueprints file I curated for the application : https://github.com/msarilar/EDEngineer/blob/master/EDEngineer/Resources/Data/blueprints.json
You'll see that it's a simple array of objects separated by commas, and they're pretty straightforward:

  {
    "Type": "Plasma Accelerator",
    "Name": "Short Range Blaster",
    "Engineers": [
      "Zacariah Nemo",
      "Bill Turner"
    ],
    "Ingredients": [
      {
        "Name": "Modified Consumer Firmware",
        "Size": 1
      },
      {
        "Name": "Nickel",
        "Size": 1
      },
      {
        "Name": "Insulating Membrane",
        "Size": 1
      }
    ],
    "Grade": 2
  }

You just have to be careful with the names (ingredients, type, engineers) and use the exact same as other blueprints (same casing, no dashes etc..)

**Comment by msarilar** [comment]
https://github.com/msarilar/EDEngineer/pull/337
