### ISSUE TITLE
Question: What is the number next to the Top Source Systems entry?

### ISSUE THREAD

**Issue by markjfisher** [msarilar/EDEngineer#338]
Just not sure what the number represents against each system in the Top Source Systems, and can't find any notes on it yet.

![image](https://user-images.githubusercontent.com/1616940/37586180-6f3c5406-2b53-11e8-851e-972569b3ebef.png)

Where is it sourcing this data?
I tried a system on the list and got no HGEs spawn, so was unable to verify it's doing what it's supposed to.

**Comment by msarilar** [comment]
it's how many you found of that ingredient in this particular system.

it uses your personal logs which means that if you delete your log folder, you won't have that information anymore even though you'll still get the right amount of materials for each ingredient (since this is dumped at each startup of the game).

**Comment by markjfisher** [comment]
I see, thanks. Does it take into account the state required (e.g. Federation in Boom) vs what it currently is? I might head somewhere based on this info but when I get there, there won't spawn any.

**Comment by msarilar** [comment]
as of right now it doesn't take any dynamic information into account, only the system name

it's something that could come up in the future though, just need a way to cleanly display the info without cluttering the tooltip even more

**Comment by markjfisher** [comment]
Cool, look forward to it. BTW, really appreciate the 3.0 changes you made with the groupings so I can mentally work out how many of one item I can convert to others in same subgroups.
