### ISSUE TITLE
Invalid JSON for blueprints.json

### ISSUE THREAD

**Issue by corenting** [msarilar/EDEngineer#339]
Hello,

When parsing the blueprints.json  (https://github.com/msarilar/EDEngineer/blob/master/EDEngineer/Resources/Data/blueprints.json), various JSON parsers (Python's parser, https://codebeautify.org/jsonvalidator ...) report errors when parsing the file, around the line 2336-2337.

**Comment by msarilar** [comment]
b3e163d0e2ce872f89faaefbcef4bb610c71c032
