### ISSUE TITLE
Wiki

### ISSUE THREAD

**Issue by msarilar** [msarilar/EDEngineer#34]
* Frequently Asked Questions
* Common Issues
* How to use the application

**Comment by msarilar** [comment]
Hello @RFQ-hub/dev

**Comment by rosscarlson** [comment]
Does the fact that the "help wanted" tag is applied here mean you're looking for help to do this?  If so I'd love to pitch in if I can.  I've done lots of testing and moderation of various projects and sites, from 2005-2008 I created and ran on open source project.  It grew to over 50,000 installs and 2 others joined me along the way.  I did most of the coding (PHP) and setup and managed our support forums and wiki.

If that's something you'd like to chat about by all means let me know.  Now, thanks to your help, that I have EDE working and have started using it I'm an even bigger fan.  It took me from zero interest in Engineering to "this ain't bad" and it did so very quickly.  I can't see how anyone would use Engineering without it.

**Comment by msarilar** [comment]
hey that's pretty awesome!

yeah I figured people could help submit documentation stuff about the application. Especially in game screenshots of common use cases ; like when you're tracking materials, or the shopping list, or anything else that would need a specific window size / position.

It's not extremely urgent or vital, but would help new users (for instance I had a few requests to make a video of it, but couldn't find the time to do it).

the idea is to use the [project's wiki](https://github.com/msarilar/EDEngineer/wiki) which accepts markdown content. anyone is welcome to contribute (I think I configured it to be editable by anyone) so feel free to add stuff if you think it's appropriate :)

**Comment by rosscarlson** [comment]
"I had a few requests to make a video of it, but couldn't find the time to do it"

Honestly I was considering making a video for it already so I think I'll start there.  I hear this video stuff is all the rage these days ;-)

Quick question before I screw up my current EDE, what would I backup so that I could start fresh with EDE but then restore my stuff back after?  Just that json file that's in my profile?  I'm guessing it's more to it than that, if you let me know I'll work on the video soon.

**Comment by Psieonic** [comment]
If I recall, EDE now uses the journal to get the full material list. The json only stores offsets, if at all necessary. Can't guarantee it, but you should be right to just fiddle around and delete that file if you want to remove custom offsets.

I'm sure m.s. can confirm though. :)
