### ISSUE TITLE
Sync not syncing

### ISSUE THREAD

**Issue by awdwyn** [msarilar/EDEngineer#340]
Not sure if there's anything log-wise I can provide to help, but I noticed when 1.0.9.7 was released that sync worked when crafting a blueprint at an engineer base, but not remotely, and crafting an experimental wouldn't sync. A little bit later (still on 9.7) it completely stopped working and as of 9.9 is still broken.

**Comment by msarilar** [comment]
upload your journal logs as a zip file here and I'll have a look tonight

**Comment by awdwyn** [comment]
Okie dokie - cheers!

[log files: Elite Dangerous.zip](https://github.com/msarilar/EDEngineer/files/1829992/Elite.Dangerous.zip)
[json files: Extras.zip](https://github.com/msarilar/EDEngineer/files/1829995/Extras.zip)

**Comment by msarilar** [comment]
I don't see anything wrong yet.
Are you sure that the path displayed at the bottom points to your log folder ?
![image](https://user-images.githubusercontent.com/5569959/37670951-de3be796-2c6a-11e8-9681-6051d10b6db7.png)

nobody else has reported such issue yet

is it a particular ingredient that isn't substracted, or a particular blueprint craft?

to be clear ; your ingredients count "drifts" away from the game and you have to restart the game to get the correct numbers?

**Comment by awdwyn** [comment]
It's reading the logs ok, as it tracks material/data counts on the left side right - where it gets wonky is in the shopping list section as I craft a blueprint. The sync checkbox is checked:
![sync](https://user-images.githubusercontent.com/23404043/37671677-dc2d5a86-2c31-11e8-90a7-cbd4803a4635.PNG)
but if I craft a blueprint it does not reduce the blueprint numbers in the shopping list as expected.

**Comment by msarilar** [comment]
do you have both the blueprint and the experimental effect in your shopping list?

**Comment by awdwyn** [comment]
Yes - initially in .9.7 the blueprint would be reduced, but not the experimental - later (sitill in .9.7) both stopped working.

This is an example of what I'd do....
![capture](https://user-images.githubusercontent.com/23404043/37673642-5c9b519c-2c36-11e8-98d6-d0da8f62dac1.PNG)

**Comment by msarilar** [comment]
ok I might have something that could help, your logs helped a lot
although it's still going to be in a prototype status...

I'll wait a few days before deploying just in case people working on localization (@nepomuk16321, @JohnXaverius, @wesleymoura) opens a pull request with their changes (to reduce the number of deployments)

**Comment by awdwyn** [comment]
Awesome! Thanks for looking into it - as soon as I saw that checkbox I got excited as when I'm engineering a whole ship (happens a lot) and especially in post-3.0 when we need to account for the G1-4 rolls as well I have a huge list of blueprints (to the point where the app slows right down). This feature would be super useful.

**Comment by msarilar** [comment]
should be fixed with latest update
