### ISSUE TITLE
Error in Shopping List

### ISSUE THREAD

**Issue by CMDRPhaedra** [msarilar/EDEngineer#344]
In the shopping list Ruthenium is shown as Rhenium and doesn't match against materials.

**Comment by msarilar** [comment]
what blueprint specifically?

**Comment by CMDRPhaedra** [comment]
Either of the Human Shock cannons

**Comment by msarilar** [comment]
I don't understand, they do require Rhenium and not Ruthenium so it's normal that Rhenium shows up and not Ruthenium?

http://elite-dangerous.wikia.com/wiki/Technology_Broker

**Comment by CMDRPhaedra** [comment]
Apologies i was being a fool.
