### ISSUE TITLE
Life Support Lightweight Grade 5 Blueprint Missing

### ISSUE THREAD

**Issue by badbud65** [msarilar/EDEngineer#345]
Life Support Lightweight Grade 5 Missing - Current EDEngineer only has this Blueprint going up to level 4.

See These Pages for details of Level 5
http://elite-dangerous.wikia.com/wiki/Lightweight_Module
https://inara.cz/galaxy-blueprint/133/

**Comment by awdwyn** [comment]
I think those are wrong - last time I checked no engineer in the game actually did a grade 5 life support.

**Comment by badbud65** [comment]
Now I look at those pages in detail neither show which engineer can do this upgrade, so you are probably right.

**Comment by Tagom** [comment]
I have now completed a Grade 5 Life Support engineering. Sent the info the developers discord a few days ago.

Completed G5 Lightweight
https://cdn.discordapp.com/attachments/530205999525527562/557925279377522709/unknown.png

Lightweight
https://cdn.discordapp.com/attachments/530205999525527562/557919353937330187/unknown.png

Reinforced
https://cdn.discordapp.com/attachments/530205999525527562/557921457926307870/unknown.png

Shielded
https://cdn.discordapp.com/attachments/530205999525527562/557921600293306378/unknown.png


Additionally G5 for Shield Cell Banks from Mal Brandon is close to completing as well.

**Comment by Tagom** [comment]
Ahh yep Cometborne had raised this already https://github.com/msarilar/EDEngineer/pull/500
