### ISSUE TITLE
Please insert an option to disable the latest shopping list design.

### ISSUE THREAD

**Issue by ElanSolo** [msarilar/EDEngineer#346]
I'm really not a fan of the latest update to the shopping list.  The grades box takes up way too much space for my liking.  I really have no interest in the lower grades for blueprints, if I did I'd pin them individually to the list... Would you consider allowing an option to revert to the older more compact shopping list?

cheers! :)

**Comment by msarilar** [comment]
no I won't revert to the older shopping list but I agree that it can take an unnecessary amount of room so I've put this together, will most likely deploy during the week

![shopping](https://user-images.githubusercontent.com/5569959/37792584-727cd864-2e0c-11e8-9124-2b0918dec7d6.gif)

**Comment by msarilar** [comment]
now deployed

**Comment by ElanSolo** [comment]
I appreciate what you've done to reduce the size of the boxes, I feel they could still be more efficiently sized and also re-stack dependant on the window width?

This is how it looks snapped to the right half of my screen...

![image](https://user-images.githubusercontent.com/19846708/37823057-415c3274-2e80-11e8-9443-ff2c311c37cf.png)

**Comment by msarilar** [comment]
I see ; you could maybe resize your left panel?

when the window is unlocked there is a splitter in the middle you can move (similar to the splitter between the shopping list and the blueprints, except that it's vertical and separates the left and the right panels)

if you resize it and there *should* be enough room although the shopping list doesn't shows up properly, you should restart the app (there are some slight repositionning issues that can occur)

**Comment by ElanSolo** [comment]
Yep, that's an option, but I would prefer to not see the boxes at all, or make them smaller, rather than give them yet more screen space. ;)
