### ISSUE TITLE
Log parsing error

### ISSUE THREAD

**Issue by Andargor** [msarilar/EDEngineer#347]
Here you go, probably related to Guardian modules.

https://i.imgur.com/9yft30G.png

https://i.imgur.com/FgIIMPI.png

**Comment by msarilar** [comment]
thanks for reporting
the log manual didn't specify that format (EDEngineer was trying to access an "Ingredients" property but turns out it's "Materials")

patch is deployed 👍 

![image](https://user-images.githubusercontent.com/5569959/37801442-ecad05d6-2e26-11e8-9981-1de52b8d07a8.png)
