### ISSUE TITLE
Cannon overcharged missing

### ISSUE THREAD

**Issue by Javelias** [msarilar/EDEngineer#349]
Downloaded latest version to be sure. Still an issue.

See https://inara.cz/galaxy-blueprint/47/

**Comment by msarilar** [comment]
they're here 
![image](https://user-images.githubusercontent.com/5569959/37877133-af2c5e96-3056-11e8-85f8-29391fa97a65.png)

**Comment by Javelias** [comment]
Thanks, I checked again and somehow I had them on Ignore filter. Sorry for the inconvenience, great features and bugfixes you are doing !
