### ISSUE TITLE
FSDI Long Range G4

### ISSUE THREAD

**Issue by Big-Gaz** [msarilar/EDEngineer#350]
Frame Shift Drive Interdictor Long Range Grade 4 doesn't seem to be included.

**Comment by msarilar** [comment]
yeah it is 
![image](https://user-images.githubusercontent.com/5569959/37879464-d8d1c588-3079-11e8-9e4f-3c730ea0a176.png)

**Comment by msarilar** [comment]
Thanks for reporting!

Feel free to update the blueprints file I curated for the application : https://github.com/msarilar/EDEngineer/blob/master/EDEngineer/Resources/Data/blueprints.json
You'll see that it's a simple array of objects separated by commas, and they're pretty straightforward:

  {
    "Type": "Plasma Accelerator",
    "Name": "Short Range Blaster",
    "Engineers": [
      "Zacariah Nemo",
      "Bill Turner"
    ],
    "Ingredients": [
      {
        "Name": "Modified Consumer Firmware",
        "Size": 1
      },
      {
        "Name": "Nickel",
        "Size": 1
      },
      {
        "Name": "Insulating Membrane",
        "Size": 1
      }
    ],
    "Effects": [
      {
        "Effect": "+27%",
        "Property": "Damage",
        "IsGood": true
      },
      {
        "Effect": "-10%",
        "Property": "Maximum Range",
        "IsGood": false
      }
    "Grade": 2
  }
You just have to be careful with the names (ingredients, type, engineers) and use the exact same as other blueprints (same casing, no dashes etc..)

**Comment by Big-Gaz** [comment]
Changes made - hope they're ok!!

**Comment by msarilar** [comment]
I don't see the changes, you need to edit the file and then open a pull request

https://help.github.com/articles/editing-files-in-another-user-s-repository/

**Comment by Big-Gaz** [comment]
I don't think I did the pull request - I've never used GitHub before!

I'll try again later when I'm back from work.

**Comment by Big-Gaz** [comment]
Pull request done.

**Comment by msarilar** [comment]
https://github.com/msarilar/EDEngineer/pull/351
