### ISSUE TITLE
Guardian/Human Tech commodities missing

### ISSUE THREAD

**Issue by Javelias** [msarilar/EDEngineer#352]
For example, Guardian Power Plant does not mention the 10 Energy Grid Assembly. Noticed the same issue with Remote Flechette Fixed not mentioning the 8 CMM Composites.

See https://inara.cz/galaxy-techbroker/.

**Comment by msarilar** [comment]
yes, edengineer doesn't track commodities anymore (since they were removed from regular blueprints)
one day I might add them back again but until then it won't show up in any recipe

**Comment by Javelias** [comment]
Ok, do you think it is a good idea to add a warning text to the tech broker blueprints ?

It might save people by not making them think too soon they can go dock and unlock tech.

**Comment by msarilar** [comment]
I've added the warning for now, maybe I'll add the commodities back again :)
