### ISSUE TITLE
v1.1.0.8 Shopping list sync failure

### ISSUE THREAD

**Issue by awdwyn** [msarilar/EDEngineer#354]
Loving the new shopping list format!

I just started working on engineering and did a burst laser (g5 efficient with phasing) which reduced the blueprint counts in the shopping list perfectly (regular blueprints and experimental) but now doing a long range with thermal vent on a beam laser I've got a problem.

The long range doesn't reduce in the shopping list, but the thermal vent does.

Relevant log entry:
`{ "timestamp":"2018-03-28T16:26:39Z", "event":"EngineerCraft", "Slot":"HugeHardpoint1", "Module":"hpt_beamlaser_fixed_huge", "Ingredients":[ { "Name":"sulphur", "Count":1 } ], "Engineer":"Broo Tarquin", "EngineerID":300030, "BlueprintID":128673335, "BlueprintName":"Weapon_LongRange", "Level":1, "Quality":1.000000, "Modifiers":[ { "Label":"Mass", "Value":17.600000, "OriginalValue":16.000000, "LessIsGood":1 }, { "Label":"PowerDraw", "Value":2.688300, "OriginalValue":2.610000, "LessIsGood":1 }, { "Label":"MaximumRange", "Value":3600.000244, "OriginalValue":3000.000000, "LessIsGood":0 }, { "Label":"DamageFalloffRange", "Value":3600.000244, "OriginalValue":600.000000, "LessIsGood":0 } ] }
`

![capture](https://user-images.githubusercontent.com/23404043/38043028-219a0866-3273-11e8-80c7-36b61f2dfa10.PNG)

**Comment by msarilar** [comment]
thanks for reporting and kudos for including the log, that's very helpful

however the log you provided is the G1 roll which seems to be working fine when I try myself; was the problem on another grade instead?

**Comment by awdwyn** [comment]
All grades of the beam laser long range failed. I did two and both were the
same.

**Comment by awdwyn** [comment]
Here's the whole log.  Engineering started on line 74

[Journal.180328092446.01.log](https://github.com/msarilar/EDEngineer/files/1856873/Journal.180328092446.01.log)

**Comment by awdwyn** [comment]
I have two railguns to engineer, so i'll go do one, the relaunch edengineer and do the second and report back.

**Comment by msarilar** [comment]
I see, it actually reduced your shield cell bank counter

**Comment by msarilar** [comment]
https://github.com/msarilar/EDEngineer/commit/9ab3072cc5e8ccd8cb434f650d64abf1e2c54abe

**Comment by msarilar** [comment]
the reason was because I was using a wrong field from the journal log to find the matching blueprint so the code falls back to the first blueprint which has the same ingredient and it got the SCB G1 blueprint

**Comment by awdwyn** [comment]
Ahh ok good find. Thanks!

**Comment by msarilar** [comment]
no worries ; it's much easier to find issues when screenshot and log are provided 🙂 
fix has been deployed
