### ISSUE TITLE
installation of newest version (1.1.1.0) destroys ALL user prior configuration

### ISSUE THREAD

**Issue by rdslw** [msarilar/EDEngineer#356]
As in subject.

All shopping lists and settings are gone. 
All favourite/ignored blueprints are gone.

:-(

**Comment by msarilar** [comment]
if you had FSD interdictors related blueprints in your favorites and shopping list, they were indeed lost ; but other blueprints should not have had been affected

not exactly sure what went wrong for you but you might have something that deleted your config (should be stored in `C:\Users\%USERNAME%\AppData\Local\EDEngineer` or `C:\Users\%USERNAME%\AppData\Roaming\EDEngineer`

**Comment by rdslw** [comment]
everything was affected including shortcut i was using (i had a different one).

I suspect a bug, as it went like this:
1. windows off (EDEngineer works ok, all settings are intact)
2. windows on, I manually start EDEnginer
3. Automatic EDEngineer Update 
4. After update I'm being asked configuration questions: voice and that it can not find ED logfile (I have ED installed in non default folder)
5. I answer questions from 4, EDEngineer starts but with clean settings.
