### ISSUE TITLE
Missing Commodities filter showing blueprints with no commodity requirement

### ISSUE THREAD

**Issue by Athanasius** [msarilar/EDEngineer#36]
Using Craftable Filter > Missing Commodities I see things like Grade 3 Heat Sink Launcher despite it showing as 100% craftable, presumably because its requirements include no commodities.  Similarly for any Grade 1 blueprint.

**Comment by msarilar** [comment]
Well spotted ! https://github.com/msarilar/EDEngineer/commit/6b66e7ad21399faca1824c18cc1233a186844d1b
