### ISSUE TITLE
EDEngineer not refreshing inventory

### ISSUE THREAD

**Issue by sebaspitt** [msarilar/EDEngineer#364]
Hi,

I've noticed that last version not longer update material/data inventory in the "live" way it used to.

Regards!

**Comment by dyfron** [comment]
Same here. I am collecting guardian stuff and it doesn't update those.
After a restart it is updated.

**Comment by msarilar** [comment]
if you delete a random material that you don't care about, its number doesnt change in the app?

**Comment by dyfron** [comment]
I cannot delete a random material, but if I synthesize ammo reload in the SRV, EdEngineer doesn't update the iron and the nickel.
After restart of EdEngineer, it's correct again.

**Comment by msarilar** [comment]
found it ; was linked to the asynchronous loading (splash screen)

**Comment by dyfron** [comment]
Congrats :)
