### ISSUE TITLE
Max storage

### ISSUE THREAD

**Issue by dyfron** [msarilar/EDEngineer#368]
The max storage for "Pattern alpha/beta/delta/gamma/epsilon obelisk data" should be 150 for all of them.

**Comment by msarilar** [comment]
thanks for reporting, I hotfixed this

**Comment by dyfron** [comment]
But now the bars make no sense
![pattern](https://user-images.githubusercontent.com/25774620/38507349-9869e850-3c1c-11e8-9124-41cea9ed9984.jpg)

**Comment by msarilar** [comment]
indeed! should be alright now

**Comment by dyfron** [comment]
Check !  :)
