### ISSUE TITLE
Feature Request: Updated Labeling, Mat Trader Exchange, Mass Mat Locations

### ISSUE THREAD

**Issue by lexsan82** [msarilar/EDEngineer#370]
Excellent program!

With the crafting update it is far easier to understand the attempts as rolls and not crafting individual items.

Please update the CAN CRAFT X label to read X ROLLS, and in the shopping list the + - should be tracking the number of roll attempts as opposed to individual pieces crafted. This would make a lot more sense.

Also, please add a Material Trader Exchange much like the one found on INARA. I would like to consolidate to just using EDENGINEER, but this information is a must have.

Finally, please add an icon next to the items that can be found at the crashed Anaconda in Orrere and a separate icon for materials at Dav's Hope, as well as any other known en mass material locations.

Thanks!

**Comment by msarilar** [comment]
By MTE you mean the locations of traders here ? https://inara.cz/galaxy-nearest/25/2821/

Don't know about the new materials in Orrere and other ; if the application doesn't recognize them it should tell you when you hover the material to report the missing information to GitHub (what you see in the GUI + what it is in the game + its rarity and type).

**Comment by lexsan82** [comment]
For the MTE, take a look at the Cargo and Crafting section. You can add blueprints to craft in the Crafting List section, and it will show you the materials that you don't have. You can then click Missing Components and it will tell you what you can use to trade (out of your inventory) to get the required number of materials for what you are crafting.

**Comment by lexsan82** [comment]
Also, about the Dav's Hope/Crashed Anaconda - so these are basically locations that have material spawns at a specific site. They drop a wide range of materials, and are particularly easy to farm because you can exit to menu and re-enter the game and the materials will spawn again. I was suggesting that there be an indicator of which materials can be found at these unique spawn sites, in addition to their usual way of acquisition. Here is forum post regarding the materials that can be found at Dav's Hope: https://forums.frontier.co.uk/showthread.php/354425-List-of-goodies-at-Dav-s-Hope
