### ISSUE TITLE
EDEngineer Client updates on each start up

### ISSUE THREAD

**Issue by Pootch** [msarilar/EDEngineer#372]
v1.1.1.11

Each time I start the edengineer client it tells me that there is an update available.

**Comment by msarilar** [comment]
have you installed the app using the setup.exe linked on the project home page? or did you download the project with the green Download button

https://cdn.rawgit.com/msarilar/EDEngineer/master/EDEngineer/releases/setup.exe

**Comment by msarilar** [comment]
The app should show 1.1.1.11 but the real version is 1.1.1.20 (I don't put a new version nor release notes for small hotfixes)

if you go to `Control Panel\Programs\Programs and Features`, you should see the real version of EDEngineer there ; make sure you have the real latest one

apart from that I don't really know what could trigger that. you might have some logs in your event viewer (see https://github.com/msarilar/EDEngineer/issues/310#issuecomment-370152359 for how to view them) but I doubt it.

you could try to reinstall too and see if the problem persists ; let me know if you find anything

**Comment by Pootch** [comment]
All right.. I have checked the version at the control panel.. it is the latest.
thanks for help..

**Comment by msarilar** [comment]
are you part of the windows insider program? a recent patch was rolled out and it could be linked to the issue

**Comment by Pootch** [comment]
nope no insider builds
