### ISSUE TITLE
error after upgrading to v1.1.1.21

### ISSUE THREAD

**Issue by eyalr1** [msarilar/EDEngineer#375]
after upgrading to v1.1.1.21 ,running the app it throes an error

![image](https://user-images.githubusercontent.com/38360134/38749268-af64ea74-3f59-11e8-8e86-5ef7c750d043.png)

-see insluded picture link
-the error didn't exits in last version when run yesterday.
-the error is about several guardian modules but also for manganese.

**Comment by msarilar** [comment]
thanks for reporting, I've hotfixed it
