### ISSUE TITLE
error when running version v1.1.1.21

### ISSUE THREAD

**Issue by eyalr1** [msarilar/EDEngineer#376]
![image](https://user-images.githubusercontent.com/38360134/38750405-7ec708ee-3f5d-11e8-892b-974b4362f0f8.png)

just got updated client (following your hotfix for this issue) -> version still shows same as last one v1.1.1.21 and the above error remains.

**Comment by msarilar** [comment]
that's a different one, there seems to be some divergence/weird incompatibility in the game logs (frontier updated the journal I guess)

should be fixed now

**Comment by msarilar** [comment]
I don't put a new version nor release notes for small hotfixes

if you go to `Control Panel\Programs\Programs and Features`, you should see the real version of EDEngineer there ; make sure you have the real latest one

**Comment by eyalr1** [comment]
good to know , indeed i can see the correct version in 1.1.1.24
thanks for the quick fix
