### ISSUE TITLE
Engineering Collector Limpets SYNC's Shopping List with Prospector Limpet

### ISSUE THREAD

**Issue by badbud65** [msarilar/EDEngineer#377]
I have LIGHTWEIGHT Collector and Prospector Limpets in my Shopping list for Grade 3 to Grade 5 and SYNC is selected. When I Upgrade the Collector Limpet Controller the number remaining is taken from Prospector Limpet Controller.

[Journal.180414032515.01.log](https://github.com/msarilar/EDEngineer/files/1909942/Journal.180414032515.01.log)

![2018-04-14_0332](https://user-images.githubusercontent.com/4669127/38763470-766b86d4-3f94-11e8-9a90-214f7beafa0b.png)

**Comment by msarilar** [comment]
thanks for the logs! will be in next hotfix
4eac7ae55926f6e66bb1b4bee875b01370b21d35
