### ISSUE TITLE
message d'erreur à l'ouverture

### ISSUE THREAD

**Issue by Giblood** [msarilar/EDEngineer#380]
![capture error 1](https://user-images.githubusercontent.com/23616232/38864503-36671b1c-423b-11e8-954c-c4c42784f8e0.JPG)
![capture error 2](https://user-images.githubusercontent.com/23616232/38864513-3b49cb7a-423b-11e8-8993-045f4e8cab26.JPG)

**Comment by msarilar** [comment]
this error has already been fixed, make sure you're using the latest version

the application should show 1.1.1.21 and if you go to `Control Panel\Programs\Programs and Features` you should see the *real* version which is 1.1.1.25 (I don't always update the application version/release notes when I publish a hotfix)
