### ISSUE TITLE
FUBAR?

### ISSUE THREAD

**Issue by dyfron** [msarilar/EDEngineer#384]
[EDEngineer.zip](https://github.com/msarilar/EDEngineer/files/1952313/EDEngineer.zip)

This is a real mess.
First I noticed almost all figures are wrong.
so I corrected everything by hand.
Now I am upgrading some burst lasers at Broo and the numbers just don't update while upgrading.

**Comment by msarilar** [comment]
could you screenshot the EDEngineer window, upload your log as well as the aggregate.json file in `C:\Users\%USERNAME%\AppData\Roaming\EDEngineer`?

**Comment by msarilar** [comment]
ah right for some reason the periodic refresh of the log files got lost in latest update so the app was never notified of any changes in game

should be all right by now

**Comment by dyfron** [comment]
Thanks
