### ISSUE TITLE
[Feature Request] Sort Shopping List & more

### ISSUE THREAD

**Issue by Pootch** [msarilar/EDEngineer#388]
Hi.
First of all, thanks for the great tool.

I got two feature requests:

- **Sort shopping list for missing materials, data.** 
Would be cool to see the missing materials, data, raw at the very top.

- **Rename raw materials to RAW or ELEMENTS (current it's called MATERIAL) in the shopping list**

Thanks a lot.

**Comment by msarilar** [comment]
published in 1.1.2.2
