### ISSUE TITLE
Doesnt show anymore after last patch

### ISSUE THREAD

**Issue by Alekhoff** [msarilar/EDEngineer#39]
The window doesnt show up anymore no matter what i do...

**Comment by Alekhoff** [comment]
I am on Windows 10 Pro 64bit

**Comment by msarilar** [comment]
Do you see the icon in the task tray ? You can unlock the window if you right click on it, and you should find it again.

**Comment by Alekhoff** [comment]
Yes i can see it in the system tray, but when i click "toogle window mode" it appears for a milli second on the screen then it dissapers again. I cant bring it to the front or find it. Restarting does not help!

**Comment by msarilar** [comment]
Are you using a multiscreen setup? If yes, Windows Key combined with Arrows (Left, Right, Up, Down) can move it from hidden places. You might have to combine these with Shift key (like Windows Key + Shift + Left) if that doesn't do it.

**Comment by puuhbear** [comment]
shift rightclick the icon in the taskbar and click "move" 

then use arrow keys

that helped me :)

**Comment by Alekhoff** [comment]
Thanks @puuhbear that worked! 
Thanks @msarilar aswell for that fast support! Great app!

**Comment by msarilar** [comment]
great ! 🎉

**Comment by Alekhoff** [comment]
btw saw that all my materials and data is totaly wrong now, allmost all of the are in negative even tho i didnt use any since i last started the app. Is there a way to fix ?

**Comment by puuhbear** [comment]
same here :/

**Comment by msarilar** [comment]
Can you guys check the content of directory `C:\Users\%USERNAME%\AppData\Local\EDEngineer` ? what do you see?

**Comment by Alekhoff** [comment]
https://i.imgur.com/6yjY5b2.png

**Comment by msarilar** [comment]
Could you double check if the correct folder is picked in EDEngineer ? (the dark cyan path at the bottom of the window)

**Comment by Alekhoff** [comment]
Seems like it has two profiles now in EDEgineer:
https://i.imgur.com/Z6n7bEG.png
https://i.imgur.com/Q2QX5JL.png

**Comment by puuhbear** [comment]
wich one is the correct one?

**Comment by Alekhoff** [comment]
you can see the difference in the materials list on those pictures, but it started taking all the changes from the log file into the CMDR Alekhoff, when CMDR Default has all the original data

**Comment by msarilar** [comment]
Ok I see. I'm going to check what's wrong with the migration.

In the meantime, please stop the application, rename the file from "manualChanges.Default.json" to "manualChanges.Alekhoff.json" (or whatever your cmdr name is), and start the app again.

**Comment by Alekhoff** [comment]
Yeah, that seemed to fix it! 
Thanks 😃

**Comment by msarilar** [comment]
Could you upload a zip file of your log folder?

**Comment by Alekhoff** [comment]
where is it located ?

**Comment by puuhbear** [comment]
noe all my data is gone after renaming it to Puuhbear

**Comment by msarilar** [comment]
@Alekhoff  `C:\Users\%USERNAME%\Saved Games\Frontier Developments\Elite Dangerous`

@puuhbear it's case sensitive ; check any file in `C:\Users\Max\Saved Games\Frontier Developments\Elite Dangerous`, you should see a line like :

`{ "timestamp":"2016-11-10T21:58:33Z", "event":"LoadGame", **"Commander":"Hg"**, "Ship":"Federation_Corvette", "ShipID":3, "GameMode":"Solo", "Credits":256175789, "Loan":0 }`

Here, "Hg" is my cmdr name

**Comment by puuhbear** [comment]
didn't help Last Updated says: Mininstant

**Comment by Alekhoff** [comment]
Have tried making a zip with 7Zip and Winrar, Github tells me it doesnt support it even tho ZIP is a supported file type.

**Comment by msarilar** [comment]
@puuhbear what do you see in the log directory (dark cyan bottom right of the app) ?

@Alekhoff rename the .zip as .jpg, it will work

**Comment by Alekhoff** [comment]
![elite dangerous](https://cloud.githubusercontent.com/assets/4733271/20200581/41ec84c4-a7b2-11e6-939c-f59b244faaca.jpg)

lol

**Comment by puuhbear** [comment]
https://dl.dropboxusercontent.com/u/9641105/EDEngineer_2016-11-11_01-58-11.png

**Comment by Alekhoff** [comment]
@puuhbear you have the wrong profile selected

**Comment by Alekhoff** [comment]
https://i.imgur.com/GVFWAWw.png

**Comment by msarilar** [comment]
@Alekhoff thanks, I see what's wrong. shit log outputted by the game not containing anything but stuff like 

`{ "timestamp":"2016-11-06T01:54:50Z", "event":"Fileheader", "part":1, "language":"English\\UK", "gameversion":"2.2", "build":"r125374/r0 " }`

which messes up the profiles. I'll push a patch asap hoping not many users encounter the same issue

**Comment by Alekhoff** [comment]
Ah, nice! 

Good thing you found the problem so quickly!

**Comment by puuhbear** [comment]
jesus... thanks... I didn't even see that before xD

I feel so stupid now :)

great work!

**Comment by msarilar** [comment]
Just pushed the hotfix. Thanks guys for reporting the issue so soon! 

Remember, your manual changes are never ever lost unless you delete the manualChanges.json file

If you both restart, you should not see that pesky "CMDR DEFAULT" on top. That display is only for users playing with multiple accounts :)

**Comment by Alekhoff** [comment]
Thanks @msarilar 

You are doing amazing work with this app!

**Comment by Alekhoff** [comment]
btw i can still see CMDR Default after the patch

**Comment by puuhbear** [comment]
me too

**Comment by msarilar** [comment]
well that should do it now :D
some file logs are really weird. I don't even know what they're supposed to represent :/

**Comment by Alekhoff** [comment]
awesome!

**Comment by puuhbear** [comment]
fantastic! \o/

**Comment by msarilar** [comment]
On a side note, I think there's a pretty big bug on Frontier's side regarding some logs. @Alekhoff Can I use some of your logs to file a bugreport ? Low chance of seeing it fixed but we never know...

**Comment by Alekhoff** [comment]
yeah no problem at all!

**Comment by msarilar** [comment]
cheers!
