### ISSUE TITLE
Most recent version fails to upgrade or install on Windows 10 most recent version

### ISSUE THREAD

**Issue by Gerdofal** [msarilar/EDEngineer#390]
The most recent version will not install at all. Briefly pops up a window "Verifying Application Requirements..." which then disappears.

This happened when I tried to update existing version as well as when I uninstalled and tried to install fresh.

**Comment by Gerdofal** [comment]
Note: This is as of a Windows update that installed today.

**Comment by Gerdofal** [comment]
Windows 10 Pro
10.0.17134 Build 17134

**Comment by msarilar** [comment]
yeah the latest Windows update seemed to have broken something

until I figure out if it's an issue with the app or Windows itself, please check this out https://github.com/msarilar/EDEngineer/issues/371#issuecomment-385653808

**Comment by MrVaad** [comment]
It seems the app is not considered safe by windows 1803 (i get a security popup when launching the exe from the install directory). If i look at the edEngineer.exe properties, there is a problem with the SSL certificate, it can't find the root certificate.
----------------------------------------------------------------------------------------------------------
The solution that worked for me :
To avoid disabling the smartscreen (which is not recommended), you have to launch edEngineer.exe from its folder one time (just do a search in the C:\Users\ directory as Mattpenfold did in the #371 ) .
A security warning will pop, you just have to confirm that you want to launch the app.

After that, you'll be able to launch the app with the shortcut.

Also, don't use the exe all the time. It seems edengineer's settings aren't stored in the same place when using the shortcut or the exe.

**Comment by msarilar** [comment]
closing this one as there's all details in #390
