### ISSUE TITLE
[Request] synthesis items for AX and Guardian weapons

### ISSUE THREAD

**Issue by Tigir** [msarilar/EDEngineer#392]
The AX/Guardian weapon synthesis items are missing. Could we get those included, please?

**Comment by msarilar** [comment]
please check this wiki page to see how to contribute :
https://github.com/msarilar/EDEngineer/wiki/Contributing

**Comment by Tigir** [comment]
Ok, working on it. 
Putting it all into the json format when I can work on it with my schedule.

**Comment by Tigir** [comment]
Done.

[blueprints.zip](https://github.com/msarilar/EDEngineer/files/1970574/blueprints.zip)

**Comment by Tigir** [comment]
I tried that, said I didn't have the permission?
Will try again.

**Comment by Tigir** [comment]
Yay, success, pull request in.

**Comment by msarilar** [comment]
thank you!

https://github.com/msarilar/EDEngineer/pull/393
