### ISSUE TITLE
Shopping list scrollbar not big enough when shopping list is extended further upwards than possible

### ISSUE THREAD

**Issue by MaximumWoahverdrive** [msarilar/EDEngineer#397]
As the title says the scrollbar thinks the shopping list has been extended further than it actually is when pulling it too far up (past the point to which it actually goes)
this happens in windowed, maximized and locked mode
[video demonstrating this](https://youtu.be/GyF9z-iV6Ms)

**Comment by msarilar** [comment]
thanks for the report and the video!

I don't think the problem matters that much to be honest (also it seems to be the standard behaviour for a grid splitter within a grid in WPF), better to spend time on other things 😉
