### ISSUE TITLE
Multi Commanders Missing

### ISSUE THREAD

**Issue by sollisb** [msarilar/EDEngineer#399]
Im running 3 Accounts.. EDEngineer used to show active commander now it doesnt?

Where is it installed to? 

Documentation available for server?

As its WPF would be nice to have UI scaling?

KUTGW!

**Comment by msarilar** [comment]
> EDEngineer used to show active commander now it doesnt?

you should get them back if you delete the aggregation.json file (in your AppData/Roaming/EDEngineer folder) but obviously they should not have disappeared
