### ISSUE TITLE
1.0.0.30 Overlay is blank

### ISSUE THREAD

**Issue by VoggixHavenwhite** [msarilar/EDEngineer#40]
Title - after updating to 1.0.0.30 the application is a blank black screen.  Tried restarting app and game.

**Comment by msarilar** [comment]
what happens if you unlock the window via the icon in the task tray?

**Comment by msarilar** [comment]
I've added a "Reset Window" command in the tasktray icon, check it out!

**Comment by VoggixHavenwhite** [comment]
I had indeed tried the lock/unlocknin the tray to to avail. 

However the new "Reset Window Position" worked perfectly!!!

Thanks for this great tool!!
