### ISSUE TITLE
THARGOID CARAPACE Max Amount Incorrect

### ISSUE THREAD

**Issue by badbud65** [msarilar/EDEngineer#400]
Currently THARGOID CARAPACE capacity is set at 100, when it is actually 250

![thargoid_carapace](https://user-images.githubusercontent.com/4669127/39761121-20cdd490-52cf-11e8-9ce2-6e1f97134f46.png)

**Comment by msarilar** [comment]
thanks for the report, fixed in https://github.com/msarilar/EDEngineer/commit/f0ae054f408ba70d84a580a57662c4a2f2f6793d
