### ISSUE TITLE
Shield Cell Bank no Grade 4

### ISSUE THREAD

**Issue by Pootch** [msarilar/EDEngineer#402]
According to Inara there are grade 4 Upgrades available.
EdEngineer only shows Grade 1-3

https://inara.cz/galaxy-blueprint/17/
https://inara.cz/galaxy-blueprint/18/

**Comment by msarilar** [comment]
if the recipes exist in game (please check as there's been a certain number of blueprints in inara that don't exist in game), then feel free to add it to the blueprint.json file :)

https://github.com/msarilar/EDEngineer/wiki/Contributing
