### ISSUE TITLE
Problem loading the App.

### ISSUE THREAD

**Issue by LazyCalf** [msarilar/EDEngineer#404]
Hi, i have a problem with loading up the edengineer. it used to work fine but now it just doesn't load up. i uninstalled it and reinstalled it, excluded it from my anti virus software, uninstalled my anti virus, you name it i've tried it.
downloading the setup works fine, installing the actual app seems to work fine, i download the app and go to launch it, and it just, doesn't.
 when i go to launch the app, i get a small box saying "verifying application requirements" that lasts for a split second, then the app doesnt launch, its not in task manager, and i cant seem to find it in the event viewer either.
any solutions?

**Comment by msarilar** [comment]
yeah it's a known issue with the latest Windows update, see this : https://github.com/msarilar/EDEngineer/issues/371#issuecomment-385653808 and this https://github.com/msarilar/EDEngineer/issues/390#issuecomment-386174152
