### ISSUE TITLE
Can't add experimentals to shopping list

### ISSUE THREAD

**Issue by sporebat** [msarilar/EDEngineer#406]
Latest version, after solving the Windows launch problem

**Comment by msarilar** [comment]
seems like the same issue as this one : https://github.com/msarilar/EDEngineer/issues/378

could you check this out?

**Comment by sporebat** [comment]
I'm not getting a crash: rather, the + button is missing.

**Comment by sporebat** [comment]
![image](https://user-images.githubusercontent.com/23209850/40276215-911e9b86-5c47-11e8-94c2-2bbe52137d6b.png)

**Comment by msarilar** [comment]
I see, it's your window that is too small to make the left end of the panel appear (engineer list and shopping list button)

you either need to resize the entire window or make the right side panel bigger using the vertical splitter in the middle (the one that splits the blueprint/shopping list on the right and the ingredient list on the left)
