### ISSUE TITLE
Electrochemical Arrays is listed as G2 but is G3

### ISSUE THREAD

**Issue by Fersoltil** [msarilar/EDEngineer#410]
no biggie, but still

**Comment by Josemaloco** [comment]
That was due to the [Bonus weekend](http://elite-dangerous.wikia.com/wiki/Bonus_Weekend)

**Comment by msarilar** [comment]
it seems the ingredient is G3 in the application:
![image](https://user-images.githubusercontent.com/5569959/40779329-d357d73e-64d4-11e8-9d5c-4a05af6b837e.png)

are we talking about the same thing?
