### ISSUE TITLE
EDEngineer Recipes not correct 

### ISSUE THREAD

**Issue by Tonyfun** [msarilar/EDEngineer#412]
I've noticed while i've been using EDEngineer that the recipes have changed in game but EDEngineer are using the old recipes...
For Example:
Power Plant Over Charged LV3 for MARCO QWENT should be:
Heat Conduction Wiring / Basic Conductors / Tin

However EDEngineer is showing that it needs:
Heat Conduction Wiring / Conductive Components / Gelenium

Also noticed other mis matches like this:
Increased FSD Range LV5 for FELICITY FARSEER should be:
Rhenium / Chemical Distillery / Eccentric Hyperspace Trajectories

However EDEngineer is showing that it needs:
Arsenic / Chemical Manipulators / Data Mined Exceptions

Any Ideas???

Screenshots can be seen here:
![edengineer screenshot](https://user-images.githubusercontent.com/4711350/40630730-0876bbec-62cd-11e8-98af-fecaad1ddf6a.jpg)
![fsd elite screenshot](https://user-images.githubusercontent.com/4711350/40630731-0d8977fa-62cd-11e8-8fbb-340266e58060.jpg)
![power plant screenshot](https://user-images.githubusercontent.com/4711350/40630734-106932d0-62cd-11e8-81d8-758e71d46f2b.jpg)

**Comment by daveglw** [comment]
its the same for efficient beam laser and multi cannons incorrect recipes

**Comment by Josemaloco** [comment]
The event is over but maybe this should be taken into account. 

Personally I would opt for the more broad option of the ability of adding mats into the shopping list (maybe a different shopping list than the one for blueprints?). This could cover future, short events, and allow a bit more flexibility overall.

**Comment by msarilar** [comment]
this is a good idea, I'll try and add a way to create artificial blueprints that you can add to your shopping list
