### ISSUE TITLE
Blueprint sorting

### ISSUE THREAD

**Issue by Josemaloco** [msarilar/EDEngineer#413]
It would be nice if sorting in the blueprints panel would follow some simple rules, so it would automatically sort by more than 1 column.

For example, when you sort by Type, usually you are interested in seeing the column Name ordered too, and then by grade, so instead of the semingly random order of the other columns, you had something like:

```
G   TYPE        Name
1   Armour    Blast Resistant
2   Armour    Blast Resistant
3   Armour    Blast Resistant
4   Armour    Blast Resistant
5   Armour    Blast Resistant
1   Armour    Heavy Duty
2   Armour    Heavy Duty
... More Armour blueprints
5   Armour    Thermal Resistant
1   Sensors    Light Weight Scanner
2   Sensors    Light Weight Scanner
...
```

The flow of priority when sorting columns could be "Type -> Name -> Grade ~> Type...", so if you sort by Type, then it would sort by Name and then Grade. If you sort by Grade, it would go back to sort by Type, and then Name.

**Comment by msarilar** [comment]
https://github.com/msarilar/EDEngineer/commit/a879af1681843af7b40fc539bd1aaf14641eebea
