### ISSUE TITLE
Allow adding items to the shopping list from API

### ISSUE THREAD

**Issue by willyb321** [msarilar/EDEngineer#415]
Was thinking about adding a "add recipes to edengineer" button to Coriolis but as far as I can tell the API doesn't support modifying shopping list.

**Comment by msarilar** [comment]
sounds like a good idea, we just need to settle with a way to identify blueprints individually:
* an shared unique identifier (incremental, guid, ...) : this doesn't exist in EDEngineer (yet) but shouldn't be much trouble to implement, just a bit tedious. if Coriolis has ones for blueprints already, we can use them here as well
* identify with the name of the blueprint and its type : already exists in EDEngineer but a minor difference of names between different apps would cause mismatches

regarding implementation, it's probably going to be an [`HTTP PATCH`](https://tools.ietf.org/html/rfc5789) call to the API with a [`204`](https://developer.mozilla.org/en-US/docs/Web/HTTP/Methods/PATCH) response if succeeded (failure would be `404 blueprint not found` or `422` when trying to remove blueprints from the shopping list that isn't in there)

**Comment by willyb321** [comment]
Coriolis has IDs for all the blueprints [here](https://github.com/EDCD/coriolis-data/blob/master/modifications/blueprints.json)

**Comment by willyb321** [comment]
Actually looking at it again - I'll add a per grade GUID for each blueprint.

**Comment by willyb321** [comment]
UUIDs added https://github.com/EDCD/coriolis-data/blob/develop/modifications/blueprints.json

**Comment by msarilar** [comment]
here's a sample query for `PATCH` in C#:

```csharp
var url = "http://localhost:44405/CommanderName/shopping-list";

using(var client = new HttpClient())
{
	var method = new HttpMethod("PATCH");
	var content = new MultipartFormDataContent();
	content.Add(new StringContent("fe30a1a0-3644-4411-af1f-59bae0a565b9"), "uuid");
	content.Add(new StringContent("1"), "size");
	var request = new HttpRequestMessage(method, new Uri(url))
	{
		Content = content
	};
	
	client.SendAsync(request).Result.Content.ReadAsStringAsync().Result.Dump();
}
```

beware that some blueprints share the same Guids for a given modification (generic ones that are shared by some weapons)

**Comment by willyb321** [comment]
I have started to work on integrating this to coriolis, but there doesn't seem to be an `Access-Control-Allow-Origin: *` header on the API, which breaks browser since a request to the API is considered to be CORS. In theory just adding that header to all API responses should be sufficient. Thanks.

**Comment by msarilar** [comment]
you're right, I was sure the header was here when I added the [CORS config](https://github.com/msarilar/EDEngineer/blob/master/EDEngineer.Server/Server.fs#L70) but it's missing

should be trivial to add the header, I'll do that tonight

**Comment by msarilar** [comment]
should be fine now, let me know if there's any other issues

**Comment by willyb321** [comment]
Looks like the preflight OPTIONS request is failing with a 404.

**Comment by msarilar** [comment]
what GUID are you using?

**Comment by msarilar** [comment]
Is that something you're going to require or can we do without?

**Comment by msarilar** [comment]
well anyway I've added a basic handling of OPTIONS requests here : https://github.com/msarilar/EDEngineer/commit/bc1ba362f13d8fe4369ca1d73a300608e4fafec6

let me know if that's good enough ;)

**Comment by willyb321** [comment]
Oof, looks like you'll need to add `Access-Control-Allow-Methods` to have PATCH in it as well.

**Comment by willyb321** [comment]
Hmm, not sure why it's still not working. 
https://willb.info/images/2018/06/27/chrome_2018-06-27_05-47-27.png
https://willb.info/images/2018/06/27/chrome_2018-06-27_05-47-35.png

**Comment by willyb321** [comment]
Oh! It's Access-Control-Allow-Method**s**

**Comment by msarilar** [comment]
yeah missing `s` I also just spotted hit 😔

**Comment by msarilar** [comment]
should be fine now, sorry about that

**Comment by willyb321** [comment]
Yep, looks like it's all working fine now. Will deploy this to Coriolis. Thanks!
