### ISSUE TITLE
Feature Request: Engineer system location with the name in the mod panel

### ISSUE THREAD

**Issue by Sheuzzo** [msarilar/EDEngineer#416]
As in the topic :D at the moment when i click a mod i get the name of the engineer, i have to look for it's location in the engineer panel in game or inara and then go to him. It would be nice to have straight the system name and even more nice to be able to copy the name of the system to the clipboard clicking it

**Comment by msarilar** [comment]
9e0294b97c74494a4f8b5a1c00274a95b5592c29
