### ISSUE TITLE
Avast stops EDEngi from launching

### ISSUE THREAD

**Issue by Swish777** [msarilar/EDEngineer#419]
So, after the recent update, EDEngi wouldn't open. I thought it might have been a W10 issue like it has been for others previously. So i went thorught he motions to sort it out. And I thought I had. But today when I tried to launch it, I got the "Application cannot be launched. Contact vendor" pop-up. I had a thought, that maybe it was my security, and it was. I disabled Avast, launched EDEngi and then re-enabled Avast. EDEngi works fine, it's just Avast being protective.

**Comment by msarilar** [comment]
does Avast give any detail?
scanning the binaries with https://www.virustotal.com shows Avast doesn't find anything

**Comment by Swish777** [comment]
No, there was no message yesterday from Avast, the only notifcation was the pop-up contact vendor. I looked in Avast there was nothing in there. I've had this, unable to launch, type situation come up with a few games and programs in the past, and it had been attributed to Avast. And there was no notfication or message of any kind. Hence my assumption that Avast was just being aggressive. 

I just tried launching EDEngi again just now, without disabling anything, it updated itself again, and it launched fine.

Well, now I feel foolish

**Comment by msarilar** [comment]
don't worry about it, the fact that EDEngineer is signed with a certificate of mine that is not verified by a third-party (like verisign) *and* that the update system uses ClickOnce (infamous for how it's sometimes maliciously used to install malware especially 10 years ago) can cause things to go wrong (AV check being one of them)

but all in all it's generally fine
