### ISSUE TITLE
Favourite blueprints are lost on update

### ISSUE THREAD

**Issue by Psieonic** [msarilar/EDEngineer#42]
Unsure if this is simply an issue with my client or a universal bug.  Update to 1.30 wiped my favourites.

**Comment by Athanasius** [comment]
Happened to me too with this latest update.  I was mostly wondering why after hitting the favourites button I had empty panes.

**Comment by msarilar** [comment]
yeah it was a one time only :/ won't happen again, but I should have given a warning in the release notes. sorry!

**Comment by msarilar** [comment]
I managed to salvage your old favorite and ignored blueprints ! If you want to make sure you're in the same state than before, just restart the application.

**Comment by Psieonic** [comment]
Holy crap that was fast dude!  I make an issue report, go to sleep for 6 hours then come back and new version.  XD  But fantastic, thanks for your hard work.  :D
