### ISSUE TITLE
Using coriolis ship builder beta with EDEngeneer - how do I start a new shopping list

### ISSUE THREAD

**Issue by mendocinotim** [msarilar/EDEngineer#427]
Using https://beta.coriolis.edcd.io/outfit/krait_mkii, I was able to send alist of required materials over to EDEngeneer. That was a great ability they added in coriolis. However, upon successive sends to EDE - because I started experimenting with different load-outs - I discovered the shopping list was being added to, and not getrting replaced. Of course this is not your fault.

However, I am unable to clear the shopping list from within EDE - even though I have pressed the reset button.. it is not emptying the shopping list so I can start a new one.

Any suggestions?

**Comment by msarilar** [comment]
the boxes represent a blueprint:
![image](https://user-images.githubusercontent.com/5569959/42147951-7de61bde-7dd0-11e8-8fe1-19657259a042.png)

click the red cross top right to remove the modification, or individually remove rolls using the `-` button

if you don't see the boxes, try to resize your window (either the entire window or the left/right panel ratio using the vertical splitter in the middle)

**Comment by mendocinotim** [comment]
Thank you - that's what I didn't understand before. Now I do, and everything is good.
Many thanks for the quick reply, and (more importantly) this program.
