### ISSUE TITLE
Possible issue with machine running in a Windows Domain.

### ISSUE THREAD

**Issue by msrhs** [msarilar/EDEngineer#43]
I have my PC joined to a Windows 2008R2 Server domain.

Firstly thank you for creating such a useful utility.

The manualChanges.my commander name.json file is being created and contains the manual changes. The commander name is correct. However the changes are lost when I close the app and restart. The app is pointing to the correct location on my drive but my username is in domain format ie logon name.domain. C:\logon name.domain\saved games\frontier developments\elite dangerous.

The string at the top of the screen is CMDR my commander name CMDR domain\appdata\local\edengineer\manualchanges.

I am happy to give you the exact strings, screen shots etc but not on an open server. See first few lines of the json file below.

{"timestamp":"2016-11-11T19:28:48Z","event":"ManualUserChange","Name":"Articulation Motors","Count":-1}
{"timestamp":"2016-11-11T19:28:49Z","event":"ManualUserChange","Name":"Articulation Motors","Count":-1}
{"timestamp":"2016-11-11T19:28:49Z","event":"ManualUserChange","Name":"Articulation Motors","Count":-1}
{"timestamp":"2016-11-11T19:28:50Z","event":"ManualUserChange","Name":"Articulation Motors","Count":-1}
{"timestamp":"2016-11-11T19:29:01Z","event":"ManualUserChange","Name":"Antimony","Count":1}
{"timestamp":"2016-11-11T19:29:01Z","event":"ManualUserChange","Name":"Antimony","Count":1}
{"timestamp":"2016-11-11T19:29:02Z","event":"ManualUserChange","Name":"Antimony","Count":1}
{"timestamp":"2016-11-11T19:29:03Z","event":"ManualUserChange","Name":"Antimony","Count":1}
{"timestamp":"2016-11-11T19:29:03Z","event":"ManualUserChange","Name":"Antimony","Count":1}
{"timestamp":"2016-11-11T19:29:08Z","event":"ManualUserChange","Name":"Antimony","Count":1}

**Comment by msarilar** [comment]
I'm starting to investigate, meanwhile could you take a look at this discussion starting from this comment : https://github.com/msarilar/EDEngineer/issues/39#issuecomment-259850737

Might shed some light on your issue

**Comment by msarilar** [comment]
Could you completely uninstall the application, delete the entire directory located in `C:\Users\%USERNAME%\AppData\Local\EDEngineer` and try to run `EDEngineer.exe` in this archive:
[Release.zip](https://github.com/msarilar/EDEngineer/files/586774/Release.zip) (won't install the application, just run it ; extract everything before).

let me know if that works ; if it does, I'll publish for other users who might be in the same situation as you

**Comment by msrhs** [comment]
Hello Max,

I will try that now.

Thank you.

--
Martin

**Comment by msrhs** [comment]
Hello Max,

I have unistalled the original install and deleted the edengineer directory. I extracted the realease.zip file and ran the executable. Next I entered my data for commodities and materials did not do data. The json file was created and updated as I went along. I exited the programme by right clicking on the running programmes and restarted. Both the commodites and materials have not updated and look as if they have the original figures listed. Note the %USERNAME% variable is returning my logon username and entering C:\Users\%USERNAME%\AppData\Local\EDEngineer results in an explorer error "windows cant find...

Thank you for your help so far.

**Comment by msrhs** [comment]
Note %HOMEPATH%\AppData\Local\EDEngineer does work I am no programmer but the homepath variables does return the correct user's home directory for a domain user. This of course may have nothing to do with the issue.

**Comment by msarilar** [comment]
I'm not using environment variables in the code, I'm using the windows API instead to retrieve "special" folders such as AppData etc..

Could you do the exact same procedure I initially told you to do, but this time install the application the regular way (with the setup.exe link in the home page) ?

**Comment by msrhs** [comment]
Hello Max

Thank you. Have carried out the procedure and installed using the setup.exe link in the home page and now I can open and close the application without loss of data. Have updated foe commodites, materials and data and all appear to be OK. Have not yet used materials. Once gain thank you ever so much for your contribution to the community. The EDEngineer folder does not appaear in my user so I dont know where the manualchanges file is could you let me know?

**Comment by msarilar** [comment]
Happy to hear that!

I store the data in the roaming folder of appdata which is synced across the domain for your user. It's the only other location where the application have write access :)
