### ISSUE TITLE
Feature request: "last session farmed materials"

### ISSUE THREAD

**Issue by Sheuzzo** [msarilar/EDEngineer#434]
As in topic, it would be nice to know how many and which kind of materials i got in a session, or between chosen date / time, so it's easier to understand farming efficency.

Thanks for everything I love Ed Engineer :D

**Comment by msarilar** [comment]
have a look at the chart in the latest version, might help you with that

**Comment by Sheuzzo** [comment]
System.NullReferenceException: Riferimento a un oggetto non impostato su un'istanza di oggetto. in CommanderChart.chartData@44.Invoke(JournalEntry e) in Microsoft.FSharp.Collections.Internal.IEnumerator.next@187[T](FSharpFunc`2 f, IEnumerator`1 e, FSharpRef`1 started, Unit unitVar0) in Microsoft.FSharp.Collections.Internal.IEnumerator.filter@182.System-Collections-IEnumerator-MoveNext() in Microsoft.FSharp.Collections.SeqModule.Fold[T,TState](FSharpFunc`2 folder, TState state, IEnumerable`1 source) in CommanderChart.chartData(String commander, String logDirectory, JsonSerializerSettings settings, ILanguage languages, LanguageInfo l) in CommanderChart.chart(String commander, String logDirectory, JsonSerializerSettings settings, ILanguage languages, LanguageInfo l) in Server.app@324-90.Invoke(LanguageInfo _arg38) in Microsoft.FSharp.Core.FSharpFunc`2.InvokeFast[V](FSharpFunc`2 func, T arg1, TResult arg2) in Microsoft.FSharp.Control.AsyncPrimitives.CallThenInvokeNoHijackCheck[a,b](AsyncActivation`1 ctxt, FSharpFunc`2 userCode, b result1) in .$Async.Return@1097.Invoke(AsyncActivation`1 ctxt) in .$Async.Return@1097.Invoke(AsyncActivation`1 ctxt) in .$Async.Return@1097.Invoke(AsyncActivation`1 ctxt) in .$Async.Return@1097.Invoke(AsyncActivation`1 ctxt) in .$Async.Return@1097.Invoke(AsyncActivation`1 ctxt) in .$Async.Return@1097.Invoke(AsyncActivation`1 ctxt) in Microsoft.FSharp.Control.Trampoline.Execute(FSharpFunc`2 firstAction)

**Comment by msarilar** [comment]
could you restart and try again? if that doesn't work, I'll need your logs uploaded in a zip file here

**Comment by Sheuzzo** [comment]
works ! thanks :)

**Comment by Sheuzzo** [comment]
it's perfect :D
