### ISSUE TITLE
Feature Request: "Clear complete shopping list" Button

### ISSUE THREAD

**Issue by MBGTBenjamin** [msarilar/EDEngineer#436]
o7, I have another suggestion: A button with which you can delete the complete shopping list with one click. Why: Because I often export different setups from Coriolis to see what I can and cannot mod without collecting a lot of materials.

**Comment by randomprecision** [comment]
PLEASE do this. I exported a bunch of crap to eden by mistake from coriolis. The red X's don't even clear any out. Otherwise I'd need to know how to purge my user data.

**Comment by msarilar** [comment]
added in 1.1.3.6
