### ISSUE TITLE
Malwarebytes has labeled EDEngineers app as Ransomware

### ISSUE THREAD

**Issue by LarrySmith-1437** [msarilar/EDEngineer#438]
I'm concerned that Malwarebytes, a program I rely on and trust, has marked and removed this app as Ransomware. 

Wondering if the author can comment on this, or work with Malwarebytes about this.

**Comment by msarilar** [comment]
Scan here is fine:

https://www.virustotal.com/file/9c258fe2a8424395a0a236b38bb9b84a5d0e2481cd88a5156783dc2b7c7eb213/analysis/1532250216/

Without more details I cannot really help with this. Your computer might be infected by something which put something inside your local EDEngineer executable (although it's signed so I don't see how that would be possible). It cannot initially come from EDEngineer anyway, but you can try to compile the sources yourself and see what goes.

**Comment by LarrySmith-1437** [comment]
Thanks for the independent verification.  Sometimes there are false positives, I'll dig a little further to see what if anything I can figure out about it.
