### ISSUE TITLE
EDEngineer is not in center of screen.

### ISSUE THREAD

**Issue by arkhilhra** [msarilar/EDEngineer#439]
I've just installed EDEngineer for the first time and it doesn't seem to be fitting my screen.  I changed it to overlay mode to see if that helped and it simply offset and I have to Ctrl + Alt + Del out of it.  By that I mean it's not in the center, it's positioned to the lower right side of my screen and there doesn't seem to be any way to change it back when it's like that.

**Comment by msarilar** [comment]
the bottom left button unlock/lock window allows you to switch between overlay and window mode

in window mode, you can resize and move the window to your taste for instance:

![image](https://user-images.githubusercontent.com/5569959/43267403-255e5018-90ee-11e8-83a5-6fa489f08af7.png)

once you're happy with the dimensions and position you can lock the window and it should stay in place

**Comment by arkhilhra** [comment]
That's off screen by about 4 inches, hence my issue.  Is there a keyboard command?

**Comment by msarilar** [comment]
noo but you should have the icon in your tasktray

![image](https://user-images.githubusercontent.com/5569959/43267642-cb254ae2-90ee-11e8-80c9-aa981945906c.png)

**Comment by arkhilhra** [comment]
That's covered up by the overlay.

**Comment by msarilar** [comment]
you have access to the same menu if you click the gear on the top right
![image](https://user-images.githubusercontent.com/5569959/43268080-f787291a-90ef-11e8-9e73-a1d15bef0b77.png)

**Comment by arkhilhra** [comment]
Okay.  That got me out of the window.  As I toggle between lock/unlock the window wants to float around a little but when it's locked it does fit the screen correctly.    Thank you.
