### ISSUE TITLE
Black screen

### ISSUE THREAD

**Issue by CrazyPotatoes** [msarilar/EDEngineer#44]
I updated the client straight from version 18 to version 31 because I haven't been on in a few days. When the client opens, the screen is black except for a vertical strip on the left that is 3-4 pixels wide. It allows me to click on the separate window button, which still shows a black window.

**Comment by msarilar** [comment]
Everything is in here : https://github.com/msarilar/EDEngineer/wiki/Troubleshooting-Issues =)
