### ISSUE TITLE
API off

### ISSUE THREAD

**Issue by nathanc213** [msarilar/EDEngineer#442]
The API is off and I'm unable to turn it on, when i click launch local API i get this: https://i.imgur.com/3jbpjOv.jpg

Is there supposed to be more settings in the window that pops up?

**Comment by msarilar** [comment]
the window on the right is supposed to be a dialog window asking you to pick a port if you don't want to use default one

seems like there's a resolution issue as it's supposed to look like this:

![image](https://user-images.githubusercontent.com/5569959/44107683-84cc3920-9ff8-11e8-894d-10a79a43112d.png)

if you can't resize the window (I don't think you can), could you move EDEngineer to a higher res screen and try to launch the API again? the popup will appear as it should

**Comment by nathanc213** [comment]
My pc is running at 3840x2160, i did close EDE and then set my resolution down to 1920x1080 but when i re launched the window was still the same size.

I even tried turning the windows scaling down to 100% (from 300%) but no luck.

**Comment by msarilar** [comment]
all right I just pushed a hotfix (restart the app) and you'll be able to press enter to accept the port

that should do it until I find a solution for that resolution/scaling concern

**Comment by nathanc213** [comment]
Wow that was quick, thanks!
