### ISSUE TITLE
unrecognized material - Guardian Wreckage Components

### ISSUE THREAD

**Issue by cyberbofh** [msarilar/EDEngineer#446]
found unrecognized material - guardian sentinel wreckage component

using EDEngineer v1.1.3.8

found this info about it:

Guardian Wreckage Components
https://inara.cz/galaxy-component/175/

Guardian Sentinel Wreckage Components
http://elite-dangerous.wikia.com/wiki/Guardian_Sentinel_Wreckage_Components

**Comment by msarilar** [comment]
that ingredient is in the application : https://github.com/msarilar/EDEngineer/blob/master/EDEngineer/Resources/Data/entryData.json#L1766

what's the error/warning you are seeing exactly?

**Comment by cyberbofh** [comment]
This is what I see in EDEngineer:  https://i.imgur.com/X7u2Lyf.png

**Comment by msarilar** [comment]
all right I found it, it was a remnant in the aggregation system that speeds up EDEngineer's startup

a restart will update the app and then clear the aggregation (so startup might be slower at first but a second startup will be faster)

thanks for reporting!
