### ISSUE TITLE
Add roll-out for commodities/materials/data to show recipes that it is used in

### ISSUE THREAD

**Issue by Psieonic** [msarilar/EDEngineer#45]
Reverse lookup of a material to decide if it's valuable or not is something that is useful to a lot of people, and simultaneously a little tedious to look up on something like Inara.  Adding the ability to click a material and have it roll-out a list of recipes its used in would be very beneficial.

**Comment by msarilar** [comment]
Have you tried the advanced "Ingredient Filter (reversed)" in the filters (top right of the window) ?

**Comment by Psieonic** [comment]
Forgot about that.  Overlooked it because it meant changing the other filters too if I had them set to something already.  ^_^
