### ISSUE TITLE
Meta Alloy Hull Reinforcement requires 25 Focus Xtal (not 15)

### ISSUE THREAD

**Issue by Charybdis** [msarilar/EDEngineer#458]
As per title: the unlock for Meta Alloy Hull Reinforcement at the broker is 25 Focus Crystals, not 15. 

Have added the JSON log record for the unlock from ED Discovery. Totals were correctly handled when completing the unlock.

 "Materials": [
    {
      "Name": "focuscrystals",
      "Name_Localised": "Focus Crystals",
      "Count": 25,
      "Category": "Manufactured"
    },

[Meta Alloy Hull Reinforcement.txt](https://github.com/msarilar/EDEngineer/files/2566417/Meta.Alloy.Hull.Reinforcement.txt)

![ma_recipie](https://user-images.githubusercontent.com/23155785/48271540-7492a500-e434-11e8-88ef-dda5836fdaf1.JPG)

**Comment by MaximumWoahverdrive** [comment]
I've confirmed the proposed value in game and fixed the error in https://github.com/msarilar/EDEngineer/pull/459/commits/6fd8930364503f2f15eb3dcfe792f392d3b1a836
So it should be fixed in the next release

**Comment by msarilar** [comment]
deployed in 1.1.4.0
