### ISSUE TITLE
Feature Request: Allow offline Engineering

### ISSUE THREAD

**Issue by Jibsman** [msarilar/EDEngineer#468]
I can export my ship builds from the game to Coriolis (or EDShipyard) via EDMC. If I could export my materials to a usable form and if EDEngineer would allow me to import the ship and materials I could work on Engineering offline, away from the game. 
I spent a couple hours working with EDEngineer last night before blasting off to gather mats and visit engineers. I LOVE EDEngineer and what it allows me to do. If I could do this (on breaks) at work I would be able to come home and immediately blast off to gather mats and visit engineers!
Thanks for reading!

**Comment by msarilar** [comment]
I think you should be able to get away with this by copying the aggregation.json file in your folder `C:\Users\%username%\AppData\Roaming\EDEngineer` and pasting it in the same place on the computer you use with EDEngineer

**Comment by Jibsman** [comment]
Thanks I’ll give it a try!


From Jibs on my iPhone
