### ISSUE TITLE
App insta-crash

### ISSUE THREAD

**Issue by upspiral89** [msarilar/EDEngineer#469]
After a lot of fiddling I managed to install and launch the application from the .exe, it required me to disable windows error reporting, but when the app starts the window closes as soon as it finishes loading and if I try to open it again I get the message "edengineer is already running" and then I have to reboot the system

**Comment by upspiral89** [comment]
Update: I uninstalled and removed the 2.0 folder entirely and then I reinstalled in safe mode with networking. Doing so I managed to install  and run edengineer without errors but when I try to launch it in normal mode the app closes itself as soon as it finishes loading. Any idea on what could cause this?

**Comment by msarilar** [comment]
could you check windows' event viewer and see if there's any interesting log in there?

windows+R `eventvwr`, Windows Logs => Application

**Comment by upspiral89** [comment]
ok, when I launch the app I get two error event (the description it't in italian since that's my system language)

.NET Runtime / event ID 1026 / category none

Applicazione: EDEngineer.exe
Versione framework: v4.0.30319
Descrizione: il processo è stato terminato a causa di un'eccezione non gestita.
Informazioni sull'eccezione: codice eccezione c0000005, indirizzo eccezione 18C671A0
Stack:

Application Error / event ID 1000 / category (100)

Nome dell'applicazione che ha generato l'errore: EDEngineer.exe, versione: 1.0.0.0, timestamp: 0x5be81c8f
Nome del modulo che ha generato l'errore: GTII-OSD.dll, versione: 2.0.3.2, timestamp: 0x5be93476
Codice eccezione: 0xc0000005
Offset errore 0x000371a0
ID processo che ha generato l'errore: 0x2e38
Ora di avvio dell'applicazione che ha generato l'errore: 0x01d4913d11640433
Percorso dell'applicazione che ha generato l'errore: C:\Users\TheCheater\AppData\Local\Apps\2.0\PHNZHW8A.REG\O7C9ZQPZ.D7H\eden..tion_b9c6c2d0b4f2eae5_0001.0001_530bc65010ba8563\EDEngineer.exe
Percorso del modulo che ha generato l'errore: C:\Program Files (x86)\ASUS\GPU TweakII\GTII-OSD\x86\GTII-OSD.dll
ID segnalazione: 6de70164-6c84-4ddb-a478-e5b1426dec8f
Nome completo pacchetto che ha generato l'errore: 
ID applicazione relativo al pacchetto che ha generato l'errore:

**Comment by msarilar** [comment]
so if I'm reading this right, it might be coming from an ASUS thing (GPU Tweak) ?
I'm not exactly sure what could be going wrong with this

Did you install EDEngineer using the setup.exe here https://cdn.rawgit.com/msarilar/EDEngineer/master/EDEngineer/releases/setup.exe ?

**Comment by MaximumWoahverdrive** [comment]
Yeah definitely some sort of issue with GPUTweak 2.
Did you install GPUTweak2 from the disk that came with your gpu or did you download it online?
If you installed it from disk when did you last update it (if at all) and lastly what model is your gpu?

**Comment by upspiral89** [comment]
ok, it's the osd function of GPU Tweak II indeed, if I disable the osd (or either add edengineer to the exclusion list) the app works witout issues

**Comment by upspiral89** [comment]
Since the issue is solved I'll close the issue, thx for your help

**Comment by Rkreitan** [comment]
you are Missing the GTII-OSD.dll files. I have posted them [here](https://github.com/Rkreitan/asus-GPUTweak-II-DLL-files/tree/8d84f5ecbe4f19342cd8b64b308b073a960b202b) for you to download. you could also download the program from ASUS sites[ her](https://www.asus.com/supportonly/GPUTweak%20II/HelpDesk_Download/)
