### ISSUE TITLE
EDEngineer loads up but just spins but never finsihes

### ISSUE THREAD

**Issue by domingojangles** [msarilar/EDEngineer#478]
I have installed a new version of EDEngineer. I started up Elite Dangerous in windowed mode and then started EDEngineer. The application looks to start up ok but it hangs on the black loading screen where the orange dots rotate around to make a circle under the EDENGINEER title of the loading screen but never actually loads anything.

I have recently had to uninstall my older version of EDENGINEER. After the removal of the applciation I downloaded the latest version from github here. Since then this has been the behavior I am seeing.

**Comment by msarilar** [comment]
could it be related to https://github.com/msarilar/EDEngineer/issues/469 ?

**Comment by Gabbatek** [comment]
I have this problem too

**Comment by msarilar** [comment]
the first startup can take a while, how long are you waiting?

**Comment by domingojangles** [comment]
After reading the information in that incident my issue doesn't soudn
related at all.

I used the setup.exe provided on the same url
https://cdn.rawgit.com/msarilar/EDEngineer/master/EDEngineer/releases/setup.exe

It installs fine and there aren't any errors in the event viewer. It in
fact does not error out at all. It just sits on the black window for
EDEgineer and spins the oprange dotted wheel like its loading something.


I just launched EDE again to take a screen shot for you. This time I was
prompted with an update. Odd.. I updated EDEngineer and now its working.

I guess this ticket can be closed.

Thanks for the quick response.

-D

**Comment by Gabbatek** [comment]
I actually just fixed it by uninstalling then reinstalling it with administrator rights. Avast flagged up a false positive for idp.alexa but once that was bypassed its running fine. Nice1

**Comment by msarilar** [comment]
yeah I just published an update but I'm unsure how it fixed your issue

anyway if this is working then it's great, have fun !

**Comment by domingojangles** [comment]
I'm guessing that's what it mostly was. The C:\Users\$USER$\Saved
Games\Frontier Developments\Elite Dangerous directory has about 50MB of
logs in it and i'm guessing the EDE program crawls through all of the
logs???

**Comment by msarilar** [comment]
yeah the first time to build history it does this, then subsequent restarts won't take as long

**Comment by domingojangles** [comment]
Good to know and sorry for the false alarm.
