### ISSUE TITLE
Suggestion: Ability to import/export preferences (Filters/Favourites/Shopping lists etc)

### ISSUE THREAD

**Issue by Slegnor** [msarilar/EDEngineer#482]
I wanted to move my EDEngineer from my PC to a laptop and realised that there was no way to preserve my current settings.

Would be useful to be able to import/export preferences (Filters/Favourites/Shopping lists etc)

**Comment by msarilar** [comment]
added in 90a3bf8412b44ce1e7164f09dea0c960a3af79c5
