### ISSUE TITLE
Errors when starting EDEngineer

### ISSUE THREAD

**Issue by AlexMoshninov** [msarilar/EDEngineer#488]
Hi, I tried to run the EDEngineer application, but after selecting the language I get an error [log.txt](https://github.com/msarilar/EDEngineer/files/2784550/log.txt). 
After all the error correction manipulations, the application failed to start and received another log [log Script-start.txt](https://github.com/msarilar/EDEngineer/files/2784549/log.Script-start.txt).
Please help me how to solve this problem.

**Comment by msarilar** [comment]
should be fixed in latest patch, please reopen if this is still breaking
