### ISSUE TITLE
Translate to German

### ISSUE THREAD

**Issue by msarilar** [msarilar/EDEngineer#49]
Bitte versuchen Sie, Ihre Arbeit hier synchronisieren, so dass Sie nicht am Ende der Übersetzung die gleichen Dinge zweimal :)

https://github.com/msarilar/EDEngineer/blob/master/EDEngineer/Resources/Data/localization.json

Currently Involved:

@puuhbear
@Scorprox
@rogerkilo

**Comment by puuhbear** [comment]
ok... I have no clue what to do :X

**Comment by msarilar** [comment]
@puuhbear I've seen this commit 1d2ecdbdd082cafa3b41184328b71de36ce7bbe7 and it's very good ! Only a few minor typos I've commented (missing double quotes there and there). You can fix this and open a pull request so I can merge these changes into EDEngineer :)

**Comment by puuhbear** [comment]
ok... how do I edit? sorry I'm all new to this :)

**Comment by msarilar** [comment]
once you make your change on your computer and you push on GitHub, the page of your fork will have a new button that will showup in order to initiate a pull request.

you don't have to wait for all the translation to be finished before doing a single massive pull request, you can send me multiple small ones

just make sure the whole file you modified is valid JSON (copy paste it in a validator like this one : http://jsonlint.com/)

**Comment by msarilar** [comment]
so @Scorprox completely finished the translation (100%)
I need to make some minor changes to the blueprint grid to handle long words :P

**Comment by msarilar** [comment]
deployed in 1.0.2
