### ISSUE TITLE
Tons of NullReferences reading log files since 2018-12-21

### ISSUE THREAD

**Issue by SirWumpus** [msarilar/EDEngineer#496]
![nullref](https://user-images.githubusercontent.com/7441729/52912083-76ada080-327a-11e9-8a60-93d1cebb7940.png)

Popping LOTS of null references reading journal files from 2018-12-21 onwards.   I've supplied some example logs.

[Journal.181222055830.01.log](https://github.com/msarilar/EDEngineer/files/2847743/Journal.181222055830.01.log)
[Journal.181222114348.01.log](https://github.com/msarilar/EDEngineer/files/2847744/Journal.181222114348.01.log)
[Journal.181223064733.01.log](https://github.com/msarilar/EDEngineer/files/2847745/Journal.181223064733.01.log)
[Journal.181223075259.01.log](https://github.com/msarilar/EDEngineer/files/2847746/Journal.181223075259.01.log)

**Comment by msarilar** [comment]
that issue was fixed thr 13th of December I believe : 3970b9f57382ebe5e6cf1fd6bb06f5a34fb1cdd4

make sure you're using the latest version of EDEngineer (1.1.4.3 as of today)
