### ISSUE TITLE
Translate to Russian

### ISSUE THREAD

**Issue by msarilar** [msarilar/EDEngineer#50]
Пожалуйста, попробуйте синхронизировать работу здесь, так что вы не будете в конечном итоге перевод одни и те же вещи дважды))

https://github.com/msarilar/EDEngineer/blob/master/EDEngineer/Resources/Data/localization.json

Currently Involved:

@Morozova
@VChet

**Comment by msarilar** [comment]
Great job so far @Morozova, a fourth of the application is now translated in russian.

Please be aware that [translation like this](https://github.com/Morozova/EDEngineer/blob/patch-3/EDEngineer/Resources/Data/localization.json#L1516) might cause issues because of their length compared to the initial length of the text in english.

I'll see what I can do to resize things according to the translated text, but before publishing I'll send you a binary standalone of the russian version so you can check things by yourself :)

Keep up the good work!

**Comment by Morozova** [comment]
@msarilar i already think about this issue, but looks like its not possible to do anything with that, because Russian words mostly longer than English, thats why we get:
Untypical Shield Scans (22 symbols) = Нетипичные данные сканирования щитов (36 symbols) 

:(

**Comment by msarilar** [comment]
Alright just keep that in mind not for official names in the game but for "misc" text that doesn't refer to anything in the game :)

I'll work out something out with what you sent me this far tonight

**Comment by msarilar** [comment]
Congratz @Morozova and @VChet, the russian localization is now available!

Don't hesitate to submit more PR if you spot typos/errors or if you think some text can be shortened to better fit the UI!
