### ISSUE TITLE
Bug in loadout event

### ISSUE THREAD

**Issue by VAKazakov** [msarilar/EDEngineer#503]
![image](https://user-images.githubusercontent.com/47143965/56862962-2446d980-69b9-11e9-91cc-89d45adb6771.png)
i suppose it connected with new 1st slot
<details> 
  <summary>LoadOut event from log
</summary>
  { "timestamp":"2019-04-28T10:22:48Z", "event":"Loadout", "Ship":"Anaconda", "ShipID":16, "ShipName":"[EGP-AX] ADM Drofovich", "ShipIdent":"EGKAX3", "HullValue":120606024, "ModulesValue":76080375, "HullHealth":0.990987, "UnladenMass":627.221619, "CargoCapacity":16, "MaxJumpRange":43.189285, "FuelCapacity":{ "Main":32.000000, "Reserve":1.070000 }, "Rebuy":9834321, "Modules":[ { "Slot":"LargeHardpoint2", "Item":"hpt_mininglaser_turret_medium", "On":true, "Priority":0, "Health":0.982394, "Value":28587 }, { "Slot":"LargeHardpoint3", "Item":"hpt_mininglaser_turret_medium", "On":true, "Priority":0, "Health":0.999337, "Value":28587 }, { "Slot":"TinyHardpoint1", "Item":"hpt_cloudscanner_size0_class5", "On":false, "Priority":1, "Health":0.992959, "Value":962702 }, { "Slot":"TinyHardpoint2", "Item":"hpt_heatsinklauncher_turret_tiny", "On":true, "Priority":0, "AmmoInClip":1, "AmmoInHopper":2, "Health":0.985311, "Value":3072 }, { "Slot":"TinyHardpoint3", "Item":"hpt_heatsinklauncher_turret_tiny", "On":true, "Priority":0, "AmmoInClip":1, "AmmoInHopper":1, "Health":0.984298, "Value":3072 }, { "Slot":"TinyHardpoint4", "Item":"hpt_xenoscanner_basic_tiny", "On":true, "Priority":0, "Health":0.993263, "Value":320901 }, { "Slot":"Armour", "Item":"anaconda_armour_grade1", "On":true, "Priority":1, "Health":1.000000, "Engineering":{ "Engineer":"Selene Jean", "EngineerID":300210, "BlueprintID":128673644, "BlueprintName":"Armour_HeavyDuty", "Level":5, "Quality":0.830000, "Modifiers":[ { "Label":"DefenceModifierHealthMultiplier", "Value":137.221985, "OriginalValue":79.999992, "LessIsGood":0 }, { "Label":"KineticResistance", "Value":-14.204001, "OriginalValue":-20.000004, "LessIsGood":0 }, { "Label":"ThermicResistance", "Value":4.830003, "OriginalValue":0.000000, "LessIsGood":0 }, { "Label":"ExplosiveResistance", "Value":-33.237995, "OriginalValue":-39.999996, "LessIsGood":0 } ] } }, { "Slot":"PaintJob", "Item":"paintjob_anaconda_galnet_galnet", "On":true, "Priority":1, "Health":1.000000 }, { "Slot":"PowerPlant", "Item":"int_powerplant_size4_class5", "On":true, "Priority":1, "Health":0.984920, "Value":1264683, "Engineering":{ "Engineer":"Hera Tani", "EngineerID":300090, "BlueprintID":128673765, "BlueprintName":"PowerPlant_Boosted", "Level":1, "Quality":1.000000, "Modifiers":[ { "Label":"Integrity", "Value":83.599998, "OriginalValue":88.000000, "LessIsGood":0 }, { "Label":"PowerCapacity", "Value":17.472000, "OriginalValue":15.600000, "LessIsGood":0 }, { "Label":"HeatEfficiency", "Value":0.420000, "OriginalValue":0.400000, "LessIsGood":1 } ] } }, { "Slot":"MainEngines", "Item":"int_engine_size5_class2", "On":true, "Priority":0, "Health":0.994626, "Value":165879 }, { "Slot":"FrameShiftDrive", "Item":"int_hyperdrive_size6_class5", "On":true, "Priority":0, "Health":0.987699, "Value":14197539, "Engineering":{ "Engineer":"Felicity Farseer", "EngineerID":300100, "BlueprintID":128673691, "BlueprintName":"FSD_LongRange", "Level":2, "Quality":1.000000, "Modifiers":[ { "Label":"Mass", "Value":46.000000, "OriginalValue":40.000000, "LessIsGood":1 }, { "Label":"Integrity", "Value":132.539993, "OriginalValue":141.000000, "LessIsGood":0 }, { "Label":"PowerDraw", "Value":0.795000, "OriginalValue":0.750000, "LessIsGood":1 }, { "Label":"FSDOptimalMass", "Value":2250.000000, "OriginalValue":1800.000000, "LessIsGood":0 } ] } }, { "Slot":"LifeSupport", "Item":"int_lifesupport_size5_class5", "On":true, "Priority":0, "Health":0.986380, "Value":1089257 }, { "Slot":"PowerDistributor", "Item":"int_powerdistributor_size4_class2", "On":true, "Priority":0, "Health":0.985029, "Value":24898 }, { "Slot":"Radar", "Item":"int_sensors_size8_class2", "On":true, "Priority":0, "Health":0.994424, "Value":1530326, "Engineering":{ "Engineer":"Juri Ishmaak", "EngineerID":300250, "BlueprintID":128740670, "BlueprintName":"Sensor_LightWeight", "Level":2, "Quality":0.820700, "Modifiers":[ { "Label":"Mass", "Value":43.321602, "OriginalValue":64.000000, "LessIsGood":1 }, { "Label":"Integrity", "Value":96.000000, "OriginalValue":120.000000, "LessIsGood":0 }, { "Label":"SensorTargetScanAngle", "Value":27.000000, "OriginalValue":30.000000, "LessIsGood":0 } ] } }, { "Slot":"FuelTank", "Item":"int_fueltank_size5_class3", "On":true, "Priority":1, "Health":1.000000, "Value":83090 }, { "Slot":"Decal1", "Item":"decal_powerplay_yurigrom", "On":true, "Priority":1, "Health":1.000000 }, { "Slot":"Decal2", "Item":"decal_explorer_elite", "On":true, "Priority":1, "Health":1.000000 }, { "Slot":"ShipName0", "Item":"nameplate_hunter03_white", "On":true, "Priority":1, "Health":1.000000 }, { "Slot":"ShipName1", "Item":"nameplate_hunter03_white", "On":true, "Priority":1, "Health":1.000000 }, { "Slot":"ShipID0", "Item":"nameplate_shipid_doubleline_white", "On":true, "Priority":1, "Health":1.000000 }, { "Slot":"ShipID1", "Item":"nameplate_shipid_doubleline_white", "On":true, "Priority":1, "Health":1.000000 }, { "Slot":"Slot01_Size7", "Item":"int_fighterbay_size7_class1", "On":true, "Priority":0, "Health":0.982575, "Value":2079079 }, { "Slot":"Slot02_Size6", "Item":"int_repairer_size6_class5", "On":false, "Priority":1, "Health":0.992610, "Value":13430578 }, { "Slot":"Slot03_Size6", "Item":"int_fuelscoop_size6_class5", "On":true, "Priority":0, "Health":0.999522, "Value":25240068 }, { "Slot":"Slot04_Size6", "Item":"int_repairer_size6_class5", "On":false, "Priority":1, "Health":0.984303, "Value":13430578 }, { "Slot":"Slot05_Size5", "Item":"int_shieldgenerator_size5_class2", "On":true, "Priority":1, "Health":0.981296, "Value":165879 }, { "Slot":"Slot06_Size5", "Item":"int_dronecontrol_collection_size5_class2", "On":true, "Priority":0, "Health":0.984721, "Value":85293, "Engineering":{ "Engineer":"The Sarge", "EngineerID":300040, "BlueprintID":128731526, "BlueprintName":"Misc_LightWeight", "Level":1, "Quality":1.000000, "Modifiers":[ { "Label":"Mass", "Value":4.400000, "OriginalValue":8.000000, "LessIsGood":1 }, { "Label":"Integrity", "Value":69.299995, "OriginalValue":77.000000, "LessIsGood":0 } ] } }, { "Slot":"Slot07_Size5", "Item":"int_dronecontrol_repair_size5_class2", "On":true, "Priority":0, "Health":0.997444, "Value":85293 }, { "Slot":"Slot08_Size4", "Item":"int_cargorack_size4_class1", "On":true, "Priority":1, "Health":1.000000, "Value":30124 }, { "Slot":"Slot09_Size4", "Item":"int_buggybay_size4_class2", "On":true, "Priority":0, "Health":0.992083, "Value":75816 }, { "Slot":"Slot10_Size4", "Item":"int_dronecontrol_unkvesselresearch", "On":true, "Priority":0, "Health":0.985722, "Value":1535274 }, { "Slot":"PlanetaryApproachSuite", "Item":"int_planetapproachsuite", "On":true, "Priority":1, "Health":1.000000, "Value":425 }, { "Slot":"WeaponColour", "Item":"weaponcustomisation_cyan", "On":true, "Priority":1, "Health":1.000000 }, { "Slot":"EngineColour", "Item":"enginecustomisation_cyan", "On":true, "Priority":1, "Health":1.000000 }, { "Slot":"VesselVoice", "Item":"voicepack_maksim", "On":true, "Priority":1, "Health":1.000000 }, { "Slot":"Slot14_Size1", "Item":"int_detailedsurfacescanner_tiny", "On":true, "Priority":0, "Health":0.991488, "Value":219375, "Engineering":{ "Engineer":"Lori Jameson", "EngineerID":300230, "BlueprintID":128740150, "BlueprintName":"Sensor_Expanded", "Level":4, "Quality":0.905000, "Modifiers":[ { "Label":"PowerDraw", "Value":0.000000, "OriginalValue":0.000000, "LessIsGood":1 }, { "Label":"DSS_PatchRadius", "Value":27.810001, "OriginalValue":20.000000, "LessIsGood":0 } ] } }, { "Slot":"ShipCockpit", "Item":"anaconda_cockpit", "On":true, "Priority":1, "Health":0.998476 }, { "Slot":"CargoHatch", "Item":"modularcargobaydoor", "On":false, "Priority":2, "Health":0.994765 } ] } 
</details>

**Comment by msarilar** [comment]
can't reproduce I think I already fixed this
