### ISSUE TITLE
EDEngineer not coming up in game, only on desktop.

### ISSUE THREAD

**Issue by onyxius** [msarilar/EDEngineer#504]
I just installed EDEngineer and set it up according to the documentation.  The overlay comes up in windows, however it does not come up in game.

I use Oculus Rift > Launched within SteamVR.
The game is setup to Full Screen Borderless.

Not sure what else to try to get the overlay to work in game.

**Comment by onyxius** [comment]
I launched ED without VR and still not able to get engineer to show up in game.

**Comment by onyxius** [comment]
is there some other support location i need to go for help on this?  3 days and no comment/update :(

**Comment by msarilar** [comment]
are you playing full screen or windowed mode?

**Comment by onyxius** [comment]
Hi msarilar,
  I tried windowed mode and full screen borderless without any difference.  I even tried removing the VR headset and running the game as a regular full screen borderless non vr mode without a difference.

**Comment by onyxius** [comment]
Is this tool not being used anymore?

**Comment by msarilar** [comment]
yeah it is, support for VR isn't really in the pipes though

if you're not playing with VR and playing borderless/windowed, you should be able to make it work

the app should be at least visible (e.g. alt tabbing should make it appear), if it's not you can right click the icon in the task tray icon and click on Show (or use the shortcut you configured to make it appear)

**Comment by onyxius** [comment]
Thanks Msarilar,  I tried running it outside of VR and it still wont pull up the overlay in game, just the program outside of the game. I used the shortcuts as you mentioned as well as made sure the "API ON" was on the bottom.

**Comment by onyxius** [comment]
Any other troubleshooting to get the overlay to work in game?

**Comment by msarilar** [comment]
if you could upload screenshots of the game with graphic settings shown as well as a screenshot with the app visible (with the game in the background), it could shed some light on your problem

**Comment by onyxius** [comment]
Here you go.
https://imgur.com/a/9I827dM

**Comment by msarilar** [comment]
so I can see the window being in unlocked mode, i.e. normal regular window

focussing on another window will make EDEngineer go behind said window

locking EDEngineer will make it always on top, and you can show/hide it using the configurable shortcut

**Comment by onyxius** [comment]
I'm not sure what changed, but it is working this morning.  I reset the position and was able to pull it up in front of the game with a translucent look because i can see the game in the background.  Would be awesome to get this to also load up inside a VR headset for everyone using VR, or make a version that can be used via browser like chrome since we can use OVRDrop to pull up said browsers.

Thanks Again.
