### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by Jibsman** [msarilar/EDEngineer#506]
I would like to be able to print out the list of materials displayed in the bottom right after selecting the engineering I want to add. Maybe include the pulldowns of materials from the Material Trader so we can see what we need to trade to get our mats.
Thanks!
Great App! Saved me tons of time figuring out what I need!
Happy

**Comment by msarilar** [comment]
you mean like a screenshot somehow?

**Comment by Jibsman** [comment]
What I have been doing is taking a screenshot and cropping just the material list in EDEngineer, then displaying the picture on my desktop for reference. I was thinking "export to a text file" or something similar. 
Thanks for responding. Keep up the excellent work!!
Jibs / Happy / John

**Comment by msarilar** [comment]
published in 1.1.4.6

**Comment by Jibsman** [comment]
Thanks so much! That is just perfect!
Cheers!
