### ISSUE TITLE
EdEngineer set to wrong language

### ISSUE THREAD

**Issue by whitelion1284** [msarilar/EDEngineer#507]
Hello,

I just attempted to install ED Engineer and it's all in Russian or Polish (not sure which). I can't understand a word of it. I'm not very tech savvy to begin with. Can anyone help me get it working for this poor dumb American? 

Thanks so much
Cheers

**Comment by msarilar** [comment]
if you click on the gear icon on the top right, you will have a menu and in this menu, click the globe to open the language selection window

![image](https://user-images.githubusercontent.com/5569959/59501821-a07b7a80-8e9c-11e9-9a53-1a2afafae785.png)

**Comment by whitelion1284** [comment]
Thank you.
