### ISSUE TITLE
Chromium missing from some Guardian recipes

### ISSUE THREAD

**Issue by AMWild** [msarilar/EDEngineer#516]
Hi,

I've just got back from Guardian space with everything EDEngineer said I needed for all the Guardian unlocks, except that I didn't have the required commodities.

However, on going to a Guardian tech broker,  I found that EDEngineer had omitted the Chromium requirement for all Guardian unlocks that require it.

**Comment by seedubya** [comment]
@msarilar : this can be closed, as its been fixed already.

**Comment by msarilar** [comment]
thanks @seedubya I appreciate it
