### ISSUE TITLE
Question about using EDEngineer

### ISSUE THREAD

**Issue by GiacomoLaw** [msarilar/EDEngineer#518]
Hi there, first thanks for the tool. I have a quick question on using it - I want to track my progress towards getting all the stuff for my mods for this build: https://s.orbis.zone/2pyo

This is what I see: https://i.imgur.com/VMUfaO0.png

Not really sure what settings to have just to have it show my progress towards item collection towards the mods.

Thanks!

**Comment by msarilar** [comment]
you can drag and drop the red horizontal bar, it's a splitter that you can move around (will make scrollbars appear)

**Comment by GiacomoLaw** [comment]
Okay, thank you!
