### ISSUE TITLE
Running API on non-localhost?

### ISSUE THREAD

**Issue by sbarre** [msarilar/EDEngineer#524]
Would you consider allowing the API to run on a machine's non-localhost address?  I have an internal network at home and I'd like to access EDEngineer's API from a second computer within my house (without having to set up a proxy etc)

This doesn't have to be on by default (I get the security concerns) but having it as an advanced option would be very useful.

If this is something you'd consider, I'd donate to get it into the backlog.  

Thank you for all your work on this app, it's fantastic!

**Comment by msarilar** [comment]
What do you mean by `a machine's non-localhost address`?

I don't think you need any proxy to access a HTTP endpoint hosted by a computer in your local network.

You might want to try to find out the API computer's IP address (`ipconfig` in the console) and then try to access it from your other computer `http://100.100.100.5:45000/commanders`.

Let me know if that's good enough or if I misunderstood the request!

**Comment by sbarre** [comment]
Unless I'm reading it wrong, from what I can see in the source the API server is binding to localhost (127.0.0.1) only:

See here: https://github.com/msarilar/EDEngineer/blob/0c8e58267833207730e3c3ea9e2c70c611a31893/EDEngineer.Server/Server.fs#L367`

```
startWebServer { 
    defaultConfig with 
      cancellationToken = token
      bindings = [ HttpBinding.createSimple HTTP "127.0.0.1" port ] } app
  state
```

That means that the API is only available on the machine's local/loopback address, and can't be accessed from other machines even on the same local network.

If this API is read-only and there's no way to update or change any info through it, you could change that `127.0.0.1` value to `0.0.0.0` which will cause the web server to bind to all available IP addresses on the host machine, meaning it will be available on localhost but also on `192.168.x.y` or whatever external IP address(es) the computer has available.

Since this does expose a public port/service on the computer, you may want to make that choice a toggle in the options (either running only on localhost, or on all available interfaces), since some privacy-focused Commanders may not want this behaviour if their computers are not behind a router or firewall, etc..   

If I knew C# and F# better, I'd try my hand at submitting a PR, but unfortunately I don't know those languages well enough unfortunately.

Thanks for responding, I hope my additional info helps..

**Comment by msarilar** [comment]
ah yes you're right I forgot about this binding!

it should be replaced by 0.0.0.0 indeed or IPAddress.Any (the same but more .NET idiomatic)

I'll try and update that soon, having the option to do so is a good idea

**Comment by sbarre** [comment]
Great!  I bought you a few beers in exchange.  ;-)

**Comment by msarilar** [comment]
the feature is available now if you restart the app, you can reopen if you encounter issues

cheers for the beers!
