### ISSUE TITLE
EDEngineer Window wont scroll

### ISSUE THREAD

**Issue by scotty113** [msarilar/EDEngineer#528]
Hi, I hope I am writing this in the correct place. I love ED and couldn't play without it.  I have just discovered the API feature as someone told me about it.  I have successfully got a build from Coriolis into EDEngineer, but I can't scroll the window.  I usually have it in locked mode. But if I unlock it and then full screen it, then I see there is more items to look at.  Perhaps I'm missing something.
Apologies if I am reporting this in the wrong place.

Many thanks for one of the most useful tools in Elite Dangerous. ;)

**Comment by msarilar** [comment]
hi, does #444 answer your question?

**Comment by scotty113** [comment]
Ah, thanks so much.  I suspected that it would have already been addressed.  Apologies for not seeing the reb bar.  
Thanks for the tool -- I've been using EDEngineer for a long time, but have only just discovered the shopping list from Coriolis thing.
Many many thanks
