### ISSUE TITLE
Seems to be all in spanish? 

### ISSUE THREAD

**Issue by nirurin** [msarilar/EDEngineer#529]
I know you recently completed a spanish translation pack for this (which is great and all) but it seems to default to spanish. In fact, even when I choose the 'English' option in the setup popup menu, everything is still in spanish.

**Comment by msarilar** [comment]
what happens when you change language in the window menu (gear icon top right) or right click the icon in the windows task tray icon?

do you have write access to username\AppData\Roaming folder?
