### ISSUE TITLE
App closes immediatly

### ISSUE THREAD

**Issue by Kamiakze** [msarilar/EDEngineer#533]
The applikation worked fine for years, but recently when i open it, the OneClick process starts with EDEngineer as an attached child process, displays a "Launching Appliaktion" window for about half a second and closes again. I have tried reinstalling and rebooting several times, and adding it to Windows Defender's exceptions list, to no avail

I'm kind of at a loss here

**Comment by msarilar** [comment]
it could have been linked to a problem in the app signing

could you give it a go again and reopen if the issue persists?
