### ISSUE TITLE
Window gets lost using dual monitors

### ISSUE THREAD

**Issue by Kierne** [msarilar/EDEngineer#537]
This is probably an extreme edge case, but this is the issue I encountered today:

I play with a laptop and have a secondary monitor I use to keep things like EDEngineer, EDDiscovery, and such visible while I play on the laptop's main screen. Today I played without the second monitor plugged in. Normally programs will remember their location when they were last on the main monitor and open there in the absence of the second monitor, but EDEngineer tried to place its window on the non-existent second monitor. I could tell it was trying to open there because the program was running and when I minimized and maximized it from the taskbar, I could see the "swoosh" effect going from its button on the taskbar and moving in the direction of where the second monitor was as it maximized.

**Comment by msarilar** [comment]
if the window gets lost you can always reset its position via right clicking the icon in the task tray

**Comment by Kierne** [comment]
Ah, handy! Thanks for the tip.
