### ISSUE TITLE
Export from Coriolis misses bulkhead and life support blueprints

### ISSUE THREAD

**Issue by alterNERDtive** [msarilar/EDEngineer#542]
No idea if other stuff that I haven’t actually been using is missing, too. Also no idea if the issue is on Coriolis’ or ED Engineer’s end.

see EDCD/coriolis#607

**Comment by Sid127** [comment]
@felixlinker this can be closed

**Comment by felixlinker** [comment]
Why?

**Comment by felixlinker** [comment]
I see. It got fixed in EDCD/coriolis/issues/607. However, this is EDEngineer. So either @msarilar or @alterNERDtive must close.
