### ISSUE TITLE
Request: API call to have raw+manufactured+data counts in one go

### ISSUE THREAD

**Issue by phlnx** [msarilar/EDEngineer#548]
If such thing is already possible then I offer my apologies and you can disregard the question (I would appreciate being redirected to the appropriate documentation).

Thank you for your attention.

**Comment by msarilar** [comment]
I think the endpoint exists, it's "cargo" (see https://github.com/msarilar/EDEngineer/wiki/API-Reference)

**Comment by phlnx** [comment]
Oh thanks. That one also returns commodities, but I can work around that. I will close the issue then.
