### ISSUE TITLE
incorrect coriolis id on some blueprints

### ISSUE THREAD

**Issue by PwccaCode** [msarilar/EDEngineer#552]
i only found the issue for power plant currently 

the "CoriolisGuid": "4dcf6bdc-bcff-448a-92a0-7612de548db7" is for overcharged grande 5 powerplan on ed engineer docs.

this is the  "uuid": "f8cee63e-9cdf-43e5-9584-a945d4c57aee" for the powerplant overcharged grade 5 on coriolis documentation.

when you try to import this blueprint from coriolis only the experimental effect works. I suspect this is the cause of the issue

**Comment by msarilar** [comment]
seems to be reminiscent of this issue #501 

coriolis guids are mapped here : https://github.com/msarilar/EDEngineer/blob/master/EDEngineer/Resources/Data/blueprints.json

if there's discrepency between what coriolis sends to edengineer then these ids should be updated - contributions are most welcome :)
