### ISSUE TITLE
Small error in spanish translation.

### ISSUE THREAD

**Issue by Jugom** [msarilar/EDEngineer#557]
Every time I'm engineering something, I have to spend 30 seconds looking before realizing that yeah... that's the one I can't never find. 

![Sample2](https://user-images.githubusercontent.com/74990247/103058047-2b97ff00-456f-11eb-86e5-cbd861020ad9.png)
^What EDEngineer shows^

![Sample1](https://user-images.githubusercontent.com/74990247/103058086-41a5bf80-456f-11eb-9654-c014604e9237.png)
^How is actually called in game.^

**Comment by msarilar** [comment]
thanks for reporting that, localization can be fixed from your browser

check this page https://github.com/msarilar/EDEngineer/wiki/Helping-With-The-Localization
