### ISSUE TITLE
Feature Request: Permanent "Collapse/Expand Categories" setting

### ISSUE THREAD

**Issue by raulmckool** [msarilar/EDEngineer#565]
Hello! 

PLEASE, for the love of Raxxla, include a setting to make material categories in the left panel **stay collapsed** no matter what, and leave expanded only the ones we have open.

It is really annoying having to re-collapse all categories on every start, _and_ every time one switches between All-Raw Only-Manufactured Only.

I don't know, may be a "Default Category Display: Expanded/Collapsed" option, or a simple "Expand all/Collapse all" button?

Heck, even the Group Ingredients button could do it: group stuff and collapse all categories by default.

Please, please, please make this happen. Thank you! o7

![EDE](https://user-images.githubusercontent.com/65040283/105890650-6669d880-5fee-11eb-8ddb-87cda6600f85.png)

**Comment by msarilar** [comment]
good idea, it's in 3d2d29784342338bebdbf8bb3d824242a741d9d9
