### ISSUE TITLE
Guardian Gauss Incorrect Premium Synth Recipe

### ISSUE THREAD

**Issue by wingcobob** [msarilar/EDEngineer#567]
![image](https://user-images.githubusercontent.com/71791191/106274891-e7161800-622c-11eb-9cde-f510a04d060e.png)
Premium gauss synth does not use heat resistant ceramics (only Standard does)
![image](https://user-images.githubusercontent.com/71791191/106275059-2cd2e080-622d-11eb-93b8-2bf2173dce07.png)

**Comment by msarilar** [comment]
thanks for the report 👍, you can submit any sort of correction directly to the blueprints (see https://github.com/msarilar/EDEngineer/wiki/Contributing)
