### ISSUE TITLE
Not all engineers showing up in EDEngineer

### ISSUE THREAD

**Issue by rbradh53** [msarilar/EDEngineer#569]
I noticed that all engineers are not showing up.
The engineers not on the list are:
COLONEL BRIS DEKKER
JURI ISHMAAK
MEL BRANDON
THE DWELLER
TOD MCQUINN
![engineers](https://user-images.githubusercontent.com/79338607/108565732-2e933f80-72d3-11eb-9bd6-9a4c52da5f57.jpg)

**Comment by msarilar** [comment]
these are engineers you unlock via bringing stuff to collect that is tracked by the app
the engineers you cite afaik don't need ingredients but other stuff such as having a certain combat rank etc
