### ISSUE TITLE
Downloadable setup does Not work.

### ISSUE THREAD

**Issue by quall3** [msarilar/EDEngineer#57]
Hello,
thank you very much for making such an impressive app!
I would like to try it too, but everytime i try to run the downloadable setup from this:
https://cdn.rawgit.com/msarilar/EDEngineer/master/EDEngineer/releases/setup.exe
i just get the Warning:
"An error occurred attempting to install EDEngineer."
I tried running it as Administrator and with deactivated firewall.
[install.log.txt](https://github.com/msarilar/EDEngineer/files/587903/install.log.txt)
i have attached the Install.log
Please help, what am I doing wrong?

Regards,
quall3

**Comment by msarilar** [comment]
Have you tried the steps described in the section [Whenever I try to install/update, I got some messed up error that doesn't seem to come from the application itself](https://github.com/msarilar/EDEngineer/wiki/Troubleshooting-Issues)?

**Comment by quall3** [comment]
There is no process named "ClickOnce" or "dfsvc.exe" running in my Task Manager.
The smart Screen process Starts always again after I killed it and the setup is started.

**Comment by msarilar** [comment]
you can access https://raw.githubusercontent.com/msarilar/EDEngineer/master/EDEngineer/releases/EDEngineer.application ?

**Comment by quall3** [comment]
If I open the link you posted in Browser, I see some 28 Line HTML code.

**Comment by quall3** [comment]
Is it possible that it doesn't work because I changed the path of my Home Folder?

**Comment by msarilar** [comment]
try to delete the content of `C:\Users\%USERNAME%\AppData\Local\Apps\2.0` directory, eventually restart your computer

some people experience similar issues you have for other clickonce application

http://stackoverflow.com/questions/30042008/clickonce-fails-on-download
http://stackoverflow.com/questions/20244507/download-clickonce-fails-from-setup-exe

**Comment by quall3** [comment]
is there another way than running that setup.exe ?
what do i have to do if I just clone the repository to make it run?

**Comment by msarilar** [comment]
you could build the solution with visual studio (just disable assembly signing in the project option) and run the outputted executable

**Comment by msarilar** [comment]
or unzip that:
[Release.zip](https://github.com/msarilar/EDEngineer/files/587982/Release.zip)

and run EDEngineer.exe in here

be aware that you won't have autoupdate with that, so if I add feature or fix issues you're not going to be up to date
