### ISSUE TITLE
Wrong maximum for Ruthenium

### ISSUE THREAD

**Issue by kerbe** [msarilar/EDEngineer#581]
![image](https://user-images.githubusercontent.com/47280420/111856302-67562100-8932-11eb-8c19-c24d47d22c64.png)

I just noticed that Ruthenium has maximum storage of 100, while EDEngineer expects maximum storage to be 150.

I didn't find where this is stored in EDEngineer, otherwise I'd done pull request to fix it.

**Comment by msarilar** [comment]
rare elements have 150 max capacity, this one seems to be the exception so I overrided it in the ref data file
thanks for the report!
