### ISSUE TITLE
Wrong max count in Antimony

### ISSUE THREAD

**Issue by kerbe** [msarilar/EDEngineer#584]
As I was gathering materials, noticed that EDEngineer and in game inventory has different maximum for Antimony:

![image](https://user-images.githubusercontent.com/47280420/112542003-bc73b600-8dbc-11eb-8f1f-6315dba041bc.png)

Also noticed that grade seems to be different, in game it looks to be T5 material, EDEngineer shows grade 4. Haven't checked material trader how it shows it.

**Comment by Scyntrus** [comment]
Antimony has a limit of 150 for me.
Ruthenium also has a limit of 150 for me, but EDEngineer says the limit is 100.
But Tellerium's limit is actually 100.

**Comment by Scyntrus** [comment]
![image](https://user-images.githubusercontent.com/1661362/114321250-af4e0b00-9ace-11eb-888a-a619dfdea969.png)

**Comment by kerbe** [comment]
Now that I got notification of these messages, I checked my game again. Currently it seems to have:
- Antimony limit of 150
- Rutherium limit of 150
- Tellerium limit of 150

@Scyntrus, that Rutherium limit of 100 is because of issue #581, as it was showing like that a while ago.

Antimony limit was 100 for few weeks, before I made this issue. Now it seems to have changed... No idea what has caused that. Update from Fdev, or some other anomaly. Don't know. But a bit annoying.

**Comment by Scyntrus** [comment]
So I just checked again and my Tellerium limit changed from 100 to 150. I don't know what happened.

**Comment by Lorithus** [comment]
It's an Elite Dangerous bug, when you reach the limit of 100, logout and login, so the limit will be 150.

**Comment by seedubya** [comment]
Antimony / Tellurium all report 150 now.
Ruthenium limit was resolved by #720
