### ISSUE TITLE
Unlock Requirement for Engineered FSD V1 Incorrect

### ISSUE THREAD

**Issue by lucidtraceur** [msarilar/EDEngineer#586]
Listed materials for unlock:
10 Tellurium
10 Electrochemical Arrays
12 Chemical Processors
10 Datamined Wake Exceptions

Actual materials for unlock:
26 Tellurium
26 Electrochemical Arrays
28 Chemical Processors
18 Datamined Wake Exceptions

**Comment by msarilar** [comment]
data is fine, might need a deploy
