### ISSUE TITLE
ClickOnce annoyances

### ISSUE THREAD

**Issue by draeath** [msarilar/EDEngineer#59]
ClickOnce removes a ton of control from users, including where files are installed to and control of network connectivity, updates, etc. Users should be given a straight and to the point executable application, instead.

I wasted nearly an hour and a half because of this nonsense, before I was able to get things to work right (because I have a nonstandard environment) - all because a standard installation directory and shortcuts were not placed down by ClickOnce. Instead, there's this ".appref-ms" foolishness.

**Comment by msarilar** [comment]
I admit I picked ClickOnce because it was the easy solution to deploy that and keep users up to date, almost no configuration to do on my side

PR changing the way the software is deployed are welcome :)
