### ISSUE TITLE
Unknown materials

### ISSUE THREAD

**Issue by Athanasius** [msarilar/EDEngineer#6]
On startup I get 'Unknown material, please contact the author !' for:

uncutfocuscrystals
fedcorecomposites
unknownenergysource

**Comment by msarilar** [comment]
Thank you for your report.

I'm taking assumptions:

uncutfocuscrystals : must be one of the crystals? not sure which one
fedcorecomposites : is supposed to be mapped to Core Dynamics Composites
unknownenergysource : I have absolutely no idea

The best way to know is:
1. Go to your log folder C:\Users\%USERNAME%\Saved Games\Frontier Developments\Elite Dangerous and sort the content by date such that you have the most recent one on top
2. In the game, go through your materials/datas one by one and discarding one of them
3. Wait for the game to refresh the logs (hit F5 in the explorer to refresh the files timestamp)
4. If the app throw a popup, you know which it is :)

It's a bit tedious but that's the only way to be exactly sure.

**Comment by Athanasius** [comment]
I've a feeling unknownenergysource may be Unknown Fragment (what an Unknown Artefact turns into if you kill it).  I'll have a look at the amounts I have of candidates for the others tomorrow to see if throwing one away isn't going to cause me problems.

**Comment by Athanasius** [comment]
uncutfocuscrystal (which doesn't seem to be used in anything) is a 'Flawed Focus Crystal'

**Comment by Athanasius** [comment]
unknownenergysource is indeed 'Unknown Fragment'.

**Comment by Athanasius** [comment]
And finally fedcorecomposites is indeed 'Core Dynamics Composites'.

I don't know if you/someone was guessing the internal names for all of those (looking at the current code they're just all-lower-case-strip-the-spaces versions), or if FDev changed something.

**Comment by Athanasius** [comment]
And I've just sent a pull request that fixes these.

**Comment by msarilar** [comment]
Brilliant ! Just a minor mistake I think (check my comment) and I'll accept it

**Comment by msarilar** [comment]
Thanks :) This will be in next version.

**Comment by msarilar** [comment]
Fix deployed, please restart the application

**Comment by Athanasius** [comment]
Looks good here.  Btw is it intended that locking/unlocking the window will spit out the "unknown resource" popups each time, i.e. nagging to get in touch with you ?

**Comment by msarilar** [comment]
what does it say it's missing?

**Comment by Athanasius** [comment]
Oh, nothing new this time, just an observation during the original issue with those 3.

**Comment by msarilar** [comment]
you mean after updating you're still seeing the "unknown material" for the three items supposedly fixed?

**Comment by msarilar** [comment]
oh ok I think I understand what you meant;
when you click on Unlock Window, it actually reloads everything because :

1. I want the "locked window" to be transparent
2. it's not possible to changed the transparency after initialization

So to switch between modes, I need to reinitialize the window.

**Comment by Athanasius** [comment]
Yes, that's what I meant.  It's annoying when you have an unknown material.  Perhaps store something to note you've already carped about that material this session (run of the executeable), and if so stay silent when it's seen again ?

To be honest it's not really going to be an issue for me now, because I won't be constantly swapping locked/unlocked.

**Comment by msarilar** [comment]
I agree but keep in mind that it's temporary... The idea is to ditch that annoying messagebox altogether when we'll be sure every weird log entries have been taken into account.
