### ISSUE TITLE
Unknown Materials: "chemicalprocesssample" "medicaltrialrecords"

### ISSUE THREAD

**Issue by ursineasylum** [msarilar/EDEngineer#602]
"chemicalprocesssample" _appears_ to be an alternative name for "Chemical Sample"-- Odyssey recognizes me as having 8 "Chemical Samples", but EDEngineer says I have 7 of those and 1 of the resource mentioned.

"medicaltrialrecords" _appears_ to be listed as "Medial Records" Data in-game, but does not stack with another resource of the same name in the in-game UI.

**Comment by Gimi1967** [comment]
Most likely owing to discrepancies between Name and Name_Localised in EDEngineer.
Could you possibly post your latest journal file or just the: ShipLockerMaterials event from that file.
