### ISSUE TITLE
Duplicate Odyssey Mats

### ISSUE THREAD

**Issue by artig4n** [msarilar/EDEngineer#603]
I wrote a complete explanation on the forums, here --> https://forums.frontier.co.uk/threads/edengineer-an-overlay-to-track-your-blueprint-progress-in-realtime.305371/post-9268000

Hope it helps.

**Comment by Gimi1967** [comment]
Could you possibly post your latest journal file or just the: ShipLockerMaterials event from that file.
I expect there will be quite a few of these until it's all sorted out.

**Comment by artig4n** [comment]
[Journal.210605175435.01.log](https://github.com/msarilar/EDEngineer/files/6604347/Journal.210605175435.01.log)

**Comment by artig4n** [comment]
[Journal.210605102623.01.log](https://github.com/msarilar/EDEngineer/files/6604349/Journal.210605102623.01.log)

**Comment by Gimi1967** [comment]
Thank you. I see that that one has a diffrent owner ID. (I understand that they are intended to be used for missions and are not stolen). Have you abondoned the missions or do you intend to complete them? 
If this is intentional from FDEV, then there are a few cases.
Are they equal in engineering terms? Can you use both for engineering?
If yes, then ED Engineer can sumerize them and present them as one.
If no, we need to know the difference and see if that is relevant for ED Engineer.

**Comment by artig4n** [comment]
I think all 8 are rewards. I've had a couple missions bug out, though, so it's hard to say for sure. The power regulator is from an abandoned mission, though. I have another that I scavenged.

It appears that you can use them all for engineering. At least they show up in the totals. I have only managed to upgrade one weapon, and it did not require any of my duplicated materials, so I cannot really confirm.

**Comment by Gimi1967** [comment]
You have quite a lot of ShipLockerMaterials, so I'm going to use your journal to do quality checks.
As for the duplicated entries, It's up to @msarilar, but I expect we have to wait a bit and see what comes from FDEV.

**Comment by artig4n** [comment]
Here's a new journal file. I now have even more duplicates, and one triplicate (Power Regulator). I suspect the game itself is bugged on this. I'm sure that one of the Power Regulators is from a mission in which I stole the regulator. The mission giver should have taken it when I turned in the mission, but they did not. One of the regulators I scavenged. And one is from an abandoned mission.

[Journal.210607073119.01.log](https://github.com/msarilar/EDEngineer/files/6611736/Journal.210607073119.01.log)

**Comment by artig4n** [comment]
I got this error with the new version just now:

---------------------------
Error
---------------------------
Something went wrong in parsing your logs, open an issue on GitHub with this information : 

LogEntry = {

  "timestamp": "2021-05-24T15:56:11Z",

  "event": "SellMicroResources",

  "TotalCount": 2,

  "MicroResources": [

    {

      "Name": "medicaltrialrecords",

      "Name_Localised": "Clinical Trial Records",

      "Category": "Data",

      "Count": 1

    },

    {

      "Name": "degradedpowerregulator",

      "Name_Localised": "Degraded Power Regulator",

      "Category": "Item",

      "Count": 1

    }

  ],

  "Price": 39000,

  "MarketID": 3230671872

}

Error:System.ArgumentNullException: Value cannot be null.

Parameter name: key

   at System.Collections.Generic.Dictionary`2.FindEntry(TKey key)

   at EDEngineer.Models.Operations.MaterialTradeOperation.RemoveIngredient(String ingredient, Int32 count)

   at EDEngineer.Utils.JournalEntryConverter.ExtractMicroResourcesSold(JObject data)

   at EDEngineer.Utils.JournalEntryConverter.ExtractOperation(JObject data, JournalEvent journalEvent)

   at EDEngineer.Utils.JournalEntryConverter.ReadJson(JsonReader reader, Type objectType, Object existingValue, JsonSerializer serializer)
---------------------------
OK   
---------------------------

**Comment by msarilar** [comment]
https://github.com/msarilar/EDEngineer/blob/master/EDEngineer/Utils/JournalEntryConverter.cs#L187 crashed here means this https://github.com/msarilar/EDEngineer/blob/master/EDEngineer/Utils/ItemNameConverter.cs#L38 returned null

I'll look into it tonight

**Comment by artig4n** [comment]
You previously asked:
Are they equal in engineering terms? Can you use both for engineering?

I was unable to answer then, but I have now successfully completed a mod which used some of my duplicated items (Digitial Designs, Chemical Inventory). The engineer showed the total number I had (11), with no filtering. However, after completing the mod, I found that the items had not all been taken, and in fact some had been replaced in some way. 

I had 11 Digital Designs before doing the mod. It should have used 10 of them. I had 1 scavenged one (which showed on its own line) and 10 from mission rewards (which showed on their own line). 

After the mod I have 11 still, but they are all on one line. Same with the Chemical Inventory. 

So...this is all kinds of messed up in the game.

You want to see today's journal?

**Comment by jpacelli62** [comment]
Unfortunately, there is no event in the game logs currently indicating that a modification has been made, so the application cannot detect it.
However after a while all the ingredients should update during the ShipLockerMaterials event.
You can use stolen & mission items to upgrade a suit or weapon but I don't know for engineer modifications.
Your error should be fixed by my pull request.
