### ISSUE TITLE
Item totals wrong , but only due to Fdev incompetence

### ISSUE THREAD

**Issue by Wullailhuit** [msarilar/EDEngineer#612]
edengineer is doing it correctly ,  elite isn't, but still counts the incorrect information as available for unlocking or upgrading.

the same items are shown on different lines in-game with different totals , but still count as available to be used for unlocks / upgrades etc.

here is an example from the journal file.

{ "Name":"digitaldesigns", "Name_Localised":"Digital Designs", "OwnerID":0, "Count":5 }, { "Name":"digitaldesigns", "Name_Localised":"Digital Designs", "OwnerID":437809, "Count":4 },

2 entries for  digitaldesigns , 1 marked as me as the owner , 2 marked a "OwnerID":0 , game shows both in seperate entries in-game , but I can use all 9 for the backpack upgrade.

I don't know if you can fudge it to show the total

**Comment by msarilar** [comment]
thanks for the report

in which event is this happening?

**Comment by Wullailhuit** [comment]
I'm not sure , I've been looting and stealing mats anb downloading data from powered and unpowered bases for days now.

**Comment by Wullailhuit** [comment]
![in-app](https://user-images.githubusercontent.com/85571267/121458782-ea22d100-c9a1-11eb-8d74-64177a45f849.jpg)
![in-ship](https://user-images.githubusercontent.com/85571267/121458785-eabb6780-c9a1-11eb-915b-32fb97502b6f.jpg)
[Journal.210610040234.01.log](https://github.com/msarilar/EDEngineer/files/6628111/Journal.210610040234.01.log)

Now it's counting only those items with OwnerID:0

I've attached images of in-app and in-ship as well as my latest journal file , hope it helps.
