### ISSUE TITLE
Data/Goods on several rows in ED doesn't sum in EDEngineer

### ISSUE THREAD

**Issue by bbbkada** [msarilar/EDEngineer#614]
Noc data in edEngineer says 1 form me, but in ED it looks like this.
Same with Goods, like power regulators and so on..

![nocdata](https://user-images.githubusercontent.com/11602498/121517362-92ab5200-c9ef-11eb-8c74-4dd92310ef50.PNG)

**Comment by msarilar** [comment]
I think @jpacelli62 fixed this in 464c7379c85ab7fcfd415def5c105213e309b96b
I'll deploy tonight

**Comment by jpacelli62** [comment]
Yes, now I merge the multiple rows into one in the ShipLockerMaterials event

**Comment by texaspete** [comment]
I still have this problem in 1.1.6.6, after doing a **Reload all data**.

I have acquired many Power Regulators from missions: they are a material you are given which you need to complete the mission. If you fail the mission, you keep the material. In the game, they show on separate lines in the inventory. In my journal, they appear thus:

`{ "timestamp":"2021-06-16T18:08:16Z", "event":"ShipLocker","Items":[
{ "Name":"largecapacitypowerregulator", "Name_Localised":"Power Regulator", "OwnerID":1038026, "MissionID":781850735, "Count":1 },
{ "Name":"largecapacitypowerregulator", "Name_Localised":"Power Regulator", "OwnerID":1038026, "MissionID":782208344, "Count":1 },
{ "Name":"largecapacitypowerregulator", "Name_Localised":"Power Regulator", "OwnerID":1038026, "MissionID":782208365, "Count":1 },
{ "Name":"largecapacitypowerregulator", "Name_Localised":"Power Regulator", "OwnerID":1038026, "MissionID":783003652, "Count":1 },
{ "Name":"largecapacitypowerregulator", "Name_Localised":"Power Regulator", "OwnerID":1038026, "MissionID":783003664, "Count":1 },
{ "Name":"largecapacitypowerregulator", "Name_Localised":"Power Regulator", "OwnerID":1038026, "MissionID":783003675, "Count":1 },
{ "Name":"largecapacitypowerregulator", "Name_Localised":"Power Regulator", "OwnerID":1038026, "MissionID":783003689, "Count":1 },
{ "Name":"largecapacitypowerregulator", "Name_Localised":"Power Regulator", "OwnerID":1038026, "MissionID":783003694, "Count":1 },
{ "Name":"largecapacitypowerregulator", "Name_Localised":"Power Regulator", "OwnerID":1038026, "MissionID":783010595, "Count":1 },
{ "Name":"largecapacitypowerregulator", "Name_Localised":"Power Regulator", "OwnerID":1038026, "MissionID":783010602, "Count":1 },
{ "Name":"largecapacitypowerregulator", "Name_Localised":"Power Regulator", "OwnerID":1038026, "MissionID":783010619, "Count":1 },
{ "Name":"largecapacitypowerregulator", "Name_Localised":"Power Regulator", "OwnerID":0, "Count":1 } ],`

In EDEngineer, it shows I have only 1 Power Regulator:

![image](https://user-images.githubusercontent.com/19603891/122347605-21fdbb80-cf42-11eb-88c2-9d2f2fe437df.png)

**Comment by jpacelli62** [comment]
Good to know :) 
Thanks for the report.
I think that the issue can be closed @msarilar

**Comment by msarilar** [comment]
thank you
