### ISSUE TITLE
No Auto updates to inventory/location

### ISSUE THREAD

**Issue by Net-Slayer** [msarilar/EDEngineer#616]
At some point _before_ Odyssey, EDEngineer would grab the amount of items in my inventory...
It would also track the increase/decrease of these items and my current location.
However now it says I'm always at Sol (I'm far from Sol).
And it never grabs or syncs my current materials.

**Comment by Wyrdstock** [comment]
I'm not getting auto updates on the latest version from yesterday

**Comment by dQeLse** [comment]
can confirm no auto updates

**Comment by msarilar** [comment]
will look into this tonight

@jpacelli62 do you know if https://github.com/msarilar/EDEngineer/pull/615 addresses the issue?

**Comment by jpacelli62** [comment]
> @jpacelli62 do you know if #615 addresses the issue?

Frontier changed their log format with the latest update. I fixed the mission completed reward but I cannot confirm that there is a link with the current location. Maybe a crash while parsing can cause it.
With the next version of EdEngineer I had to reread all logs and the location looks good after.

**Comment by jpacelli62** [comment]
Location will be fixed with https://github.com/msarilar/EDEngineer/pull/619
