### ISSUE TITLE
New version published 1.1.6.7?

### ISSUE THREAD

**Issue by Wyrdstock** [msarilar/EDEngineer#618]
I can see a new version was completed yesterday... but the current release  is 1.1.6.6. Not sure how it works, does the new version have to be released or am I missing something?

**Comment by msarilar** [comment]
![image](https://user-images.githubusercontent.com/5569959/121806982-7529f280-cc52-11eb-8873-c68869ec16dd.png)

I simply didn't publish it on github but the release is out
