### ISSUE TITLE
Suit and Weapon grade upgrade

### ISSUE THREAD

**Issue by davidalex791** [msarilar/EDEngineer#623]
For version 1.1.6.7 I tried to find weapons and suit grade upgrade 1-5 but can no longer find it, I've enabled all filters possible as well as engineers. I'm pretty sure previous version had this feature, was it removed recently?

**Comment by msarilar** [comment]
make sure you have the checkboxes ticked in the filter (the ones in the line  between the blueprints list & the dropdown)

**Comment by davidalex791** [comment]
ah, the Merchant one, got it. thank you very much!
