### ISSUE TITLE
F-Secure shows malware in setup exe

### ISSUE THREAD

**Issue by KR1LL3N** [msarilar/EDEngineer#624]
![Capture](https://user-images.githubusercontent.com/33643480/122298253-22567200-cec2-11eb-8670-8c204040fecb.PNG)
 I downloaded the application but it shows that there is an malware hidden in the setup file. I Want to make sure its not actually malware. if not please make it so that it doesn't trigger a false positive on the virus scanner

**Comment by msarilar** [comment]
you can check it out on virus total https://www.virustotal.com/gui/file/7bc3fe704cdb730c575f13560b82ed2676df8be2e29f816726ec0d3b132a9de3/detection
the setup itself doesn't contain much but it downloads the app for you (and its update) so the behaviour might be flagged by some AV

alternatively you can compile the sources yourself and run EDEngineer directly (clone the repo then open the .sln file with https://visualstudio.microsoft.com/vs/community/ and then launch the EDEngineer project)
