### ISSUE TITLE
Recipes with error 

### ISSUE THREAD

**Issue by AlexsampBsb** [msarilar/EDEngineer#628]
Magazine size and Reload speed use electromagnets, not metal coils.
https://inara.cz/equipment-blueprint/12/ 

o7
CMDR Angilus

**Comment by Gimi1967** [comment]
Can anyone take a screen shoot of the recipie an post here, preferably seperate screen shots for Takada, Manticore and Kinematic type weapons

**Comment by seedubya** [comment]
Magazine Size:
* Kinetic: 
![image](https://user-images.githubusercontent.com/59203802/227765495-fe144ae9-a161-4631-a4d1-5c6cf452a3a8.png)
* Plasma: 
![image](https://user-images.githubusercontent.com/59203802/227765367-27928ce2-aec0-47d1-8cf8-0ad77bb3d768.png)
* Thermal: 
![image](https://user-images.githubusercontent.com/59203802/227765451-40aa20fc-9ee4-45a0-a6c4-4163bf8bef81.png)


Reload Speed:
* Kinetic: 
![image](https://user-images.githubusercontent.com/59203802/227765507-12567e1e-d794-4b23-8f04-99d1698c75b6.png)
* Plasma: 
![image](https://user-images.githubusercontent.com/59203802/227765409-db1e1184-e847-49b8-b0bb-8eee8760c061.png)
* Thermal: 
![image](https://user-images.githubusercontent.com/59203802/227765469-516206b8-a58e-44b6-bfea-28db91a0a867.png)

**Comment by seedubya** [comment]
@msarilar : this has already been fixed.

**Comment by msarilar** [comment]
thank you @seedubya
