### ISSUE TITLE
"Something went wrong with your parsing logs" error

### ISSUE THREAD

**Issue by redtraveller** [msarilar/EDEngineer#629]
After completely removing and re installing EDEngineer I get this error with a long list of code below every time I launch it. EDE wont open until I dismiss the error window and then it seems to work fine... or so it looks. I cant seem to be able to copy the text in the error message unless I do a screen capture. Any ideas?

https://i.imgur.com/nwApJjt.png

**Comment by msarilar** [comment]
you can hit ctrl+C while the error window is focused which will copy the content and allow you to paste here

**Comment by redtraveller** [comment]
---------------------------
Error
---------------------------
Something went wrong in parsing your logs, open an issue on GitHub with this information : 

LogEntry = {

  "timestamp": "2021-07-02T21:02:52Z",

  "event": "SellMicroResources",

  "TotalCount": 131,

  "MicroResources": [

    {

      "Name": "residentialdirectory",

      "Name_Localised": "Residential Directory",

      "Category": "Data",

      "Count": 1

    },

    {

      "Name": "pyrolyticcatalyst",

      "Name_Localised": "Pyrolytic Catalyst",

      "Category": "Item",

      "Count": 5

    },

    {

      "Name": "deepmantlesample",

      "Name_Localised": "Deep Mantle Sample",

      "Category": "Item",

      "Count": 23

    },

    {

      "Name": "infinity",

      "Category": "Item",

      "Count": 8

    },

    {

      "Name": "propaganda",

      "Category": "Data",

      "Count": 2

    },

    {

      "Name": "trueformfossil",

      "Name_Localised": "True Form Fossil",

      "Category": "Item",

      "Count": 4

    },

    {

      "Name": "incidentlogs",

      "Name_Localised": "Incident Logs",

      "Category": "Data",

      "Count": 1

    },

    {

      "Name": "campaignplans",

      "Name_Localised": "Campaign Plans",

      "Category": "Data",

      "Count": 3

    },

    {

      "Name": "explorationjournals",

      "Name_Localised": "Exploration Journals",

      "Category": "Data",

      "Count": 5

    },

    {

      "Name": "castfossil",

      "Name_Localised": "Cast Fossil",

      "Category": "Item",

      "Count": 7

    },

    {

      "Name": "slushfundlogs",

      "Name_Localised": "Slush Fund Logs",

      "Category": "Data",

      "Count": 1

    },

    {

      "Name": "inorganiccontaminant",

      "Name_Localised": "Inorganic Contaminant",

      "Category": "Item",

      "Count": 2

    },

    {

      "Name": "travelpermits",

      "Name_Localised": "Travel Permits",

      "Category": "Data",

      "Count": 1

    },

    {

      "Name": "factiondonatorlist",

      "Name_Localised": "Faction Donator List",

      "Category": "Data",

      "Count": 1

    },

    {

      "Name": "insight",

      "Category": "Item",

      "Count": 4

    },

    {

      "Name": "petrifiedfossil",

      "Name_Localised": "Petrified Fossil",

      "Category": "Item",

      "Count": 7

    },

    {

      "Name": "compactlibrary",

      "Name_Localised": "Compact Library",

      "Category": "Item",

      "Count": 2

    },

    {

      "Name": "hush",

      "Category": "Item",

      "Count": 1

    },

    {

      "Name": "purchaserecords",

      "Name_Localised": "Purchase Records",

      "Category": "Data",

      "Count": 1

    },

    {

      "Name": "kompromat",

      "Category": "Data",

      "Count": 1

    },

    {

      "Name": "insightdatabank",

      "Name_Localised": "Insight Data Bank",

      "Category": "Item",

      "Count": 5

    },

    {

      "Name": "degradedpowerregulator",

      "Name_Localised": "Degraded Power Regulator",

      "Category": "Item",

      "Count": 1

    },

    {

      "Name": "personaldocuments",

      "Name_Localised": "Personal Documents",

      "Category": "Item",

      "Count": 8

    },

    {

      "Name": "personalcomputer",

      "Name_Localised": "Personal Computer",

      "Category": "Item",

      "Count": 9

    },

    {

      "Name": "biochemicalagent",

      "Name_Localised": "Biochemical Agent",

      "Category": "Item",

      "Count": 2

    },

    {

      "Name": "purchaserequests",

      "Name_Localised": "Purchase Requests",

      "Category": "Data",

      "Count": 1

    },

    {

      "Name": "cocktailrecipes",

      "Name_Localised": "Cocktail Recipes",

      "Category": "Data",

      "Count": 3

    },

    {

      "Name": "californium",

      "Category": "Item",

      "Count": 6

    },

    {

      "Name": "nutritionalconcentrate",

      "Name_Localised": "Nutritional Concentrate",

      "Category": "Item",

      "Count": 2

    },

    {

      "Name": "internalcorrespondence",

      "Name_Localised": "Internal Correspondence",

      "Category": "Data",

      "Count": 3

    },

    {

      "Name": "accidentlogs",

      "Name_Localised": "Accident Logs",

      "Category": "Data",

      "Count": 1

    },

    {

      "Name": "lazarus",

      "Category": "Item",

      "Count": 3

    },

    {

      "Name": "universaltranslator",

      "Name_Localised": "Universal Translator",

      "Category": "Item",

      "Count": 3

    },

    {

      "Name": "interrogationrecordings",

      "Name_Localised": "Interrogation Recordings",

      "Category": "Data",

      "Count": 1

    },

    {

      "Name": "chemicalsample",

      "Name_Localised": "Chemical Sample",

      "Category": "Item",

      "Count": 2

    },

    {

      "Name": "photoalbums",

      "Name_Localised": "Photo Albums",

      "Category": "Data",

      "Count": 1

    }

  ],

  "Price": 4247000,


Thanks, here you go:
  "MarketID": 3226858240

}

Error:System.ArgumentNullException: Value cannot be null.

Parameter name: key

   at System.Collections.Generic.Dictionary`2.FindEntry(TKey key)

   at EDEngineer.Models.Operations.MaterialTradeOperation.RemoveIngredient(String ingredient, Int32 count)

   at EDEngineer.Utils.JournalEntryConverter.ExtractMicroResourcesSold(JObject data)

   at EDEngineer.Utils.JournalEntryConverter.ExtractOperation(JObject data, JournalEvent journalEvent)

   at EDEngineer.Utils.JournalEntryConverter.ReadJson(JsonReader reader, Type objectType, Object existingValue, JsonSerializer serializer)
---------------------------
OK   
---------------------------

**Comment by msarilar** [comment]
thanks, should be fixed now if you restart the app

**Comment by redtraveller** [comment]
Thanks a lot! No error this time :)
