### ISSUE TITLE
List for Greater Range is wrong

### ISSUE THREAD

**Issue by CmdrHogweed** [msarilar/EDEngineer#642]
Here is a screen shot showing EDEngineer's list and the actual requirements:

![WBeck GRange](https://user-images.githubusercontent.com/87772908/126522880-e7a5d68b-7fa3-4b06-9438-18b1886a7f84.png)

**Comment by Gimi1967** [comment]
Greater range has different recipes for each manufacturer. 
Could you please provide information about which weapon you were modifying.
Additional screenshots for other weapon types would also be great.

**Comment by CmdrHogweed** [comment]
Ok, I've been to every engineer and saved screen shots of the recipes. The ones that have different requirements for different weapons are Greater Range, Hip Fire Accuracy and Headshot Damage.

![Domino Green - Greater Range - Kinetic](https://user-images.githubusercontent.com/87772908/128645954-d96df0fc-c454-4bc6-8757-ed107413bdb8.png)

![Domino Green - Greater Range - Plasma](https://user-images.githubusercontent.com/87772908/128645966-367a882c-fddd-49dd-9cbc-d1bdabcb41ae.png)

![Domino Green - Greater Range - Thermal](https://user-images.githubusercontent.com/87772908/128645970-40fc9845-b83d-4828-ad2c-fdc062a22d0f.png)

![Terra Velasquez - Improved Hip Fire Accuracy - Kinetic](https://user-images.githubusercontent.com/87772908/128645978-db3f846c-56ec-4767-a590-808d3fc3baf3.png)

![Terra Velasquez - Improved Hip Fire Accuracy - Plasma](https://user-images.githubusercontent.com/87772908/128645987-72839b68-cee6-437e-86e4-6b0e3654301e.png)

![Terra Velasquez - Improved Hip Fire Accuracy - Thermal](https://user-images.githubusercontent.com/87772908/128645991-923d0970-0e57-4232-ab61-af4e811bfb7b.png)

![Uma Laszlo - Headshot Damage - Kinetic](https://user-images.githubusercontent.com/87772908/128646002-639be691-03d4-4b45-bc2e-9b52134a42ef.png)

![Uma Laszlo - Headshot Damage - Plasma](https://user-images.githubusercontent.com/87772908/128646006-071e6fbc-271c-4695-9367-744399209793.png)

![Uma Laszlo - Headshot Damage - Thermal](https://user-images.githubusercontent.com/87772908/128646011-698eabb0-7ff6-4d29-95fb-43411b2a619e.png)

**Comment by Gimi1967** [comment]
This is great. I'm away for the rest of the week, but I'll have a look this weekend unless somebody beats me to it.
