### ISSUE TITLE
Audio Masking Recipe is missing

### ISSUE THREAD

**Issue by artig4n** [msarilar/EDEngineer#647]
For any on-foot weapon

5 Audio Logs
10 Patrol Routes
10 Scrambler
15 Transmitter
5 Circuit Board

**Comment by seedubya** [comment]
@msarilar : Looks like this has already been done:

![image](https://user-images.githubusercontent.com/59203802/227725583-43c90e31-0819-461b-bade-0de0ea004ace.png)

Also - in the code base:

```json
{
    "Type": "Weapon",
    "Name": "Audio Masking",
    "Engineers": [
      "Yarden Bond"
     ...
```

**Comment by msarilar** [comment]
thank you @seedubya
