### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by Alekhoff** [msarilar/EDEngineer#65]
Hey,

Been using the application alot latley, it so good! Im glad we finally got an automated system for egineering.

But i find myself really wanting to sort Materials/Data by Ammount (Decreasing/Increasing) and the rarity of the material/data. It would be very neat to check fast what the most rare materials are.

Thanks for making such a good app!

**Comment by msarilar** [comment]
yeah that will come with #68, a overhaul of the left side of the window :)
