### ISSUE TITLE
Shopping list mismatch from game

### ISSUE THREAD

**Issue by MOOOOs** [msarilar/EDEngineer#651]
Armor experimental effect Deep Plating needs 2 Molybdenum its correct in game and in EDE but hull reinforcement package needs 3 Molybdenum for DP it only shows 2 in EDE.

**Comment by alex140i** [comment]
bulk heads (main armor) and hull reinforcements have 2 different crafting needs for deep plating    could be that ede only has the one for the bulkheads and needs to have the hull reinforcements made a seperate thing

**Comment by seedubya** [comment]
@msarilar : Deep Plating for both Armour and Hull Reinforcement appear to be correct now.

**Comment by msarilar** [comment]
thank you @seedubya
