### ISSUE TITLE
Window position

### ISSUE THREAD

**Issue by P51DDangerous** [msarilar/EDEngineer#653]
Im not sure what happened, but now when I run EDEngineer, the taskbar icon shows ok, but the program window is rendered off the left side of my left monitor.  Clicking on the taskbar icon will show a plain  white window moving from the taskbar to the left side of the left monitor.  Have you ever heard of such a thing?

**Comment by msarilar** [comment]
what happens if you right click the taskbar icon and hit "reset window position"?

**Comment by P51DDangerous** [comment]
This is getting crazy.  When I click the "installer here" link on github to download the newest version, Im redirected to a page with one word:  Forbidden.

**Comment by msarilar** [comment]
hey yes I used to rely on https://rawgit.com/ to host the binaries
I fixed the URL now it should point to the correct one

it's unrelated to the issue you're having though

**Comment by P51DDangerous** [comment]
Ok I found the setting "Reset Window Pos" I am back in business!

Thanks much for the prompt response.  You have created a great tool.

Stay Dangerous, Commander!
