### ISSUE TITLE
403 forbidden clicking install link

### ISSUE THREAD

**Issue by jeffstokes72** [msarilar/EDEngineer#655]
Link on git project: https://cdn.rawgit.com/msarilar/EDEngineer/master/EDEngineer/releases/setup.exe

fails with 403 forbidden.

**Comment by msarilar** [comment]
thanks for the report

URL should be https://raw.githubusercontent.com/msarilar/EDEngineer/master/EDEngineer/releases/setup.exe

I'll update the links 👍
