### ISSUE TITLE
Micro SuperCapacitor Missing from Circuits Section

### ISSUE THREAD

**Issue by bWildcard** [msarilar/EDEngineer#656]
In latest Release Micro SuperCapacitors are missing from the Circuits Section.

Also would it be possible to enable re-ordering of Sub Sections?
(IE) Currently
Chemicals
Circuits
All Data
Items
Than Tech

Allowing to Re-Order or maintain consistency 
Chemicals
Circuits
Tech
Items
Data  

or just to be able to order how you want?

As well as an Added Search Function would be a great addition.

And thank you for all the hard work you've been doing and putting into this great program Kudo's +1

**Comment by seedubya** [comment]
@msarilar : also done by the look of it?

![image](https://user-images.githubusercontent.com/59203802/227725739-4000ee73-3835-43e0-bf4a-25f1af9eaa5c.png)

**Comment by msarilar** [comment]
thank you @seedubya
