### ISSUE TITLE
Missing commodity on blueprint

### ISSUE THREAD

**Issue by Alekhoff** [msarilar/EDEngineer#67]
The Heat Sink Ammo Capacity (Grade 3) blueprint needs CMM Composite to be crafted, it is missing in the app :)

**Comment by msarilar** [comment]
Thanks for the report ! Will be fixed in next deploy : https://github.com/msarilar/EDEngineer/commit/7a3b1b774b5206a1db5020e9d4539bb12dde27c6

**Comment by msarilar** [comment]
deployed in 1.0.2
