### ISSUE TITLE
Missing the new Salvation Weapon: Modified Plasma Charger

### ISSUE THREAD

**Issue by eisbaer9** [msarilar/EDEngineer#675]
Hi, i'm missing the new Salvation Modified Guardian Plasma Charger.

Weapon: Modified Plasma Charger (FIXED) (CLASS: 1)
1 Guardian Weapon Blueprint Segment
3 Guardian Power Cell
3 Guardian Sentinel Weapon Parts
4 Guardian Technology Component
2 Arsen

Weapon: Modified Plasma Charger (FIXED) (CLASS: 2)
1 Guardian Weapon Blueprint Segment
5 Guardian Power Conduit
5 Guardian Sentinel Weapon Parts
4 Arsenic
2 Power Transfer Bus

Can you please add the Weapon, thanks.

12.02.2022 checked the Materials and made Screenshots
Material are now correct

**Comment by eisbaer9** [comment]
[blueprints.zip](https://github.com/msarilar/EDEngineer/files/8103822/blueprints.zip)

I have updated the blueprints.json, see attached zip, with the Mdoified Plasma Charger with the amount of materials needed since the 12.02.2022.

**Comment by OzDruiD** [comment]
Did you create a pull request for this?
Is there a way to temporarily import\use your blueprints.json file?
