### ISSUE TITLE
Feature Request - Material Details

### ISSUE THREAD

**Issue by punkerich** [msarilar/EDEngineer#68]
Wouldn't it be great to have an expandable description (editable?) on where to find the mats/data by clicking on them? Like on Inara?

**Comment by msarilar** [comment]
@Alekhoff

> Hey,
> 
> Been using the application alot latley, it so good! Im glad we finally got an automated system for egineering.
> 
> But i find myself really wanting to sort Materials/Data by Ammount (Decreasing/Increasing) and the rarity of the material/data. It would be very neat to check fast what the most rare materials are.
> 
> Thanks for making such a good app!

**Comment by msarilar** [comment]
@jfurtner

> I'd like to be able to tell the difference between regular commodities that can be bought and commodities that are only mission rewards in the lists. Other then dreaded modular terminals I never remember which commodities are only mission rewards and always have to look it up. I know I can relatively easily get or mine the other commodities, but some are harder to come by.

**Comment by msarilar** [comment]
deployed in 1.0.2
