### ISSUE TITLE
App doesn't start on Windows 11

### ISSUE THREAD

**Issue by seedubya** [msarilar/EDEngineer#683]
It did work for a while, and recently it just hangs on startup. I have tried the steps you list in the troubleshooting which do not resolve it either.
Cleaned out the app, etc., and now the error looks like this when using the setup.exe of the .application link:

```
Application cannot be started. Contact the application vendor.
```

An error log is produced - attached.

[O7GNVB6F.log](https://github.com/msarilar/EDEngineer/files/8386592/O7GNVB6F.log)

Its a great app - been using it for a year or so!

**Comment by msarilar** [comment]
Can you check whether the .NET framework is properly installed? The logs refer to the code 0x800736B3 which, when searching on the internet, seems to indicate it’s linked to that.

**Comment by seedubya** [comment]
hi - tried that, no change. is there a complete (clean) de-install process for this app so i can try from clean again? This app used to work fine, i've not used it for a couple of weeks, and now it refuses to start

**Comment by msarilar** [comment]
you can uninstall the app like any other but the app does not install .NET runtime for you (if I remember correctly)

make sure you have the runtime installed https://www.microsoft.com/download/details.aspx?id=49981

**Comment by seedubya** [comment]
Doesn't look like it's win 11 friendly. If it's looking like it's 11 specific then probably one for later.

**Comment by Billkyriaf** [comment]
Just installed in windows 11:

>Edition	Windows 11 Pro
Version	21H2
Installed on	‎4/‎17/‎2022
OS build	22000.613
Experience	Windows Feature Experience Pack 1000.22000.613.0
.NET Framework 4.8

The program works fine out of the box, no additional installs are required.

**Comment by seedubya** [comment]
That's the thing - it did, but does not now. I tried installing .net framework 4.8 as mentioned and it reports it is already present.

Log file is attached - this is consistent across attempts.

[T93PLS9N.log](https://github.com/msarilar/EDEngineer/files/8515604/T93PLS9N.log)

**Comment by msarilar** [comment]
I had an idea, can you try and restart the app? it should update to a new version that includes some required dlls, they should come from windows but my guess is your win11 install somehow removed them from the path

**Comment by seedubya** [comment]
after the initial issues, i deinstalled and removed the app and references to it as it refused to start.
Downloading the latest build, and attempting to install again gives the errors in the log file above.

**Comment by seedubya** [comment]
just coming back to this - confirmed .net 4.8 is installed ok. i've been thro the troubleshooting steps on here and the ones listed on the site, still no luck.

![Screenshot 2022-05-17 072546](https://user-images.githubusercontent.com/59203802/168744518-0a0133c5-9c9b-4e63-9fbf-dba733e2e81f.png)

**Comment by seedubya** [comment]
Actually - scrub that. i've got it to work by the following:

* remove all the content under %user%/appdata/local/apps/2.0/
* reboot

:warning: this will nuke any/all oneclick apps you may have installed.
