### ISSUE TITLE
External json stored mats file

### ISSUE THREAD

**Issue by Shemuev** [msarilar/EDEngineer#69]
Ey msarilar!, congrats for this great work.

I'm using this wonderful app with Spanish translation, and i can see a big potential for use it with voiceattack API called "VATextReader". This API can read xml and json files, If you could enable an real time copy of json stored mats file, everyone could use it to develop voice commands to request real time cargo information, very useful and smart :)

Regards,
Shemuev

**Comment by Andargor** [comment]
I support this request, for a different reason, as I want to import the material counts to Excel for further analysis. An external dump in JSON and/or CSV or tab delimited format would be great.

**Comment by Andargor** [comment]
It looks like the app doesn't store the actual amounts, but instead uses a manual amount file in C:\Users\<user>\AppData\Local\EDEngineer and then reads the logs to apply modifiers to it.

**Comment by Shemuev** [comment]
I know Andargor, and i know the manual changes json, but it isn't enough to make precise queries for amounts or another kind information about stored cargo/materials/data with voiceattack commands.

**Comment by msarilar** [comment]
I'm thinking about adding an optional local server using [suave](https://suave.io) library, because since I don't really care about the feature I need the development to be at least fun :D

You would have a `http://localhost:XXXX` server running which you could query like:
`COMMANDER_NAME/materials`
`COMMANDER_NAME/data`
`COMMANDER_NAME/commodities`
`COMMANDER_NAME/cargo`
`COMMANDER_NAME/blueprints`
`COMMANDER_NAME/favoriteBlueprints`

And based on the HTTP request header (or the extension given), I would give you the data requested (as json, xml, csv, whatever).

For example, typing `http://localhost:8083/Hg/materials.xml` would output the current materials in xml format for Hg (which is my commander's name).

Is that something usable by VATextReader? Also, do you guys consider that a reasonable way to export data?

**Comment by Shemuev** [comment]
Hi msarilar!

Thx for answer, this feature seems good, but i think in the beginning is enough with a json stored material copy in the same directory of manual changes. It's possible generate a stored mats json copy and update at the same time when a mat change occurs?

Thx in advance :)

**Comment by msarilar** [comment]
the server is ready, gonna deploy this weekend :)
https://github.com/msarilar/EDEngineer/wiki/API
https://github.com/msarilar/EDEngineer/wiki/API-Reference

**Comment by msarilar** [comment]
deployed in 1.0.3.0

if you have any idea for new routes we could add for the server, please open a new feature request !
[the server's code](https://github.com/msarilar/EDEngineer/blob/master/EDEngineer.Server/Server.fs) is pretty lightweight (thanks to @SuaveIO) and should be pretty readable if you feel like adding the route yourself.

**Comment by Shemuev** [comment]
I have a doubt

can be the request stored like a file (xml, json) in a local path not only is a browser?

If this is possible, can you show me an example?

**Comment by msarilar** [comment]
not sure I understand quite right what you want ; you can save the query result you see in your browser with ctrl+S

**Comment by Shemuev** [comment]
My fault,

I thought that this new feature allowed to save the query result in a file in the desired path. This make it harder to work with Voice attack, because i can't save the result without make more direct interaction with browser.

Thanks again

**Comment by msarilar** [comment]
You can't make voice attack point to a URL rather than a file ?

**Comment by msarilar** [comment]
otherwise nothing keeps you  from writing a quick powershell / wget script to periodically download  the query result http://superuser.com/a/252038/318903

**Comment by Shemuev** [comment]
I'm using a external plugin to make possible read files, Voice Attack can't read file for itself, this plugin don't allow to read url results.

**Comment by msarilar** [comment]
do you use this plugin ? https://groups.google.com/forum/#!msg/voiceattack/VotudmB84hE/AHXWKT2liesJ

it says :

> The plugin adds commands for extracting content from plain text or XML files, locally or over the Internet, and push it back to VoiceAttack for Text-to-Speech or any other use.

**Comment by Shemuev** [comment]
I'm going to check it, thanks

**Comment by Shemuev** [comment]
Ey!

VATextReader it's now obsolete and do not work with VA no more, but it have a substitute:

VAExtensions: [https://github.com/Antaniserse/VAExtensions](url)

It's works properly extracting data from url source.

**Comment by msarilar** [comment]
alright great!
if you write any script or stuff (or whatever VA consumes, I don't use it so I don't know how it works) that could benefit other users, don't hesitate to open a new wikipage (I think you can edit it, but let me know if you can't) !

**Comment by Shemuev** [comment]
Sure!

The problem will be that my command will use voice inputs in Spanish and it should be translated, but the base command that performs the queries is generic for all languages, only the section that performs the url cargo query should be adapted to be performed in the desired language.

**Comment by msarilar** [comment]
no worries ; when you're ready to share, you can post it [on the forums](https://forums.frontier.co.uk/showthread.php/305371-EDEngineer-an-overlay-to-track-your-blueprint-progress-in-realtime/page6) too :)

**Comment by Shemuev** [comment]
And here is! Thanx Max!

https://github.com/Shemuev/CIVAQUERY
