### ISSUE TITLE
Feature request - differentiate between commodities and mission rewards

### ISSUE THREAD

**Issue by jfurtner** [msarilar/EDEngineer#70]
I'd like to be able to tell the difference between regular commodities that can be bought and commodities that are only mission rewards in the lists. Other then dreaded modular terminals I never remember which commodities are _only_ mission rewards and always have to look it up. I know I can relatively easily get or mine the other commodities, but some are harder to come by.

**Comment by msarilar** [comment]
yeah that's in the pipes

#68
