### ISSUE TITLE
Sirius Heatsink Technology craft missing

### ISSUE THREAD

**Issue by Evan109** [msarilar/EDEngineer#708]
Sirius heatsink [A5 Sirius Heatsink Launcher] is not present in the list of engineering/technologies.
Materials Required:
8 Mechanical Scrap [Manufactured]
5 Mechanical Components [Manufactured]
6 Niobium [Raw]
6 Vanadium [Raw]
![image](https://user-images.githubusercontent.com/35783870/206107152-4e338c5c-77d3-4f45-b618-dfb03c373de0.png)

**Comment by seedubya** [comment]
@msarilar : fixed under #724

**Comment by msarilar** [comment]
thank you @seedubya
