### ISSUE TITLE
breizhator log

### ISSUE THREAD

**Issue by lordbzh** [msarilar/EDEngineer#71]
[Elite Dangerous.zip](https://github.com/msarilar/EDEngineer/files/601547/Elite.Dangerous.zip)

**Comment by lordbzh** [comment]
Somes issues with sometimes few Data (Decoded emission data, etc...) showing wrong value ....all the rest is very ok with no error.

**Comment by msarilar** [comment]
found the bug ! #122 

fixed it in latest update
