### ISSUE TITLE
New Problem with recent update

### ISSUE THREAD

**Issue by rbradh53** [msarilar/EDEngineer#727]
Thanks for your quick response to my last issue and thank you for the great program that have provided for us.
I'm sorry to bother you with a new problem:
![Error](https://user-images.githubusercontent.com/79338607/226132572-6774c87f-44cf-4379-9a91-40ce6d749e00.png)

**Comment by seedubya** [comment]
this was resolved ( #718 ) in the latest release - can you check and confirm please?

**Comment by msarilar** [comment]
thank you @seedubya

**Comment by seedubya** [comment]
@msarilar could we re-open this one pls - i have the same issue with the latest build:

![Interdiction Borked](https://user-images.githubusercontent.com/59203802/236918043-402cfa51-42a7-436e-bf9c-ba2dcf89b579.png)

Either my update to the ref data is borked (it did get past a linter) or its a code problem?
