### ISSUE TITLE
Add synthesis as blueprints

### ISSUE THREAD

**Issue by msarilar** [msarilar/EDEngineer#81]
We could add the synthesis as blueprints, with "Synthesis" as the engineer like this (name of the blueprint would be the [bonus of the synthesis](http://elite-dangerous.wikia.com/wiki/Synthesis)):

      {
        "Type": "SRV Ammo Restock",
        "Name": "None",
        "Engineers": [ "Synthesis" ],
        "Ingredients": [
          {
            "Name": "Sulphur",
            "Size": 2
          },
          {
            "Name": "Phosphorus",
            "Size": 1
          }
        ],
        "Grade": 1
      }

PR welcome :)

**Comment by ravstar52** [comment]
Hey, i have the new file ready. Can't push to a new branch though. Do I need access? (#GithubNewb)

**Comment by msarilar** [comment]
hey @ravstar52 
thanks for taking the task!

you need to fork the repo, do your changes in your fork, and submit a pull request

thanks again :) can't wait for the PR

**Comment by msarilar** [comment]
deployed in 1.0.2.3 !
