### ISSUE TITLE
New data for Zacariah Nemo :  Fragment Cannon - Double Shot (Grade 5)

### ISSUE THREAD

**Issue by lordbzh** [msarilar/EDEngineer#91]
[screenshot ](http://image.noelshack.com/fichiers/2016/47/1479733454-screenshot-0099.png)

**Comment by msarilar** [comment]
great! thanks for the report

don't hesitate to update the blueprints json file (https://github.com/msarilar/EDEngineer/blob/master/EDEngineer/Resources/Data/blueprints.json, a bit big so it's slow to load) and open a PR directly :)

**Comment by msarilar** [comment]
actually the blueprint already exists ! https://github.com/msarilar/EDEngineer/blob/master/EDEngineer/Resources/Data/blueprints.json#L10810

just missing the ingredients :)
