### ISSUE TITLE
New Blueprints Update 21/11/2016 (link to forum post inside)

### ISSUE THREAD

**Issue by msarilar** [msarilar/EDEngineer#93]
Looking for help to update the blueprint json : https://github.com/msarilar/EDEngineer/blob/master/EDEngineer/Resources/Data/blueprints.json

New Recipes:

- Unlock Grade 5 Burst Laser from Broo Tarquin.
- Unlock Grade 5 Beam Laser from Broo Tarquin .
- Unlock Grade 5 Mines from Juri Ishmaak.
- Unlock Grade 5 Missiles from Liz Ryder.
- Unlock Grade 5 Torpedos from Liz Ryder.
- Unlock Grade 5 Railguns from Tod ‘The Blaster’ McQuinn.
- Unlock Grade 4&5 Hull Reinforcement Thermal/Kinetic/Explosive resistance Blueprints from Selene Jean.
- Unlock Grade 4&5 Armour Thermal/Kinetic/Explosive and Advanced Blueprints from Selene Jean.
- Unlock Grade 4&5 Shield Booster Thermal/Kinetic/Explosive Blueprints from Didi Vatermann

https://forums.frontier.co.uk/showthread.php/309695-2-2-Update-Engineer-Blueprint-Balance-Adjustments

Be very careful with the json:
* All strings should be case sensitive!
* All strings should already exist somewhere in the file (it's always the same ingredients being reused)

**Comment by rosscarlson** [comment]
I see this is still open, does it still need to be done?  Am I right that it's not necessarily hard, I'd just follow the same format for each of the entries/nodes to be processed correctly?  Happy to give it a go if you need.

**Comment by msarilar** [comment]
> Am I right that it's not necessarily hard, I'd just follow the same format for each of the entries/nodes 

Yes exactly, each blueprint is just a JSON object in the blueprints.json array ! I don't know if the new blueprints are already known though, but if they are feel free to update the json file and open a PR :)

**Comment by rosscarlson** [comment]
You got it, when I have time I'll go through and verify that all the blueprints are in and are correct.  I'll ping you back in a few days when I've had time to play.

**Comment by msarilar** [comment]
fixed in 1.0.4.5

**Comment by msarilar** [comment]
entirely fixed in 1.0.4.6 thanks to @elijahgill in #155
