### ISSUE TITLE
Characters not valid in the commander name

### ISSUE THREAD

**Issue by omicrono** [msarilar/EDEngineer#94]
Hello, first thanks for the great job

The application gives error with my commander name, because it contains the * character and gives error in the system of files. In particular in the line 168 of MainWindowViewModel.cs
The variable {CurrentCommander.Key} contain the * character and is invalid  :-(

Greetings.

**Comment by msarilar** [comment]
mmmh wasn't aware * was an allowed character in commander's name... basically any character that is *not* supported in a filename on windows will make the application fail.

I'll try and fix that tonight

**Comment by msarilar** [comment]
fixed in 819ce70a8b0962299e279a7cc5e21034866f7f48
available next deploy (tonight)

**Comment by msarilar** [comment]
deployed in 1.0.2.2
